import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

for (const width of [390, 1440]) test(`header account menu at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto('/login');
  await page.getByRole('button', { name: 'Enter local preview' }).click();
  const avatar = page.getByRole('button', { name: 'Account menu' });
  await expect(avatar).toBeVisible();
  const pet = await page.getByRole('button', { name: 'Desktop Pet Not Linked' }).boundingBox();
  const account = await avatar.boundingBox();
  expect(pet!.x + pet!.width).toBeLessThanOrEqual(account!.x);
  await expect(page.locator('#app-sidebar').getByText('Settings', { exact: true })).toHaveCount(0);
  await avatar.focus();
  await avatar.press('ArrowDown');
  const menu = page.getByRole('menu', { name: 'Account' });
  await expect(menu.getByRole('menuitem', { name: 'Open settings' })).toBeFocused();
  expect(await menu.getByRole('menuitem').allTextContents()).toEqual(['Settings','Documentation','Appearance','Logout']);
  await expect(menu).toContainText('Local developer');
  const box = await menu.boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width).toBeLessThanOrEqual(width);
  await page.evaluate(() => Promise.all(document.getAnimations().filter(a => Number.isFinite(a.effect?.getComputedTiming().endTime ?? Infinity)).map(a => a.finished.catch(() => undefined))));
  const report = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(report.violations.filter(v => ['serious', 'critical'].includes(v.impact ?? '')).map(v => v.id)).toEqual([]);
  await page.screenshot({ path: `work/screenshots/account-menu-${width}.png` });
  await page.keyboard.press('End');
  await expect(menu.getByRole('menuitem', { name: 'Logout' })).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(menu).toHaveCount(0);
  await expect(avatar).toBeFocused();
  await avatar.click();
  const docs = menu.getByRole('menuitem', { name: 'Documentation' });
  await expect(docs).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  await docs.hover();
  await expect(docs).not.toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
  const appearance = menu.getByRole('menuitem',{name:'Appearance',exact:true});
  await appearance.focus();await appearance.press('ArrowRight');
  await expect(menu.getByRole('menuitemradio',{name:'System',exact:true})).toBeFocused();
  await page.keyboard.press('Escape');await expect(appearance).toBeFocused();
  await page.emulateMedia({colorScheme:'light'});
  await appearance.focus();await appearance.press('ArrowRight');
  await menu.getByRole('menuitemradio',{name:'Dark',exact:true}).click();
  await expect(page.locator('html')).toHaveCSS('background-color','rgb(22, 22, 22)');
  await page.reload();
  await expect(page.locator('html')).toHaveCSS('background-color','rgb(22, 22, 22)');
  await avatar.click();
  await appearance.focus();await appearance.press('ArrowRight');
  await menu.getByRole('menuitemradio',{name:'Light',exact:true}).click();
  await page.emulateMedia({colorScheme:'dark'});
  await expect(page.locator('html')).toHaveCSS('background-color','rgb(246, 246, 246)');
  await appearance.focus();await appearance.press('ArrowRight');
  await menu.getByRole('menuitemradio',{name:'System',exact:true}).click();
  await expect(page.locator('html')).toHaveCSS('background-color','rgb(22, 22, 22)');
  await page.emulateMedia({colorScheme:'light'});
  await expect(page.locator('html')).toHaveCSS('background-color','rgb(246, 246, 246)');
  await menu.getByLabel('Open settings', { exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(avatar).toBeFocused();
  await avatar.click();
  await page.getByLabel('Message Marvin').click();
  await expect(menu).toHaveCount(0);
  await avatar.click();
  await menu.getByRole('menuitem', { name: 'Logout' }).click();
  await expect(page.getByRole('button', { name: 'Enter local preview' })).toBeVisible();
});
