import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function login(page:Page){await page.goto('/login');await page.getByRole('button',{name:'Enter local preview'}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();}
async function fresh(page:Page){await login(page);if(await page.getByLabel('Open navigation').isVisible())await page.getByLabel('Open navigation').click();await page.getByLabel('New conversation',{exact:true}).click();await expect(page.getByText('What’s on your mind?')).toBeVisible();}
async function audit(page:Page){const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations.filter(v=>['critical','serious'].includes(v.impact??'')).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);}
for(const width of [360,768,1440])test(`responsive portal and accessibility at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.goto('/login');await audit(page);await fresh(page);await audit(page);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`work/screenshots/portal-${width}.png`,fullPage:true});
 await page.getByLabel('Open settings',{exact:true}).click();await audit(page);expect(await page.evaluate(()=>document.querySelector('dialog')!.scrollWidth<=document.querySelector('dialog')!.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Your Marvin',exact:true}).click();await audit(page);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByLabel('Open settings',{exact:true})).toBeFocused();
});
test('streaming text, sample repository, restart continuity and cancellation',async({page})=>{
 await fresh(page);await page.getByLabel('Open settings',{exact:true}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();const sample=page.getByRole('button',{name:'Explore a sample repository'});if(await sample.isVisible())await sample.click();await page.getByLabel('Close dialog').click();
 await page.getByLabel('Message Marvin').fill('What changed in the firmware?');await page.getByRole('button',{name:'Send message'}).click();await expect(page.getByRole('button',{name:'Stop response'})).toBeVisible();await expect(page.locator('.repo-card')).toBeVisible();await expect(page.getByRole('button',{name:'Stop response'})).not.toBeVisible({timeout:15000});await expect(page.locator('.assistant-message')).toContainText('sample repository');const url=page.url();await page.reload();await expect(page.locator('.repo-card')).toBeVisible();expect(page.url()).toBe(url);
 await page.getByLabel('Message Marvin').fill('Remember what we discussed earlier');await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('.assistant-message').last()).toContainText('Your previous message was');await expect(page.getByRole('button',{name:'Stop response'})).not.toBeVisible();
 await page.getByLabel('Message Marvin').fill('Another thought');await page.getByRole('button',{name:'Send message'}).click();await page.getByRole('button',{name:'Stop response'}).click();await expect(page.locator('.turn-status').last()).toContainText('Response stopped');await audit(page);
});
test('simulated provisioning, failed Wi-Fi retry, network change and unlink preserve chat',async({page})=>{
 await fresh(page);await page.getByLabel('Open settings',{exact:true}).click();await page.getByRole('button',{name:'Your Marvin',exact:true}).click();const unlink=page.getByRole('button',{name:'Unlink Marvin',exact:true});if(await unlink.isVisible()){await unlink.click();await page.getByRole('button',{name:'Unlink Marvin',exact:true}).click();}await page.getByLabel('Close dialog').click();
 const requests:string[]=[];page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.postData()??'');});
 await page.getByRole('button',{name:'Have a Marvin robot?'}).click();await page.getByRole('button',{name:'Try a simulated Marvin'}).click();await page.getByRole('radio',{name:/Studio/}).click();await audit(page);await page.getByLabel('Wi-Fi password',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'Connect Marvin'}).click();await expect(page.getByRole('alert')).toContainText('password did not work');await page.getByLabel('Wi-Fi password',{exact:true}).fill('unique-secret-not-sent');await page.getByRole('button',{name:'Connect Marvin'}).click();await expect(page.getByText('You and Marvin, connected.')).toBeVisible();await page.getByRole('button',{name:'Back to Marvin'}).click();
 await page.getByRole('button',{name:'Simulated Marvin',exact:true}).click();await page.getByRole('button',{name:'Change Wi-Fi',exact:true}).click();await page.getByRole('button',{name:'Try a simulated Marvin'}).click();await page.getByRole('radio',{name:/Guest network/}).click();await page.getByLabel('Wi-Fi password',{exact:true}).fill('unique-secret-not-sent');await page.getByRole('button',{name:'Connect Marvin'}).click();await expect(page.getByText('Marvin has a new connection.')).toBeVisible();await page.getByRole('button',{name:'Back to Marvin'}).click();
 await page.getByRole('button',{name:'Simulated Marvin',exact:true}).click();await expect(page.locator('dd').first()).toHaveText('Guest network');await page.getByRole('button',{name:'Unlink Marvin',exact:true}).click();await expect(page.getByText('Your chats and Entire connection stay with you.')).toBeVisible();await page.getByRole('button',{name:'Unlink Marvin',exact:true}).click();await expect(page.getByRole('button',{name:'Set up your Marvin',exact:true})).toBeVisible();expect(requests.join(' ')).not.toContain('unique-secret-not-sent');expect(requests.join(' ')).not.toContain('wrong-password');
});
test('unsupported Bluetooth, inactive microphone, and malicious text have truthful safe UX',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'bluetooth',{value:undefined,configurable:true});});
 await fresh(page);await page.getByRole('button',{name:'Have a Marvin robot?'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('Close dialog').click();await page.getByLabel('Talk to Marvin').click();await expect(page.getByText(/Your microphone is off/)).toBeVisible();await page.getByLabel('Close dialog').click();
 await page.getByLabel('Message Marvin').fill('<img src=x onerror="window.compromised=true">');await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('.user-message')).toContainText('<img');expect(await page.evaluate(()=>('compromised' in window))).toBe(false);await expect(page.locator('.messages img')).toHaveCount(0);
});
test('dark theme remains accessible',async({page})=>{await fresh(page);await page.getByLabel('Use dark appearance').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await audit(page);await page.screenshot({path:'work/screenshots/portal-dark.png',fullPage:true});});
