import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function login(page:Page){await page.goto('/login');await page.getByRole('button',{name:'Enter local preview'}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();}
async function fresh(page:Page){await login(page);if(await page.getByLabel('Open navigation').isVisible())await page.getByLabel('Open navigation').click();await page.getByLabel('New conversation',{exact:true}).click();await expect(page.getByText('What’s on your mind?')).toBeVisible();}
async function audit(page:Page){const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations.filter(v=>['critical','serious'].includes(v.impact??'')).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);}
for(const width of [360,768,1440])test(`responsive portal and accessibility at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.goto('/login');await audit(page);await fresh(page);await audit(page);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`work/screenshots/portal-${width}.png`,fullPage:true});
 await page.getByLabel('Open settings',{exact:true}).click();await audit(page);expect(await page.evaluate(()=>document.querySelector('dialog')!.scrollWidth<=document.querySelector('dialog')!.clientWidth)).toBe(true);
 await page.getByRole('button',{name:'Desktop Pet',exact:true}).click();await audit(page);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByLabel('Open settings',{exact:true})).toBeFocused();
});
test('streaming text, sample repository, restart continuity and cancellation',async({page})=>{
 await fresh(page);await page.getByLabel('Open settings',{exact:true}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();const sample=page.getByRole('button',{name:'Explore a sample repository'});if(await sample.isVisible())await sample.click();await page.getByLabel('Close dialog').click();await page.getByLabel('Active repository').selectOption('marvin-firmware');await expect(page.getByLabel('Active repository')).toHaveValue('marvin-firmware');
 await page.getByLabel('Message Marvin').fill('What changed in the firmware?');await page.getByRole('button',{name:'Send message'}).click();await expect(page.getByRole('button',{name:'Stop response'})).toBeVisible();await expect(page.locator('.repo-card')).toBeVisible();await expect(page.getByRole('button',{name:'Stop response'})).not.toBeVisible({timeout:15000});await expect(page.locator('.assistant-message')).toContainText('sample repository');const url=page.url();await page.reload();await expect(page.locator('.repo-card')).toBeVisible();expect(page.url()).toBe(url);
 await page.getByLabel('Message Marvin').fill('Remember what we discussed earlier');await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('.assistant-message').last()).toContainText('Your previous message was');await expect(page.getByRole('button',{name:'Stop response'})).not.toBeVisible();
 await page.getByLabel('Message Marvin').fill('Another thought');await page.getByRole('button',{name:'Send message'}).click();await page.getByRole('button',{name:'Stop response'}).click();await expect(page.locator('.turn-status').last()).toContainText('Response stopped');await audit(page);
});
test('simulated provisioning, failed Wi-Fi retry, network change and unlink preserve chat',async({page})=>{
 await fresh(page);await page.getByLabel('Open settings',{exact:true}).click();await page.getByRole('button',{name:'Desktop Pet',exact:true}).click();const unlink=page.getByRole('button',{name:'Unlink Desktop Pet',exact:true});if(await unlink.isVisible()){await unlink.click();await page.getByRole('button',{name:'Unlink Desktop Pet',exact:true}).click();}await page.getByLabel('Close dialog').click();
 const requests:string[]=[];page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.postData()??'');});
 await page.getByRole('button',{name:'Have a Desktop Pet?'}).click();await page.getByRole('button',{name:'Try a simulated Desktop Pet'}).click();await page.getByRole('radio',{name:/Studio/}).click();await audit(page);await page.getByLabel('Wi-Fi password',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'Connect Desktop Pet'}).click();await expect(page.getByRole('alert')).toContainText('password did not work');await page.getByLabel('Wi-Fi password',{exact:true}).fill('unique-secret-not-sent');await page.getByLabel('Wi-Fi password',{exact:true}).press('Enter');await expect(page.getByText('Your Desktop Pet is connected to Marvin.')).toBeVisible();await page.getByRole('button',{name:'Back to Marvin'}).click();
 await page.getByRole('button',{name:'Simulated Desktop Pet',exact:true}).click();await page.getByRole('button',{name:'Change Wi-Fi',exact:true}).click();await page.getByRole('button',{name:'Try a simulated Desktop Pet'}).click();await page.getByRole('radio',{name:/Guest network/}).click();await page.getByLabel('Wi-Fi password',{exact:true}).fill('unique-secret-not-sent');await page.getByRole('button',{name:'Connect Desktop Pet'}).click();await expect(page.getByText('Your Desktop Pet has a new connection.')).toBeVisible();await page.getByRole('button',{name:'Back to Marvin'}).click();
 await page.getByRole('button',{name:'Simulated Desktop Pet',exact:true}).click();await expect(page.locator('dd').first()).toHaveText('Guest network');await page.getByRole('button',{name:'Unlink Desktop Pet',exact:true}).click();await expect(page.getByText('Your chats and Entire connection stay with you.')).toBeVisible();await page.getByRole('button',{name:'Unlink Desktop Pet',exact:true}).click();await expect(page.getByRole('button',{name:'Set up your Desktop Pet',exact:true})).toBeVisible();expect(requests.join(' ')).not.toContain('unique-secret-not-sent');expect(requests.join(' ')).not.toContain('wrong-password');
});
test('unsupported Bluetooth, inactive microphone, and malicious text have truthful safe UX',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'bluetooth',{value:undefined,configurable:true});});
 await fresh(page);await page.getByRole('button',{name:'Have a Desktop Pet?'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('Close dialog').click();const voice=page.getByLabel('Start live voice conversation');if(await voice.isDisabled())await expect(voice).toHaveAttribute('title','Live voice is not configured');
 await page.getByLabel('Message Marvin').fill('<img src=x onerror="window.compromised=true">');await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('.user-message')).toContainText('<img');expect(await page.evaluate(()=>('compromised' in window))).toBe(false);await expect(page.locator('.messages img')).toHaveCount(0);
});
test('dark theme remains accessible',async({page})=>{await fresh(page);await page.getByLabel('Use dark appearance').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await audit(page);await page.screenshot({path:'work/screenshots/portal-dark.png',fullPage:true});});
test('repository explorer renders provenance, safe snippets, pagination and recoverable errors',async({page})=>{
 // Recorded UI responses exercise rendering; this does not claim a live Entire service test.
 await page.route('**/api/settings',async route=>{const response=await route.fetch();await route.fulfill({json:{...await response.json(),entireState:'connected',entireAvailable:true,repositories:[{id:'entire_test',name:'test/repository',capabilities:['summary','source','search','history']}]}});});
 await page.route(/\/api\/conversations\/[^/]+$/,async route=>{if(route.request().method()!=='GET'){await route.continue();return;}const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,conversation:{...data.conversation,repositoryId:'entire_test'}}});});
 let reads=0;await page.route('**/api/conversations/*/repository/read',async route=>{reads++;if(reads===3){await route.fulfill({status:429,json:{error:{code:'ENTIRE_RATE_LIMITED',message:'Entire is limiting requests. Wait a moment and retry.'}}});return;}await route.fulfill({json:{kind:'repository',repositoryId:'entire_test',title:'Recorded repository evidence',revision:'a'.repeat(40),summary:'Test evidence, not a live read.',source:'entire',files:[],fetchedAt:Date.now(),nextPage:reads===1?2:null,evidence:[{id:'hit',label:'src/main.ts',origin:'git',revision:'a'.repeat(40),path:'src/main.ts',lineStart:3,lineEnd:3,excerpt:'<img src=x onerror="window.compromised=true">'}]}});});
 await fresh(page);await page.getByLabel('Explore repository',{exact:true}).click();await page.getByLabel('Search repository',{exact:true}).fill('retry');await page.getByRole('button',{name:'Search',exact:true}).click();await page.locator('.evidence summary').click();await expect(page.locator('.evidence pre')).toContainText('<img');await expect(page.locator('.evidence img')).toHaveCount(0);await expect(page.locator('.evidence')).toContainText('Committed source');await audit(page);await page.screenshot({path:'work/screenshots/repository-explorer.png',fullPage:true});await page.getByRole('button',{name:'Next page',exact:true}).click();await page.getByRole('button',{name:'Repository overview'}).click();await expect(page.getByRole('alert')).toContainText('limiting requests');await page.getByLabel('Close dialog').click();await expect(page.getByLabel('Message Marvin')).toBeVisible();
});
