import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync} from 'node:fs';
test('privacy controls export messages, save retention, and require explicit deletion confirmation',async({page})=>{
 await page.goto('/login');await page.getByRole('button',{name:'Enter local preview'}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();await page.getByLabel('Message Marvin').fill('Privacy export marker cobalt');await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('.user-message').last()).toContainText('Privacy export marker cobalt');await expect(page.locator('.assistant-message').last()).toBeVisible();await expect(page.getByLabel('Stop response',{exact:true})).not.toBeVisible();
 await page.getByLabel('Open settings',{exact:true}).click();await page.getByRole('button',{name:'Privacy and history'}).click();await page.getByLabel('Keep conversation history').selectOption('30');await expect(page.getByRole('status').filter({hasText:'Retention preference saved.'})).toBeVisible();
 const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations.filter(v=>['critical','serious'].includes(v.impact??''))).toEqual([]);
 const downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Download conversations'}).click();const download=await downloading,path=await download.path();expect(download.suggestedFilename()).toBe('marvin-conversations.jsonl');const data=readFileSync(path!,'utf8');expect(data).toContain('Privacy export marker cobalt');expect(data.trim().split('\n').at(-1)).toContain('"complete":true');
 await page.getByRole('button',{name:'Delete my account',exact:true}).click();await expect(page.getByRole('button',{name:'Delete account',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Keep my account'}).click();await expect(page.getByRole('button',{name:'Delete my account',exact:true})).toBeVisible();await page.getByRole('heading',{name:'Your conversations, your choice.'}).scrollIntoViewIfNeeded();await page.screenshot({path:'work/screenshots/privacy.png',fullPage:true});
});
