import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
let loginCookies:Awaited<ReturnType<ReturnType<Page['context']>['cookies']>>|undefined;
async function startVoice(page:Page){await page.route('**/api/config',async route=>{const r=await route.fetch();await route.fulfill({json:{...await r.json(),voiceAvailable:true}});});if(loginCookies){await page.context().addCookies(loginCookies);await page.goto('/app');}else{await page.goto('/login');await page.getByRole('button',{name:'Enter local preview'}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();loginCookies=await page.context().cookies();}await expect(page.getByLabel('Message Marvin')).toBeVisible();await page.getByLabel('Start live voice conversation').click();}
async function audio(page:Page){await page.addInitScript(()=>{const audit={stopped:0,audioStarts:0,audioStops:0,devices:[] as MediaStreamTrack[]};Object.assign(window,{voiceAudit:audit});const nativeStart=AudioBufferSourceNode.prototype.start,nativeStop=AudioBufferSourceNode.prototype.stop;AudioBufferSourceNode.prototype.start=function(...args:Parameters<typeof nativeStart>){audit.audioStarts++;return nativeStart.apply(this,args);};AudioBufferSourceNode.prototype.stop=function(...args:Parameters<typeof nativeStop>){audit.audioStops++;return nativeStop.apply(this,args);};Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination();const track=dest.stream.getAudioTracks()[0],stop=track.stop.bind(track);track.stop=()=>{audit.stopped++;stop();void ctx.close();};audit.devices.push(track);return dest.stream;}});});}
const pcm=Buffer.alloc(12000).toString('base64');
test('one click starts live voice in chat, plays on its own route and presents one end control',async({page})=>{
 await audio(page);const controls:any[]=[];let send:(e:object)=>void=()=>{};
 await page.routeWebSocket('**/api/voice',ws=>{send=e=>ws.send(JSON.stringify({v:1,...e}));ws.onMessage(raw=>{if(typeof raw!=='string')return;const e=JSON.parse(raw);controls.push(e);if(e.type==='start'){send({type:'ready',sampleRate:24000,routeId:'test'});send({type:'state',state:'listening'});}if(e.type==='mute')send({type:'state',state:e.muted?'muted':'listening'});});});
 await startVoice(page);await expect(page.getByLabel('Live voice status')).toContainText('Let’s talk');await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.devices.length))).toBe(1);await expect(page.getByRole('dialog')).toHaveCount(0);
 send({type:'turn',interactionId:'turn',text:'Recorded voice question.'});send({type:'audio',interactionId:'foreign-turn',pcm});expect(await page.evaluate(()=>((window as any).voiceAudit.audioStarts))).toBe(0);
 send({type:'audio',interactionId:'turn',pcm});send({type:'event',event:{interactionId:'turn',type:'delta',text:'Recorded spoken answer.'}});await expect(page.getByText('Recorded spoken answer.')).toBeVisible();await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.audioStarts))).toBe(1);
 await expect(page.locator('.voice-composer-actions button')).toHaveCount(1);await expect(page.getByRole('button',{name:'Stop Marvin speaking',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Mute microphone',exact:true})).toHaveCount(0);
 const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);await page.screenshot({path:'work/screenshots/voice.png',fullPage:true});
 const start=Date.now();await page.getByRole('button',{name:'End voice conversation',exact:true}).click();expect(Date.now()-start).toBeLessThan(1000);await expect(page.getByLabel('Message Marvin')).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.audioStops))).toBeLessThanOrEqual(1);expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);expect(controls.some(e=>e.type==='stop')).toBe(true);
});
test('permission denial gives recovery guidance and returns to text',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{throw new DOMException('Denied','NotAllowedError');}}));await startVoice(page);await expect(page.getByText(/Microphone access was not allowed/).first()).toBeVisible();await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();
});
test('buffers a burst of Marvin audio instead of reporting an invalid response',async({page})=>{
 await audio(page);let send:(e:object)=>void=()=>{};
 await page.routeWebSocket('**/api/voice',ws=>{send=e=>ws.send(JSON.stringify({v:1,...e}));ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')send({type:'ready',sampleRate:24000,routeId:'test'});});});
 await startVoice(page);await expect(page.getByText('Let’s talk')).toBeVisible();send({type:'turn',interactionId:'turn',text:'A long answer.'});for(let n=0;n<100;n++)send({type:'audio',interactionId:'turn',pcm});
 await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.audioStarts))).toBeGreaterThan(0);await expect(page.getByText('Voice needs attention')).toHaveCount(0);
});
test('voice at 360px is accessible and idle closure releases capture before reconnect',async({page})=>{
 await page.setViewportSize({width:360,height:800});await audio(page);let send:(e:object)=>void=()=>{};await page.routeWebSocket('**/api/voice',ws=>{send=e=>ws.send(JSON.stringify({v:1,...e}));ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')send({type:'ready',sampleRate:24000,routeId:'test'});});});await startVoice(page);await expect(page.getByLabel('Live voice status')).toContainText('Let’s talk');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);send({type:'closed',message:'Voice paused after a quiet moment.'});await expect(page.getByRole('button',{name:'End voice conversation'})).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);await page.screenshot({path:'work/screenshots/voice-mobile.png',fullPage:true});await page.getByRole('button',{name:'End voice conversation'}).click();await expect(page.getByLabel('Start live voice conversation')).toBeVisible();
});

test('voice ends cleanly after microphone loss and releases capture',async({page})=>{await audio(page);await page.routeWebSocket('**/api/voice',ws=>ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')ws.send(JSON.stringify({v:1,type:'ready',sampleRate:24000,routeId:'test'}));}));await startVoice(page);await expect(page.getByLabel('Live voice status')).toContainText('Let’s talk');await page.evaluate(()=>((window as any).voiceAudit.devices[0].dispatchEvent(new Event('ended'))));await expect(page.getByRole('button',{name:'End voice conversation'})).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();});
test('voice reconnects after a transient socket loss without releasing the microphone',async({page})=>{await audio(page);let lose:()=>void=()=>{};await page.routeWebSocket('**/api/voice',ws=>{lose=()=>ws.close({code:1011,reason:'Test failure'});ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')ws.send(JSON.stringify({v:1,type:'ready',sampleRate:24000,routeId:'test'}));});});await startVoice(page);await expect(page.getByLabel('Live voice status')).toContainText('Let’s talk');lose();await expect(page.getByLabel('Live voice status')).toContainText('Let’s talk');expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(0);await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);});
