import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
let loginCookies:Awaited<ReturnType<ReturnType<Page['context']>['cookies']>>|undefined;
async function startVoice(page:Page){await page.route('**/api/config',async route=>{const r=await route.fetch();await route.fulfill({json:{...await r.json(),voiceAvailable:true}});});if(loginCookies){await page.context().addCookies(loginCookies);await page.goto('/app');}else{await page.goto('/login');await page.getByRole('button',{name:'Enter local preview'}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();loginCookies=await page.context().cookies();}await expect(page.getByLabel('Message Marvin')).toBeVisible();await page.getByLabel('Start live voice conversation').click();}
async function audio(page:Page){await page.addInitScript(()=>{const audit={stopped:0,audioStarts:0,audioStops:0,devices:[] as MediaStreamTrack[]};Object.assign(window,{voiceAudit:audit});const nativeStart=AudioBufferSourceNode.prototype.start,nativeStop=AudioBufferSourceNode.prototype.stop;AudioBufferSourceNode.prototype.start=function(...args:Parameters<typeof nativeStart>){audit.audioStarts++;return nativeStart.apply(this,args);};AudioBufferSourceNode.prototype.stop=function(...args:Parameters<typeof nativeStop>){audit.audioStops++;return nativeStop.apply(this,args);};Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination();const track=dest.stream.getAudioTracks()[0],stop=track.stop.bind(track);track.stop=()=>{audit.stopped++;stop();void ctx.close();};audit.devices.push(track);return dest.stream;}});});}
const pcm=Buffer.alloc(12000).toString('base64');
test('one click starts live voice in chat, plays on its own route, interrupts, mutes and releases microphone',async({page})=>{
 await audio(page);const controls:any[]=[];let send:(e:object)=>void=()=>{};
 await page.routeWebSocket('**/api/voice',ws=>{send=e=>ws.send(JSON.stringify({v:1,...e}));ws.onMessage(raw=>{if(typeof raw!=='string')return;const e=JSON.parse(raw);controls.push(e);if(e.type==='start'){send({type:'ready',sampleRate:24000,routeId:'test'});send({type:'state',state:'listening'});}if(e.type==='mute')send({type:'state',state:e.muted?'muted':'listening'});});});
 await startVoice(page);await expect(page.getByLabel('Live voice conversation')).toContainText('Let’s talk');await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.devices.length))).toBe(1);await expect(page.getByRole('dialog')).toHaveCount(0);
 send({type:'turn',interactionId:'turn',text:'Recorded voice question.'});send({type:'audio',interactionId:'foreign-turn',pcm});expect(await page.evaluate(()=>((window as any).voiceAudit.audioStarts))).toBe(0);
 send({type:'audio',interactionId:'turn',pcm});send({type:'event',event:{interactionId:'turn',type:'delta',text:'Recorded spoken answer.'}});await expect(page.getByText('Recorded spoken answer.')).toBeVisible();await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.audioStarts))).toBe(1);
 const start=Date.now();await page.getByRole('button',{name:'Stop Marvin speaking',exact:true}).click();await expect.poll(()=>page.evaluate(()=>((window as any).voiceAudit.audioStops))).toBe(1);expect(Date.now()-start).toBeLessThan(1000); // Browser scheduling check, not acoustic p95 acceptance.
 send({type:'audio',interactionId:'turn',pcm});await page.getByRole('button',{name:'Mute microphone',exact:true}).click();await expect(page.getByLabel('Live voice conversation')).toContainText('Microphone muted');expect(await page.evaluate(()=>((window as any).voiceAudit.devices[0].enabled))).toBe(false);
 const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);await page.screenshot({path:'work/screenshots/voice.png',fullPage:true});
 await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);expect(controls.some(e=>e.type==='stop')).toBe(true);expect(controls.some(e=>e.type==='interrupt')).toBe(true);
});
test('permission denial gives recovery guidance and returns to text',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{throw new DOMException('Denied','NotAllowedError');}}));await startVoice(page);await expect(page.getByText(/Microphone access was not allowed/).first()).toBeVisible();await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();
});
test('voice at 360px is accessible and idle closure releases capture before reconnect',async({page})=>{
 await page.setViewportSize({width:360,height:800});await audio(page);let send:(e:object)=>void=()=>{};await page.routeWebSocket('**/api/voice',ws=>{send=e=>ws.send(JSON.stringify({v:1,...e}));ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')send({type:'ready',sampleRate:24000,routeId:'test'});});});await startVoice(page);await expect(page.getByLabel('Live voice conversation')).toContainText('Let’s talk');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);send({type:'closed',message:'Voice paused after a quiet moment.'});await expect(page.getByRole('button',{name:'Retry voice'})).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);await page.screenshot({path:'work/screenshots/voice-mobile.png',fullPage:true});await page.getByRole('button',{name:'End voice conversation'}).click();await expect(page.getByLabel('Start live voice conversation')).toBeVisible();
});

for(const failure of ['device','socket'])test(`voice recovers from ${failure} loss and releases the microphone`,async({page})=>{await audio(page);let lose:()=>void=()=>{};await page.routeWebSocket('**/api/voice',ws=>{lose=()=>ws.close({code:1011,reason:'Test failure'});ws.onMessage(raw=>{if(typeof raw==='string'&&JSON.parse(raw).type==='start')ws.send(JSON.stringify({v:1,type:'ready',sampleRate:24000,routeId:'test'}));});});await startVoice(page);await expect(page.getByLabel('Live voice conversation')).toContainText('Let’s talk');if(failure==='device')await page.evaluate(()=>((window as any).voiceAudit.devices[0].dispatchEvent(new Event('ended'))));else lose();await expect(page.getByRole('button',{name:'Retry voice'})).toBeVisible();expect(await page.evaluate(()=>((window as any).voiceAudit.stopped))).toBe(1);await page.getByRole('button',{name:'End voice conversation',exact:true}).click();await expect(page.getByLabel('Message Marvin')).toBeVisible();});
