import { useEffect,useRef,useState,useCallback } from 'react';
import { ArrowUp,ArrowUpRight,ArrowRight,Plus,MessageSquare,Settings as SettingsIcon,PanelLeftClose,PanelLeft,ChevronDown,AudioWaveform,Square,ExternalLink,GitBranch,Check,Sun,Moon,LogOut,Wifi,Link2,Shield,Volume2,Mic,MicOff,SlidersHorizontal,Unplug,BookOpen,ChevronRight,Code2,RotateCcw,AlertCircle,Gamepad2,X,Battery,BatteryCharging,Eye } from 'lucide-react';
import Markdown from 'react-markdown';
import type { AgentEvent,Conversation,Turn,RepoCard } from '../../../packages/contracts/src/index';
import { api,setCsrf,ApiError } from './api';
import { Face } from './Face';
import { Dialog } from './Dialog';
import { PhysicalSetup } from './PhysicalSetup';
import { RepositoryCard as Card } from './RepositoryCard';
import { RepositoryPanel } from './RepositoryPanel';
import { PrivacyPanel } from './PrivacyPanel';
import { VoiceComposer,VoiceConversation,useVoiceSession } from './VoicePanel';
type Owner={id:string;name:string;activeConversation:string|null;petConversation:string|null};
type Config={authMode:string;oidcLabel:string;provider:string;development:boolean;deploymentMode:'local-dev'|'local-secure'|'cloud';localDevSetupAvailable:boolean;docsUrl:string;voiceAvailable:boolean;voiceStatus?:'ready'|'billing_required'|'unavailable';hardwareProvisioningAvailable:boolean};
type Settings={entireState:string;entireStatus?:'connected'|'host_unavailable'|'configuration_error'|'ready'|'repository_required';entireAvailable?:boolean;entireError?:string;body:null|{device_id:string;network:string;simulated:number};repositories:{id:string;name:string;capabilities?:string[]}[];provider:string};
type PetAudio={volume:number;muted:boolean;microphoneGainDb?:number;allowPlaybackMic?:boolean;followupSeconds?:number};
type BatteryStatus={levelPercent:number|null;voltageMv:number|null;charging:boolean|null};
type HeadCalibration={yawCenter:number;pitchCenter:number;yawReversed:boolean;pitchReversed:boolean};
type EyeSettings={design:'classic'|'solid'|'friendly'};
type RobotPresence={body:Settings['body'];presence:null|{deviceId:string;status:'online';capabilities:string[];audioSettings:PetAudio|null;headCalibration:HeadCalibration|null;batteryStatus:BatteryStatus|null;eyeSettings:EyeSettings|null}};
function entireDescription(settings:Settings|null){
 if(settings?.entireStatus==='host_unavailable')return 'The Marvin application cannot reach the Entire connection on this computer.';
 if(settings?.entireStatus==='configuration_error')return 'Entire is reachable, but its repository access needs attention.';
 if(settings?.entireStatus==='repository_required')return 'Entire is available. Choose which repositories Marvin may read.';
 if(settings?.entireAvailable)return 'Your Entire connection is ready. Connect to verify access and choose a repository.';
 return 'Entire has not finished connecting on this computer.';
}
type Session={owner:Owner;csrf:string}|null;
function SafeMarkdown({text}:{text:string}){return <Markdown skipHtml components={{a:({href,children})=><a href={href&&/^(https?:|\/)/.test(href)?href:undefined} target="_blank" rel="noopener noreferrer">{children}</a>,img:()=>null}}>{text}</Markdown>;}
function PetAudioControls({value,onChange,compact=false,disabled=false}:{value:PetAudio;onChange:(value:PetAudio,debounce?:boolean)=>void;compact?:boolean;disabled?:boolean}){
 return <div className={`pet-audio-controls ${compact?'compact':''}`} aria-label="Desktop Pet audio controls">
  <div className="pet-volume"><Volume2 size={compact?15:18}/><label><span>{compact?'Volume':`Speaker volume ${value.volume}%`}</span><input aria-label="Desktop Pet volume" type="range" min="0" max="100" step="5" value={value.volume} disabled={disabled} onChange={e=>onChange({...value,volume:Number(e.target.value)},true)}/></label>{compact&&<output aria-label="Desktop Pet volume level">{value.volume}</output>}</div>
  <button type="button" className={`pet-mute ${value.muted?'is-muted':''}`} disabled={disabled} aria-label={value.muted?'Unmute Desktop Pet microphone':'Mute Desktop Pet microphone'} aria-pressed={value.muted} onClick={()=>onChange({...value,muted:!value.muted})}>{value.muted?<MicOff size={compact?16:18}/>:<Mic size={compact?16:18}/>}<span>{value.muted?'Mic muted':'Mute mic'}</span></button>
 </div>;
}
function PetBattery({value}:{value:BatteryStatus}){
 if(value.levelPercent===null)return null;
 const charging=value.charging===true,description=`Desktop Pet battery ${value.levelPercent}%${charging?', charging':''}`;
 const Icon=charging?BatteryCharging:Battery;
 return <div className={`pet-battery ${charging?'is-charging':''}`} role="status" aria-label={description} title={value.voltageMv===null?description:`${description} · ${value.voltageMv} mV`}><Icon size={18} aria-hidden="true"/><span>{value.levelPercent}%</span></div>;
}
function HeadCalibrationControls({value,onSave}:{value:HeadCalibration;onSave:(value:HeadCalibration)=>Promise<void>}){
 const [draft,setDraft]=useState(value),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>setDraft(value),[value.yawCenter,value.pitchCenter,value.yawReversed,value.pitchReversed]);
 const changed=JSON.stringify(draft)!==JSON.stringify(value);
 async function save(){setSaving(true);setSaved(false);try{await onSave(draft);setSaved(true);}catch{}finally{setSaving(false);}}
 return <div className="head-calibration">
  <div className="calibration-axis"><label htmlFor="head-yaw-center"><span>Left / right center</span><output>{draft.yawCenter}°</output></label><input id="head-yaw-center" aria-label="Head left and right center" type="range" min="60" max="120" step="1" value={draft.yawCenter} onChange={e=>{setSaved(false);setDraft({...draft,yawCenter:Number(e.target.value)});}}/><label className="calibration-reverse"><span>Reverse left and right</span><input type="checkbox" checked={draft.yawReversed} onChange={e=>{setSaved(false);setDraft({...draft,yawReversed:e.target.checked});}}/></label></div>
  <div className="calibration-axis"><label htmlFor="head-pitch-center"><span>Up / down center</span><output>{draft.pitchCenter}°</output></label><input id="head-pitch-center" aria-label="Head up and down center" type="range" min="60" max="120" step="1" value={draft.pitchCenter} onChange={e=>{setSaved(false);setDraft({...draft,pitchCenter:Number(e.target.value)});}}/><label className="calibration-reverse"><span>Reverse up and down</span><input type="checkbox" checked={draft.pitchReversed} onChange={e=>{setSaved(false);setDraft({...draft,pitchReversed:e.target.checked});}}/></label></div>
  <div className="calibration-actions"><button className="button secondary" type="button" disabled={saving||(!changed&&saved)} onClick={()=>void save()}>{saving?'Centering…':changed?'Save and center head':'Center head'}</button><button className="text-button" type="button" disabled={saving} onClick={()=>{setSaved(false);setDraft({yawCenter:90,pitchCenter:90,yawReversed:true,pitchReversed:true});}}>Restore defaults</button></div>
  {saved&&<p role="status" className="calibration-saved"><Check size={15}/> Calibration saved on your Desktop Pet.</p>}
 </div>;
}
type RemoteControlProps={
 online:boolean;
 capabilities:string[];
 batteryStatus:BatteryStatus|null;
 voiceAvailable:boolean;
 voiceStatus?:Config['voiceStatus'];
 speech:string;
 speaking:boolean;
 speechNotice:string;
 onSpeechChange:(value:string)=>void;
 onSpeak:()=>void;
 onError:(error:unknown)=>void;
 onClose:()=>void;
};
function RemoteControl({online,capabilities,batteryStatus,voiceAvailable,voiceStatus,speech,speaking,speechNotice,onSpeechChange,onSpeak,onError,onClose}:RemoteControlProps){
 const [drive,setDrive]=useState({x:0,y:0}),[head,setHead]=useState({x:0,y:0}),[autonomousHead,setAutonomousHead]=useState(true),[active,setActive]=useState<'drive'|'head'|null>(null);
 const [remoteReady,setRemoteReady]=useState(false);
 const driveRef=useRef<HTMLDivElement>(null),headRef=useRef<HTMLDivElement>(null),intent=useRef({x:0,y:0,hx:0,hy:0,auto:true,sequence:0}),remoteSocket=useRef<WebSocket|null>(null);
 const enabled=online&&capabilities.includes('remote');
 useEffect(()=>{intent.current={...intent.current,x:drive.x,y:drive.y,hx:head.x,hy:head.y,auto:autonomousHead};},[drive,head,autonomousHead]);
 const sendIntent=useCallback((next= intent.current)=>{const socket=remoteSocket.current;if(socket?.readyState!==WebSocket.OPEN||!remoteReady)return;socket.send(JSON.stringify({v:1,type:'intent',sequence:++intent.current.sequence,throttle:-next.y,turn:next.x,headYaw:next.hx,headPitch:-next.hy,autonomousHead:next.auto}));},[remoteReady]);
 const stopAll=useCallback(()=>{const next={...intent.current,x:0,y:0,hx:0,hy:0};intent.current=next;setActive(null);setDrive({x:0,y:0});setHead({x:0,y:0});sendIntent(next);},[sendIntent]);
 useEffect(()=>{document.body.classList.add('remote-open');return()=>document.body.classList.remove('remote-open');},[]);
 useEffect(()=>{const stop=()=>stopAll(),visibility=()=>{if(document.hidden)stopAll();};window.addEventListener('blur',stop);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',visibility);};},[stopAll]);
 useEffect(()=>{
  if(!enabled){setRemoteReady(false);return;}
  let stopped=false,retry:ReturnType<typeof setTimeout>|undefined,delay=300;
  const connect=()=>{if(stopped)return;const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/remote`);remoteSocket.current=socket;
   socket.onmessage=event=>{try{const message=JSON.parse(event.data);if(message.type==='ready'){delay=300;setRemoteReady(true);}}catch{socket.close(4400,'Invalid server message');}};
   socket.onclose=event=>{if(remoteSocket.current===socket)remoteSocket.current=null;setRemoteReady(false);if(!stopped){if(event.code===4409||event.code===4401){onError(new Error(event.reason||'Remote control ended.'));return;}retry=setTimeout(connect,delay);delay=Math.min(delay*2,2000);}};
  };connect();return()=>{stopped=true;setRemoteReady(false);if(retry)clearTimeout(retry);const socket=remoteSocket.current;remoteSocket.current=null;if(socket?.readyState===WebSocket.OPEN)socket.close(1000,'Remote control closed');};
 },[enabled,onError]);
 useEffect(()=>{if(!remoteReady||!active)return;const timer=setInterval(()=>sendIntent(),50);sendIntent();return()=>clearInterval(timer);},[active,remoteReady,sendIntent]);
 function position(event:React.PointerEvent<HTMLDivElement>,target:React.RefObject<HTMLDivElement|null>,set:(value:{x:number;y:number})=>void){const rect=target.current?.getBoundingClientRect();if(!rect)return;set({x:Math.max(-1,Math.min(1,(event.clientX-rect.left)/rect.width*2-1)),y:Math.max(-1,Math.min(1,(event.clientY-rect.top)/rect.height*2-1))});}
 function stick(kind:'drive'|'head',event:React.PointerEvent<HTMLDivElement>){const target=kind==='drive'?driveRef:headRef;const set=kind==='drive'?setDrive:setHead;event.currentTarget.setPointerCapture(event.pointerId);setActive(kind);position(event,target,set);}
 function release(kind:'drive'|'head'){if(active===kind)setActive(null);const next={...intent.current,...(kind==='drive'?{x:0,y:0}:{hx:0,hy:0})};intent.current=next;(kind==='drive'?setDrive:setHead)({x:0,y:0});sendIntent(next);}
 const status=!enabled?'Firmware update required':remoteReady?'Connected':'Connecting';
 const speechDisabled=!online||!voiceAvailable||voiceStatus==='billing_required'||speaking;
 const speechHelp=voiceStatus==='billing_required'?'Voice needs API credit before Marvin can speak.':voiceAvailable?'Type a line and hear it through your Desktop Pet.':'Voice is not configured on this server.';
 return <div className="remote-screen" role="dialog" aria-modal="true" aria-label="Remote control">
  <header className="remote-header"><div><p className="eyebrow">LIVE REMOTE</p><h2>Drive Marvin</h2></div><div>{batteryStatus&&<PetBattery value={batteryStatus}/>}<span className={`remote-status ${remoteReady?'':'offline'}`}>{status}</span><button className="icon-button" aria-label="Close remote control" onClick={onClose}><X size={21}/></button></div></header>
  <main className="remote-main">
   <section className="remote-intro"><p>Guide Marvin with the body stick. The firmware makes starts, stops, and turns feel smooth.</p><label className="autonomous-switch"><span><b>Autonomous Head</b><small>Marvin looks into turns and scans while driving.</small></span><input type="checkbox" checked={autonomousHead} onChange={e=>setAutonomousHead(e.target.checked)} disabled={!remoteReady}/></label></section>
   <div className="remote-sticks"><section><div className="stick-label"><b>Drive</b><span>Forward · turn</span></div><div ref={driveRef} className={`analog-stick ${active==='drive'?'active':''}`} aria-label="Drive joystick" aria-disabled={!remoteReady} onPointerDown={e=>remoteReady&&stick('drive',e)} onPointerMove={e=>active==='drive'&&position(e,driveRef,setDrive)} onPointerUp={()=>release('drive')} onPointerCancel={()=>release('drive')}><i style={{left:`${50+drive.x*32.5}%`,top:`${50+drive.y*32.5}%`}}/></div></section><section><div className="stick-label"><b>Head</b><span>Look around</span></div><div ref={headRef} className={`analog-stick ${active==='head'?'active':''}`} aria-label="Head joystick" aria-disabled={!remoteReady} onPointerDown={e=>remoteReady&&stick('head',e)} onPointerMove={e=>active==='head'&&position(e,headRef,setHead)} onPointerUp={()=>release('head')} onPointerCancel={()=>release('head')}><i style={{left:`${50+head.x*32.5}%`,top:`${50+head.y*32.5}%`}}/></div></section></div>
   <section className="remote-speech" aria-labelledby="remote-speech-title">
    <div className="remote-speech-heading"><span className="remote-speech-icon"><Volume2 size={19}/></span><div><h3 id="remote-speech-title">Make Marvin say something</h3><p>{speechHelp}</p>{speechNotice&&<p className="notice" role="status">{speechNotice}</p>}</div></div>
    <form onSubmit={event=>{event.preventDefault();onSpeak();}}>
     <label className="sr-only" htmlFor="remote-speech-input">What should Marvin say?</label>
     <div className="remote-speech-composer"><textarea id="remote-speech-input" aria-label="What should Marvin say?" value={speech} maxLength={500} rows={2} placeholder="Your latest build is ready to review." disabled={speechDisabled} onChange={event=>onSpeechChange(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.metaKey&&!event.nativeEvent.isComposing){event.preventDefault();onSpeak();}}}/><button className="button primary" disabled={!speech.trim()||speechDisabled}>{speaking?'Sending…':'Speak'}<Volume2 size={16}/></button></div>
     <div className="remote-speech-meta"><span>Enter to speak · Shift + Enter for a new line</span><output aria-label="Speech character count">{speech.length}/500</output></div>
    </form>
   </section>
   <p className="remote-safety">Keep Marvin on a clear, level surface and within sight. Releasing a stick or losing the connection eases the tracks to a stop.</p>
  </main>
 </div>;
}
export function App(){
 const [config,setConfig]=useState<Config|null>(null),[session,setSession]=useState<Session>(null),[ready,setReady]=useState(false),[workspaceReady,setWorkspaceReady]=useState(false),[showLoading,setShowLoading]=useState(false),[error,setError]=useState(''),[passphrase,setPassphrase]=useState(''),[loginBusy,setLoginBusy]=useState(false),[conversations,setConversations]=useState<Conversation[]>([]),[petConversation,setPetConversation]=useState<string|null>(null),[current,setCurrent]=useState<Conversation|null>(null),[turns,setTurns]=useState<Turn[]>([]),[settings,setSettings]=useState<Settings|null>(null),[robotOnline,setRobotOnline]=useState(false),[robotCapabilities,setRobotCapabilities]=useState<string[]>([]),[petAudio,setPetAudio]=useState<PetAudio|null>(null),[batteryStatus,setBatteryStatus]=useState<BatteryStatus|null>(null),[headCalibration,setHeadCalibration]=useState<HeadCalibration|null>(null),[eyeSettings,setEyeSettings]=useState<EyeSettings|null>(null),[petSpeech,setPetSpeech]=useState(''),[petSpeechNotice,setPetSpeechNotice]=useState(''),[speaking,setSpeaking]=useState(false),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[sidebar,setSidebar]=useState(window.innerWidth>767),[modal,setModal]=useState<string|null>(null),[settingsTab,setSettingsTab]=useState('Connections'),[setup,setSetup]=useState<'new'|'change'|null>(null),[confirmUnlink,setConfirmUnlink]=useState(false),[unlinkNotice,setUnlinkNotice]=useState(''),[toolStatus,setToolStatus]=useState(''),[connection,setConnection]=useState('connecting'),[theme,setTheme]=useState(()=>localStorage.getItem('marvin-theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
 const pending=useRef<{id:string;text:string;conversationId:string}|null>(null);
 const routeId=useRef(sessionStorage.getItem('marvin-route')??crypto.randomUUID()),input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null),currentRef=useRef<string|null>(null),sessionRef=useRef(session),socket=useRef<WebSocket|null>(null),audioTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 currentRef.current=current?.id??null;sessionRef.current=session;
 const requestError=useCallback((e:unknown)=>{if(e instanceof ApiError&&e.code==='UNAUTHENTICATED'){setSession(null);setCsrf('');}if(e instanceof ApiError&&e.code==='ORIGIN_FORBIDDEN')return;setError((e as Error).message);},[]);
 const loadSettings=useCallback(async()=>{setSettings(await api<Settings>('/settings'));},[]);
 const loadHistory=useCallback(async()=>{const [history,link]=await Promise.all([api<Conversation[]>('/conversations'),api<{conversationId:string|null}>('/robot/conversation')]);setConversations(history);setPetConversation(link.conversationId);},[]);
 const refresh=useCallback(async(id:string)=>{const data=await api<{conversation:Conversation;turns:Turn[]}>('/conversations/'+id);if(currentRef.current===id){setCurrent(data.conversation);setTurns(old=>data.turns.map(t=>{const newer=old.find(v=>v.id===t.id);return newer&&newer.lastSeq>t.lastSeq?newer:t;}));}},[]);
 const refreshVoice=useCallback(()=>{const id=currentRef.current;if(id){void refresh(id).catch(requestError);void loadHistory().catch(requestError);}},[refresh,loadHistory,requestError]);
 const voice=useVoiceSession({conversationId:current?.id,available:!!config?.voiceAvailable,onRefresh:refreshVoice});
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('marvin-theme',theme);},[theme]);
 useEffect(()=>()=>{if(audioTimer.current)clearTimeout(audioTimer.current);},[]);
 useEffect(()=>{sessionStorage.setItem('marvin-route',routeId.current);const fonts=Promise.allSettled(['400 16px Barlow','500 16px Barlow','600 16px Barlow','600 16px "Barlow Condensed"','400 16px "IBM Plex Mono"'].map(font=>document.fonts.load(font)));void Promise.all([api<Config>('/config'),api<Session>('/auth/session'),fonts]).then(([c,s])=>{setConfig(c);setSession(s);setCsrf(s?.csrf??'');}).catch(requestError).finally(()=>setReady(true));},[requestError]);
 useEffect(()=>{
  if(!session){setWorkspaceReady(false);return;}
  let alive=true;setWorkspaceReady(false);
  void(async()=>{const [history,prefs,link]=await Promise.all([api<Conversation[]>('/conversations'),api<Settings>('/settings'),api<{conversationId:string|null}>('/robot/conversation')]);if(!alive)return;setSettings(prefs);setConversations(history);setPetConversation(link.conversationId);const requested=location.pathname.match(/^\/app\/([\w-]+)$/)?.[1];const selected=history.find(c=>c.id===requested)||history.find(c=>c.id===session.owner.activeConversation)||history[0];const c=selected??await api<Conversation>('/conversations','POST',{});if(!alive)return;if(currentRef.current){await loadHistory();if(alive)setWorkspaceReady(true);return;}setCurrent(c);currentRef.current=c.id;history.length||setConversations([c]);await refresh(c.id);if(!alive)return;historyReplace(c.id);setWorkspaceReady(true);})().catch(requestError);
  return()=>{alive=false;};
 },[session?.owner.id,refresh,loadHistory,requestError]);
 const booting=!ready||!!session&&!workspaceReady;
 useEffect(()=>{if(!booting){setShowLoading(false);return;}const timer=setTimeout(()=>setShowLoading(true),240);return()=>clearTimeout(timer);},[booting]);
 useEffect(()=>{
  if(!session||!settings?.body||settings.body.simulated){setRobotOnline(false);setRobotCapabilities([]);setPetAudio(null);setBatteryStatus(null);setHeadCalibration(null);setEyeSettings(null);return;}
  let alive=true;const check=()=>void api<RobotPresence>('/robot/presence').then(value=>{const presence=value.presence;if(alive){const online=!!presence&&presence.deviceId===settings.body?.device_id&&presence.status==='online';setRobotOnline(online);setRobotCapabilities(online?presence!.capabilities:[]);setPetAudio(online?presence!.audioSettings:null);setBatteryStatus(online?presence!.batteryStatus:null);setHeadCalibration(online?presence!.headCalibration:null);setEyeSettings(online?presence!.eyeSettings:null);}}).catch(()=>{if(alive){setRobotOnline(false);setRobotCapabilities([]);setPetAudio(null);setBatteryStatus(null);setHeadCalibration(null);setEyeSettings(null);}});
  check();const timer=setInterval(check,2000);return()=>{alive=false;clearInterval(timer);};
 },[session?.owner.id,settings?.body?.device_id,settings?.body?.simulated]);
 useEffect(()=>{
  if(!session||!current)return;
  const id=current.id;let stopped=false,reconnect:ReturnType<typeof setTimeout>|undefined;let delay=400;
  function connect(){if(stopped)return;setConnection('connecting');const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);socket.current=ws;
   ws.onopen=()=>{delay=400;ws.send(JSON.stringify({v:1,type:'subscribe',conversationId:id,routeId:routeId.current,after:0}));};
   ws.onmessage=message=>{const event=JSON.parse(message.data) as Omit<AgentEvent,'type'> & {type:string};if(currentRef.current!==id)return;
    if(event.type==='subscribed'){setConnection('connected');void refresh(id).catch(requestError);return;}
    if(event.type==='conversation_link'){void loadHistory().catch(requestError);return;}
    if(event.type==='started'){void refresh(id).catch(requestError);void loadHistory().catch(requestError);return;}
    if(event.type==='refresh'){void refresh(id).catch(requestError);return;}
    if(event.type==='heartbeat'){void refresh(id).catch(requestError);return;}
    if(!event.interactionId)return;
    if(event.type==='tool')setToolStatus(event.text??'');
    setTurns(old=>{const t=old.find(t=>t.id===event.interactionId);if(!t||event.seq<=t.lastSeq)return old;return old.map(t=>t.id!==event.interactionId?t:{...t,lastSeq:event.seq,assistantText:t.assistantText+(event.type==='delta'?event.text??'':''),cards:event.type==='card'&&event.card?[...t.cards,event.card]:t.cards,status:event.type==='completed'?'completed':event.type==='error'?'failed':event.type==='cancelled'?'cancelled':t.status});});
    if(['completed','error','cancelled'].includes(event.type)){setToolStatus('');void refresh(id).catch(requestError);void loadHistory().catch(requestError);if(event.type==='error')setError(event.text??'Response interrupted.');}
   };
   ws.onclose=e=>{if(stopped)return;setConnection('offline');if(e.code===4401){setSession(null);setError('Your session expired. Sign in to continue.');return;}reconnect=setTimeout(connect,delay);delay=Math.min(delay*2,5000);};
   ws.onerror=()=>ws.close();
  }connect();return()=>{stopped=true;clearTimeout(reconnect);socket.current?.close();};
 },[current?.id,session?.owner.id,refresh,loadHistory,requestError]);
 useEffect(()=>{if(turns.length||voice.active)bottom.current?.scrollIntoView({behavior:'instant',block:'end'});},[turns.at(-1)?.assistantText,turns.length,voice.active,voice.view.userText,voice.view.assistantText,voice.view.state]);
 const running=turns.some(t=>t.status==='running');
 async function login(){setLoginBusy(true);setError('');try{const result=await api<NonNullable<Session>>('/auth/login','POST',{...(config?.authMode==='local'?{password:passphrase}:{}),returnTo:location.pathname});setCsrf(result.csrf);setSession(result);setPassphrase('');}catch(e){requestError(e);}finally{setLoginBusy(false);}}
 async function choose(c:Conversation){setCurrent(c);currentRef.current=c.id;setTurns([]);setError('');setToolStatus('');historyReplace(c.id);if(window.innerWidth<768)setSidebar(false);try{await api(`/conversations/${c.id}/activate`,'POST',{});await refresh(c.id);}catch(e){requestError(e);}}
 async function newChat(){try{const c=await api<Conversation>('/conversations','POST',{});await choose(c);await loadHistory();input.current?.focus();}catch(e){requestError(e);}}
 async function togglePetConversation(c:Conversation){try{const result=await api<{conversationId:string|null}>('/robot/conversation','PUT',{conversationId:petConversation===c.id?null:c.id});setPetConversation(result.conversationId);}catch(e){requestError(e);}}
 async function send(){if(!draft.trim()||!current||sending||running)return;const text=draft.trim(),c=current.id,id=pending.current?.text===text&&pending.current.conversationId===c?pending.current.id:crypto.randomUUID();pending.current={id,text,conversationId:c};setSending(true);setError('');setDraft('');const optimistic:Turn={id,conversationId:c,userText:text,assistantText:'',status:'running',routeId:routeId.current,surface:'web_text',createdAt:Date.now(),ordinal:turns.length+1,cards:[],lastSeq:0};setTurns(old=>[...old.filter(t=>t.id!==id),optimistic]);
  try{await api('/turns','POST',{conversationId:c,interactionId:id,text,routeId:routeId.current});pending.current=null;await refresh(c);await loadHistory();}catch(e){setDraft(text);setTurns(old=>old.filter(t=>t.id!==id));requestError(e);void refresh(c).catch(()=>{});}finally{setSending(false);}
 }
 async function cancel(){const t=turns.find(t=>t.status==='running');if(t)try{await api(`/turns/${t.id}/cancel`,'POST',{});await refresh(t.conversationId);}catch(e){requestError(e);}}
 async function entire(action:'fixture'|'disconnect'|'connect'){try{const result=action==='connect'?await api<{repositories:{id:string}[]}>('/entire/connect','POST',{}):await api('/settings/entire','POST',{action}) as {repositories?:{id:string}[]};await loadSettings();if(action==='connect'&&current){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:result.repositories?.some(r=>r.id===current.repositoryId)?current.repositoryId:result.repositories?.[0]?.id??null});await refresh(current.id);}if(action==='disconnect'&&current&&!running){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:null});await refresh(current.id);}if(action==='fixture'&&current){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:'marvin-firmware'});await refresh(current.id);} }catch(e){requestError(e);}}
 async function unlink(){try{const result=await api<{deviceErasureConfirmed:boolean}>('/robot','DELETE');await loadSettings();setConfirmUnlink(false);setUnlinkNotice(result.deviceErasureConfirmed?'Your Desktop Pet is unlinked and ready for setup.':'Your Desktop Pet has been removed from your account. Its previous local account link will be cleared automatically when you connect during setup.');}catch(e){if(e instanceof ApiError&&e.code==='REAUTH_REQUIRED'){setConfirmUnlink(false);setUnlinkNotice('For your security, sign out and sign back in before unlinking this Desktop Pet.');return;}requestError(e);}}
 function updatePetAudio(next:PetAudio,debounce=false){
  setPetAudio(next);if(audioTimer.current)clearTimeout(audioTimer.current);
  const save=()=>void api<PetAudio>('/robot/audio','PATCH',next).catch(e=>{requestError(e);void api<RobotPresence>('/robot/presence').then(value=>setPetAudio(value.presence?.audioSettings??null)).catch(()=>setPetAudio(null));});
  if(debounce)audioTimer.current=setTimeout(save,120);else save();
 }
 async function updateHeadCalibration(next:HeadCalibration){
  try{setHeadCalibration(await api<HeadCalibration>('/robot/head-calibration','PATCH',next));}
  catch(e){requestError(e);const value=await api<RobotPresence>('/robot/presence').catch(()=>null);setHeadCalibration(value?.presence?.headCalibration??null);throw e;}
 }
 async function updateEyeSettings(next:EyeSettings){
  const previous=eyeSettings;setEyeSettings(next);
  try{setEyeSettings(await api<EyeSettings>('/robot/eyes','PATCH',next));}
  catch(e){setEyeSettings(previous);requestError(e);}
 }
 async function speakThroughPet(){
  const text=petSpeech.trim();if(!text||speaking)return;setSpeaking(true);setError('');
  try{const result=await api<{accepted:true;state:'playing'|'queued';position?:number}>('/robot/speak','POST',{text});setPetSpeech('');setPetSpeechNotice(result.state==='queued'?`Queued${result.position?` · position ${result.position}`:''}`:'Sent to Marvin');}
  catch(e){requestError(e);}finally{setSpeaking(false);}
 }
 if(booting||!config)return <div className={`loading-screen ${showLoading||error?'is-visible':''}`} aria-busy="true"><Face/><p>{error||'Opening Marvin…'}</p>{error&&<button className="button secondary" onClick={()=>location.reload()}>Try again</button>}</div>;
 if(!session)return <div className="login-page page-enter"><header className="login-header"><a className="wordmark" href="/">MARVIN<span className="wordmark-dot">.</span></a><a className="text-button" href={config.docsUrl} target="_blank" rel="noreferrer">Build documentation <ArrowUpRight size={15}/></a></header><main className="login-grid"><section className="login-copy"><p className="eyebrow">YOUR PERSONAL WORKSPACE</p><h1>A little Desktop Pet.<br/>A bigger conversation.</h1><p className="login-description">A thoughtful companion for your code, your ideas, and whatever comes next. Start a conversation. Bring a Desktop Pet along when you’re ready.</p><div className="login-form"><h2>Welcome to Marvin</h2><p className="muted">Your conversations, connected in one place.</p>{config.authMode==='oidc'?<a className="button primary full" href={`/api/auth/start?returnTo=${encodeURIComponent(location.pathname)}`}>Continue with {config.oidcLabel}<ArrowRight size={17}/></a>:<form onSubmit={e=>{e.preventDefault();void login();}}>{config.authMode==='local'&&<label className="field">Your local passphrase<input type="password" autoComplete="current-password" required value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></label>}<button className="button primary full" disabled={loginBusy}>{loginBusy?'Signing in…':config.development?'Enter local preview':'Sign in'}<ArrowRight size={17}/></button></form>}{config.development&&<p className="login-note">Local development sign-in. Entire identity integration is not configured.</p>}{(error||new URLSearchParams(location.search).has('error'))&&<p className="error-message" role="alert">{error||'Sign-in was cancelled or expired. Please try again.'}</p>}</div></section><section className="login-illustration"><video className="marvin-login-video" autoPlay loop muted playsInline preload="metadata" poster="/assets/img/marvin-hero-poster-10s.png" aria-label="Desktop Pet driving, pivoting, and looking around"><source src="/assets/video/marvin_moving_20sec_pingpong.mp4" type="video/mp4"/></video></section></main><footer className="login-footer"><span>Made for curious minds.</span><button className="text-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>} {theme==='dark'?'Light':'Dark'} appearance</button></footer></div>;
 return <div className={`app-layout page-enter ${sidebar?'sidebar-open':''}`}><a className="skip-link" href="#conversation">Skip to conversation</a>{sidebar&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
  <aside className="sidebar" aria-label="Conversation navigation"><div className="sidebar-brand"><a className="wordmark" href="/app">MARVIN<span className="wordmark-dot">.</span></a><button className="icon-button" aria-label="Collapse navigation" onClick={()=>setSidebar(false)}><PanelLeftClose size={18}/></button></div><button className="new-chat" aria-label="New conversation" onClick={()=>void newChat()}><Plus size={18}/>New conversation<span>↗</span></button><div className="history-heading">YOUR CONVERSATIONS <span title="Choose which conversation your Desktop Pet uses. Changes take effect when it starts listening again.">PET LINK</span></div><p className="pet-link-help">Use the link icon beside a chat to choose it for your Pet. With no link, it starts a new chat. Changes apply when it starts listening again.</p><nav className="history-list" aria-label="Recent conversations">{conversations.map(c=><div className="history-row" key={c.id} data-conversation-id={c.id}><button className={`history-conversation ${current?.id===c.id?'active':''}`} onClick={()=>void choose(c)} aria-current={current?.id===c.id?'page':undefined}><MessageSquare size={15}/><span>{c.title}</span></button><button className={`history-pet-link ${petConversation===c.id?'linked':''}`} type="button" aria-label={petConversation===c.id?`Remove Desktop Pet link from ${c.title}`:`Link Desktop Pet to ${c.title}`} aria-pressed={petConversation===c.id} title={petConversation===c.id?'Desktop Pet linked · click to remove':'Link Desktop Pet to this conversation'} onClick={()=>void togglePetConversation(c)}>{petConversation===c.id?<Check size={15}/>:<Link2 size={15}/>}</button></div>)}</nav><div className="sidebar-bottom"><a href={config.docsUrl} target="_blank" rel="noreferrer"><BookOpen size={16}/>Build documentation<ArrowUpRight size={14}/></a><button onClick={()=>{setSettingsTab('Connections');setModal('settings');}}><SettingsIcon size={16}/>Settings</button><div className="account-row"><div className="avatar">{session.owner.name[0]}</div><div><strong>{session.owner.name}</strong><small>{config.development?'Local preview':'Personal workspace'}</small></div><button className="icon-button" aria-label="Sign out" onClick={()=>void api('/auth/logout','POST',{}).then(()=>{setSession(null);setCsrf('');setCurrent(null);setTurns([]);setPetConversation(null);history.replaceState({},'','/login');}).catch(requestError)}><LogOut size={16}/></button></div></div></aside>
  <div className="workspace"><header className="workspace-header"><div className="header-left">{!sidebar&&<button className="icon-button" aria-label="Open navigation" onClick={()=>setSidebar(true)}><PanelLeft size={19}/></button>}<div className="repository-select"><GitBranch size={16}/><select aria-label="Active repository" value={current?.repositoryId??''} onChange={e=>{if(current)void api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:e.target.value||null}).then(()=>refresh(current.id)).catch(requestError);}} disabled={running}><option value="">No repository selected</option>{settings?.repositories.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><ChevronDown size={13}/></div>{settings?.entireState==='fixture'&&<span className="badge small">Sample</span>}</div><div className="header-right">{settings?.entireState==='connected'&&current?.repositoryId&&<button className="icon-button" aria-label="Explore repository" onClick={()=>setModal('repository')}><Code2 size={18}/></button>}{robotOnline&&petAudio&&<PetAudioControls compact value={petAudio} onChange={updatePetAudio}/>} {robotOnline&&batteryStatus&&<PetBattery value={batteryStatus}/>} {robotOnline&&<button className="icon-button remote-launch" aria-label="Open remote control" onClick={()=>setModal('remote')}><Gamepad2 size={19}/></button>} {settings&&<button className="body-status" onClick={()=>{if(settings.body){setSettingsTab('Desktop Pet');setModal('settings');}else setSetup('new');}}><span className={`status-dot ${settings.body&&(settings.body.simulated||robotOnline)?'':'muted-dot'}`}/>{!settings.body?'Desktop Pet Not Linked':settings.body.simulated?'Simulated Desktop Pet':robotOnline?'Desktop Pet Online':'Desktop Pet Offline'}</button>}<button className="icon-button theme-button" aria-label={`Use ${theme==='dark'?'light':'dark'} appearance`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" aria-label="Open settings" onClick={()=>setModal('settings')}><SlidersHorizontal size={18}/></button></div></header>
   <main id="conversation" className="conversation-scroll" tabIndex={0}><div className={`conversation-inner ${turns.length||voice.active?'has-messages':''}`}>
    {!turns.length&&!voice.active?<><div className="welcome"><Face large/><p className="eyebrow">A SPACE TO THINK TOGETHER</p><h1>What’s on your mind?</h1><p>Explore your code. Work through an idea.<br/>Pick up right where you left off.</p></div><div className="suggestions">{[{icon:GitBranch,title:'Understand my work',text:'What changed in the firmware?'},{icon:MessageSquare,title:'Think something through',text:'Help me think through a simple onboarding experience.'},{icon:Wifi,title:'Meet my Desktop Pet',text:'How do I set up my Desktop Pet?'}].map(s=><button key={s.title} onClick={()=>{setDraft(s.text);input.current?.focus();}}><s.icon size={19}/><strong>{s.title}</strong><span>{s.text}</span><ArrowUpRight size={15}/></button>)}</div>{settings?.entireState==='disconnected'&&<div className="connect-card"><div className="connection-logo">e<span>↗</span></div><div><strong>Give Marvin a little context.</strong><p>Connect Entire to explore your repositories and the thinking behind your code.</p></div><button className="text-button" onClick={()=>{setSettingsTab('Connections');setModal('settings');}}>Connect Entire<ArrowRight size={15}/></button></div>}{!settings?.body&&<button className="optional-setup" onClick={()=>setSetup('new')}>Have a Desktop Pet? <span>Set up your Desktop Pet</span><ArrowUpRight size={14}/></button>}</>:<div className="messages">{turns.map(t=><section key={t.id} className="turn"><div className="user-message"><div className="message-label">YOU{t.surface==='body_voice'?' · DESKTOP PET':t.surface==='web_voice'?' · VOICE':''}</div><p>{t.userText}</p></div><div className="assistant-message"><div className="message-label"><Face/>MARVIN{t.surface==='body_voice'?' · DESKTOP PET':t.surface==='web_voice'?' · VOICE':''} {t.status==='running'&&<span className="stream-state">{toolStatus||'Thinking with you…'}</span>}</div><div className="markdown"><SafeMarkdown text={t.assistantText}/>{t.cards.map((c,i)=><Card key={i} card={c}/>)}{t.status==='running'&&!t.assistantText&&<div className="typing" aria-label="Marvin is thinking"><i/><i/><i/></div>}{t.status==='cancelled'&&<p className="turn-status">Response stopped. You can continue the conversation.</p>}{t.status==='failed'&&<p className="turn-status"><AlertCircle size={14}/> Response interrupted. Your messages are saved.</p>}</div></div></section>)}{voice.active&&<VoiceConversation session={voice} persisted={turns.some(t=>t.id===voice.view.interactionId)}/>}</div>}
    <div ref={bottom}/></div></main>
   <div className="composer-region">{error&&<div className="inline-error" role="alert"><AlertCircle size={16}/><span>{error}</span><button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}{config.voiceStatus==='billing_required'&&<div className="inline-error" role="alert"><AlertCircle size={16}/><span>Realtime voice is paused because the configured OpenAI account has no remaining API credit. Add credit or update the server’s voice key, then refresh.</span></div>}{connection==='offline'&&<div className="reconnecting" role="status"><RotateCcw size={13}/> Reconnecting… Your conversation is saved.</div>}{voice.active?<VoiceComposer session={voice}/>:<><form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><textarea ref={input} aria-label="Message Marvin" placeholder="Ask Marvin anything…" value={draft} maxLength={12000} rows={2} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div className="composer-tools"><span><span className="status-dot"/> {settings?.provider==='fixture'?'Development preview':'Marvin'}<span className="composer-separator">/</span><span className="composer-context">{current?.repositoryId?'Repository context':'Ready to explore'}</span></span><div><button className="icon-button live-voice-trigger" type="button" aria-label="Start live voice conversation" title={config.voiceStatus==='billing_required'?'Realtime voice needs API credit':config.voiceAvailable?'Start live voice conversation':'Live voice is not configured'} disabled={!!running||!config.voiceAvailable||config.voiceStatus==='billing_required'} onClick={voice.start}><AudioWaveform size={20}/></button>{running?<button className="send-button" type="button" aria-label="Stop response" onClick={()=>void cancel()}><Square size={15} fill="currentColor"/></button>:<button className="send-button" aria-label="Send message" disabled={!draft.trim()||sending}><ArrowUp size={19}/></button>}</div></div></form><p className="composer-note">{settings?.provider==='fixture'?'Responses and repository data are simulated in this preview.':'Marvin can make mistakes. Check important details.'} <span>Shift + Enter for a new line</span></p></>}<div className="sr-only" role="status" aria-live="polite">{voice.active?`Live voice: ${voice.view.state}`:running?'Marvin is responding.':'Ready for your message.'}</div></div>
  </div>
  {modal==='settings'&&<Dialog title="Settings" onClose={()=>{setModal(null);setConfirmUnlink(false);}} wide><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{[{name:'Connections',icon:Link2},{name:'Desktop Pet',icon:Wifi},{name:'Voice and models',icon:Volume2},{name:'Privacy and history',icon:Shield}].map(t=><button key={t.name} className={settingsTab===t.name?'active':''} onClick={()=>{setSettingsTab(t.name);setConfirmUnlink(false);}}><t.icon size={16}/>{t.name}</button>)}</nav><div className="settings-pane">
   {settingsTab==='Connections'&&<><p className="eyebrow">REPOSITORY CONTEXT</p><h3>A connection to your work.</h3><p className="muted">Entire brings together code, checkpoints, and the context behind your decisions.</p><div className="setting-card"><div className="setting-card-title"><div className="connection-logo">e<span>↗</span></div><div><strong>Entire</strong><small>{settings?.entireState==='connected'?'Connected · read-only':settings?.entireState==='fixture'?'Sample connection active':'Not connected'}</small></div>{settings?.entireState!=='disconnected'&&<Check size={18}/>}</div>{settings?.entireState==='connected'?<><p>Marvin checks your repository access before reading. Change repositories in the conversation header. Wi-Fi and your Desktop Pet’s account link are unaffected.</p><button className="button secondary full" onClick={()=>void entire('connect')}>Check connection</button><button className="text-button" onClick={()=>void entire('disconnect')}>Disconnect Entire</button></>:<><p>{entireDescription(settings)}</p>{settings?.entireAvailable&&<button className="button primary full" onClick={()=>void entire('connect')}>Connect Entire</button>}<a className="text-button" href="https://docs.entire.io/cli-reference/login" target="_blank" rel="noreferrer">Entire login documentation <ExternalLink size={13}/></a>{settings?.entireState==='fixture'?<button className="button secondary full" onClick={()=>void entire('disconnect')}>Disconnect sample data</button>:config.development&&<button className="button secondary full" onClick={()=>void entire('fixture')}>Explore a sample repository <ArrowRight size={16}/></button>}</>}{settings?.entireError&&<p className="notice">{settings.entireError}</p>}</div></>}
   {settingsTab==='Desktop Pet'&&<>
    <p className="eyebrow">YOUR PHYSICAL COMPANION</p><h3>{settings?.body?'Meet your Desktop Pet.':'Bring the conversation to life.'}</h3>{unlinkNotice&&<p className="notice" role="status">{unlinkNotice}</p>}
    {!settings?.body?<><div className="settings-robot"><Face large/></div><p className="muted">Link a Desktop Pet whenever you’re ready. Your conversations and repository context will come with you.</p><button className="button primary full" onClick={()=>{setModal(null);setUnlinkNotice('');setSetup('new');}}>Set up your Desktop Pet <ArrowRight size={16}/></button><p className="fine-print">Your browser may label a previously used Desktop Pet “Paired.” Setup verifies its account link after connecting.</p></>:<>
     <div className="setting-card"><div className="robot-summary"><Face/><div><strong>Desktop Pet</strong><small>{settings.body.simulated?'Simulated Desktop Pet · preview only':robotOnline?'Online':'Offline'}</small></div><span className="badge">Linked</span></div><dl className="device-details"><dt>Network</dt><dd>{settings.body.network}</dd><dt>Device</dt><dd><code>{settings.body.device_id}</code></dd></dl><button className="button secondary full" onClick={()=>{setModal(null);setSetup('change');}}><Wifi size={16}/>Change Wi-Fi<ChevronRight size={15}/></button><p className="fine-print">Moved somewhere new? Change the network while keeping the same Desktop Pet linked.</p></div>
     <div className="setting-card pet-audio-card"><div className="setting-card-title"><div><strong>Sound and microphone</strong><small>{petAudio?'Synced with your Desktop Pet':robotOnline?'Audio controls require a firmware update':'Connect your Desktop Pet to change these controls'}</small></div>{petAudio?.muted?<MicOff size={18}/>:<Volume2 size={18}/>}</div>{petAudio?<PetAudioControls value={petAudio} onChange={updatePetAudio}/>:<PetAudioControls value={{volume:60,muted:false}} onChange={()=>{}} disabled/>}<div className="pet-volume pet-microphone-gain"><Mic size={18}/><label><span>Microphone sensitivity {petAudio?.microphoneGainDb!==undefined?`${petAudio.microphoneGainDb} dB`:''}</span><input aria-label="Desktop Pet microphone sensitivity" type="range" min="0" max="36" step="6" value={petAudio?.microphoneGainDb??30} disabled={petAudio?.microphoneGainDb===undefined} onChange={e=>petAudio&&updatePetAudio({...petAudio,microphoneGainDb:Number(e.target.value)},true)}/></label></div>{petAudio&&petAudio.microphoneGainDb===undefined&&<p className="fine-print">Update your Desktop Pet firmware to adjust microphone sensitivity.</p>}<div className="pet-conversation-settings"><strong>Conversation</strong><label className="pet-followup"><span>Listen for a reply <b>{petAudio?.followupSeconds===0?'Off':`${petAudio?.followupSeconds??5} seconds`}</b></span><input aria-label="Desktop Pet follow-up window" type="range" min="0" max="30" step="1" value={petAudio?.followupSeconds??5} disabled={petAudio?.followupSeconds===undefined} onChange={e=>petAudio&&updatePetAudio({...petAudio,followupSeconds:Number(e.target.value)},true)}/><small>After Marvin finishes speaking, you can reply without saying “Hey Marvin.”</small></label><label className="pet-playback-toggle"><span><b>Talk while Marvin speaks</b><small>Uses echo cancellation. Experimental: Marvin may mistake its own voice for yours.</small></span><input aria-label="Allow Desktop Pet microphone during playback" type="checkbox" checked={petAudio?.allowPlaybackMic??false} disabled={petAudio?.allowPlaybackMic===undefined} onChange={e=>petAudio&&updatePetAudio({...petAudio,allowPlaybackMic:e.target.checked})}/></label>{petAudio&&petAudio.followupSeconds===undefined&&<p className="fine-print">Update your Desktop Pet firmware to use conversation controls.</p>}</div><p className="fine-print">The Pet’s side buttons adjust volume and mute. Muting also disables its wake word until you unmute it.</p></div>
     <div className="setting-card eye-design-card"><div className="setting-card-title"><div><strong>Eye design</strong><small>{eyeSettings?'Saved on your Desktop Pet':robotOnline?'Eye designs require a firmware update':'Connect your Desktop Pet to change its eyes'}</small></div><Eye size={18}/></div><label><span className="sr-only">Desktop Pet eye design</span><select aria-label="Desktop Pet eye design" value={eyeSettings?.design??'classic'} disabled={!eyeSettings} onChange={event=>void updateEyeSettings({design:event.target.value as EyeSettings['design']})}><option value="classic">Classic · white with black center</option><option value="solid">Solid · pupil-free</option><option value="friendly">Friendly · smile blink</option></select></label><p className="fine-print">The selection is stored on the Pet and restored whenever it boots.</p></div>
     <div className="setting-card head-calibration-card"><div className="setting-card-title"><div><strong>Head servo calibration</strong><small>{headCalibration?'Saved on your Desktop Pet':robotOnline?'Calibration requires a firmware update':'Connect your Desktop Pet to calibrate its head'}</small></div><SlidersHorizontal size={18}/></div>{headCalibration?<><p>Adjust the neutral position and direction for each head servo. Saving moves the head gently to its new center.</p><HeadCalibrationControls value={headCalibration} onSave={updateHeadCalibration}/><p className="fine-print">Keep Marvin on a clear surface and stay within reach while calibrating.</p></>:<fieldset className="head-calibration-disabled" disabled><HeadCalibrationControls value={{yawCenter:90,pitchCenter:90,yawReversed:true,pitchReversed:true}} onSave={async()=>{}}/></fieldset>}</div>
     <div className="ownership-section">{confirmUnlink?<><h4>Unlink this Desktop Pet?</h4><p>Your Desktop Pet loses access to your account immediately. <strong>Your chats and Entire connection stay with you.</strong> If your Desktop Pet is offline, its local account link will be cleared during the next setup. Reset it before giving it to someone else if you also want to erase Wi-Fi settings.</p><div className="wizard-actions"><button className="button secondary" onClick={()=>setConfirmUnlink(false)}>Keep linked</button><button className="button danger" onClick={()=>void unlink()}>Unlink Desktop Pet</button></div></>:<><h4>Account link</h4><p>Unlink your Desktop Pet if you’re replacing it or giving it to someone else.</p><button className="text-button danger-text" onClick={()=>setConfirmUnlink(true)}><Unplug size={15}/>Unlink Desktop Pet</button></>}</div>
    </>}
   </>}
   {settingsTab==='Voice and models'&&<><p className="eyebrow">ONE VOICE. ONE MARVIN.</p><h3>How Marvin responds.</h3><div className="setting-card"><strong>Text provider</strong><p>{settings?.provider==='fixture'?'Deterministic development preview.':`${settings?.provider==='anthropic'?'Anthropic':'OpenAI'} · configured on the server.`}</p><p className="fine-print">Your server administrator configures the model. Provider credentials stay on the server.</p></div><div className="setting-card"><strong>Realtime voice</strong><p>{config.voiceStatus==='billing_required'?'Realtime voice is paused because the configured OpenAI account has no remaining API credit. Add credit or update the server key, then refresh.':config.voiceAvailable?'Voice is ready. Select the waveform beside the send button and start talking; your live transcript stays in the conversation.':'Voice is not configured on this server yet. Text conversations remain available.'}</p></div></>}
   {settingsTab==='Privacy and history'&&<PrivacyPanel onError={requestError}/>}
  </div></div></Dialog>}
  {modal==='repository'&&current&&<RepositoryPanel conversationId={current.id} name={settings?.repositories.find(r=>r.id===current.repositoryId)?.name??'Repository'} capabilities={settings?.repositories.find(r=>r.id===current.repositoryId)?.capabilities??[]} onClose={()=>setModal(null)}/>}
  {modal==='remote'&&<RemoteControl online={robotOnline} capabilities={robotCapabilities} batteryStatus={batteryStatus} voiceAvailable={config.voiceAvailable} voiceStatus={config.voiceStatus} speech={petSpeech} speaking={speaking} speechNotice={petSpeechNotice} onSpeechChange={value=>{setPetSpeech(value);setPetSpeechNotice('');}} onSpeak={()=>void speakThroughPet()} onError={requestError} onClose={()=>setModal(null)}/>}
  {setup&&(config.hardwareProvisioningAvailable||config.localDevSetupAvailable)?<PhysicalSetup change={setup==='change'} deviceId={settings?.body?.device_id} localDevSetupAvailable={config.localDevSetupAvailable} onClose={()=>{setSetup(null);void loadSettings().catch(requestError);}} onComplete={()=>{void loadSettings().catch(requestError);}}/>:setup&&<Dialog title="Desktop Pet setup" onClose={()=>setSetup(null)}><p>Secure setup is not configured for this local server yet. Configure its enrollment trust before connecting a Pet; no Bluetooth pairing was attempted.</p></Dialog>}
 </div>;
}
function historyReplace(id:string){history.replaceState({},'','/app/'+id);}
