import { useEffect,useRef,useState,useCallback,lazy,Suspense } from 'react';
import { ArrowUp,ArrowUpRight,ArrowRight,Plus,MessageSquare,Settings as SettingsIcon,PanelLeftClose,PanelLeft,ChevronDown,Mic,Square,ExternalLink,GitBranch,Check,Sun,Moon,LogOut,Wifi,Link2,Shield,Volume2,SlidersHorizontal,Unplug,BookOpen,ChevronRight,Code2,RotateCcw,AlertCircle } from 'lucide-react';
import Markdown from 'react-markdown';
import type { AgentEvent,Conversation,Turn,RepoCard } from '../../../packages/contracts/src/index';
import { api,setCsrf,ApiError } from './api';
import { Face,RobotDrawing } from './Face';
import { Dialog } from './Dialog';
const PhysicalSetup=lazy(()=>import('./PhysicalSetup').then(module=>({default:module.PhysicalSetup})));
import { Setup } from './Setup';
import { RepositoryCard as Card } from './RepositoryCard';
import { RepositoryPanel } from './RepositoryPanel';
import { PrivacyPanel } from './PrivacyPanel';
import { VoicePanel } from './VoicePanel';
type Owner={id:string;name:string;activeConversation:string|null};
type Config={authMode:string;oidcLabel:string;provider:string;development:boolean;docsUrl:string;voiceAvailable:boolean;hardwareProvisioningAvailable:boolean};
type Settings={entireState:string;entireAvailable?:boolean;entireError?:string;body:null|{device_id:string;network:string;simulated:number};repositories:{id:string;name:string;capabilities?:string[]}[];provider:string};
type Session={owner:Owner;csrf:string}|null;
function SafeMarkdown({text}:{text:string}){return <Markdown skipHtml components={{a:({href,children})=><a href={href&&/^(https?:|\/)/.test(href)?href:undefined} target="_blank" rel="noopener noreferrer">{children}</a>,img:()=>null}}>{text}</Markdown>;}
export function App(){
 const [config,setConfig]=useState<Config|null>(null),[session,setSession]=useState<Session>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[passphrase,setPassphrase]=useState(''),[loginBusy,setLoginBusy]=useState(false),[conversations,setConversations]=useState<Conversation[]>([]),[current,setCurrent]=useState<Conversation|null>(null),[turns,setTurns]=useState<Turn[]>([]),[settings,setSettings]=useState<Settings|null>(null),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[sidebar,setSidebar]=useState(window.innerWidth>767),[modal,setModal]=useState<string|null>(null),[settingsTab,setSettingsTab]=useState('Connections'),[setup,setSetup]=useState<'new'|'change'|null>(null),[confirmUnlink,setConfirmUnlink]=useState(false),[toolStatus,setToolStatus]=useState(''),[connection,setConnection]=useState('connecting'),[theme,setTheme]=useState(()=>localStorage.getItem('marvin-theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
 const pending=useRef<{id:string;text:string;conversationId:string}|null>(null);
 const routeId=useRef(sessionStorage.getItem('marvin-route')??crypto.randomUUID()),input=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null),currentRef=useRef<string|null>(null),sessionRef=useRef(session),socket=useRef<WebSocket|null>(null);
 currentRef.current=current?.id??null;sessionRef.current=session;
 const requestError=useCallback((e:unknown)=>{if(e instanceof ApiError&&e.status===401){setSession(null);setCsrf('');}setError((e as Error).message);},[]);
 const loadSettings=useCallback(async()=>{setSettings(await api<Settings>('/settings'));},[]);
 const loadHistory=useCallback(async()=>{setConversations(await api<Conversation[]>('/conversations'));},[]);
 const refresh=useCallback(async(id:string)=>{const data=await api<{conversation:Conversation;turns:Turn[]}>('/conversations/'+id);if(currentRef.current===id){setCurrent(data.conversation);setTurns(old=>data.turns.map(t=>{const newer=old.find(v=>v.id===t.id);return newer&&newer.lastSeq>t.lastSeq?newer:t;}));}},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('marvin-theme',theme);},[theme]);
 useEffect(()=>{sessionStorage.setItem('marvin-route',routeId.current);void Promise.all([api<Config>('/config'),api<Session>('/auth/session')]).then(([c,s])=>{setConfig(c);setSession(s);setCsrf(s?.csrf??'');}).catch(requestError).finally(()=>setReady(true));},[requestError]);
 useEffect(()=>{
  if(!session)return;
  let alive=true;
  void(async()=>{const [history,prefs]=await Promise.all([api<Conversation[]>('/conversations'),api<Settings>('/settings')]);if(!alive)return;setSettings(prefs);setConversations(history);const requested=location.pathname.match(/^\/app\/([\w-]+)$/)?.[1];const selected=history.find(c=>c.id===requested)||history.find(c=>c.id===session.owner.activeConversation)||history[0];const c=selected??await api<Conversation>('/conversations','POST',{});if(!alive)return;setCurrent(c);currentRef.current=c.id;history.length||setConversations([c]);await refresh(c.id);historyReplace(c.id);})().catch(requestError);
  return()=>{alive=false;};
 },[session?.owner.id,refresh,requestError]);
 useEffect(()=>{
  if(!session||!current)return;
  const id=current.id;let stopped=false,reconnect:ReturnType<typeof setTimeout>|undefined;let delay=400;
  function connect(){if(stopped)return;setConnection('connecting');const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);socket.current=ws;
   ws.onopen=()=>{delay=400;ws.send(JSON.stringify({v:1,type:'subscribe',conversationId:id,routeId:routeId.current,after:0}));};
   ws.onmessage=message=>{const event=JSON.parse(message.data) as Omit<AgentEvent,'type'> & {type:string};if(currentRef.current!==id)return;
    if(event.type==='subscribed'){setConnection('connected');void refresh(id).catch(requestError);return;}
    if(event.type==='refresh'){void refresh(id).catch(requestError);return;}
    if(event.type==='heartbeat'){void refresh(id).catch(requestError);return;}
    if(!event.interactionId)return;
    if(event.type==='tool')setToolStatus(event.text??'');
    setTurns(old=>{const t=old.find(t=>t.id===event.interactionId);if(!t||event.seq<=t.lastSeq)return old;return old.map(t=>t.id!==event.interactionId?t:{...t,lastSeq:event.seq,assistantText:t.assistantText+(event.type==='delta'?event.text??'':''),cards:event.type==='card'&&event.card?[...t.cards,event.card]:t.cards,status:event.type==='completed'?'completed':event.type==='error'?'failed':event.type==='cancelled'?'cancelled':t.status});});
    if(['completed','error','cancelled'].includes(event.type)){setToolStatus('');void refresh(id).catch(requestError);void loadHistory().catch(requestError);if(event.type==='error')setError(event.text??'Response interrupted.');}
   };
   ws.onclose=e=>{if(stopped)return;setConnection('offline');if(e.code===4401){setSession(null);setError('Your session expired. Sign in to continue.');return;}reconnect=setTimeout(connect,delay);delay=Math.min(delay*2,5000);};
   ws.onerror=()=>ws.close();
  }connect();return()=>{stopped=true;clearTimeout(reconnect);socket.current?.close();};
 },[current?.id,session?.owner.id,refresh,loadHistory,requestError]);
 useEffect(()=>{if(turns.length)bottom.current?.scrollIntoView({behavior:'instant',block:'end'});},[turns.at(-1)?.assistantText,turns.length]);
 const running=turns.some(t=>t.status==='running');
 async function login(){setLoginBusy(true);setError('');try{const result=await api<NonNullable<Session>>('/auth/login','POST',{...(config?.authMode==='local'?{password:passphrase}:{}),returnTo:location.pathname});setCsrf(result.csrf);setSession(result);setPassphrase('');}catch(e){requestError(e);}finally{setLoginBusy(false);}}
 async function choose(c:Conversation){setCurrent(c);currentRef.current=c.id;setTurns([]);setError('');setToolStatus('');historyReplace(c.id);if(window.innerWidth<768)setSidebar(false);try{await api(`/conversations/${c.id}/activate`,'POST',{});await refresh(c.id);}catch(e){requestError(e);}}
 async function newChat(){try{const c=await api<Conversation>('/conversations','POST',{});await choose(c);await loadHistory();input.current?.focus();}catch(e){requestError(e);}}
 async function send(){if(!draft.trim()||!current||sending||running)return;const text=draft.trim(),c=current.id,id=pending.current?.text===text&&pending.current.conversationId===c?pending.current.id:crypto.randomUUID();pending.current={id,text,conversationId:c};setSending(true);setError('');setDraft('');const optimistic:Turn={id,conversationId:c,userText:text,assistantText:'',status:'running',routeId:routeId.current,surface:'web_text',createdAt:Date.now(),ordinal:turns.length+1,cards:[],lastSeq:0};setTurns(old=>[...old.filter(t=>t.id!==id),optimistic]);
  try{await api('/turns','POST',{conversationId:c,interactionId:id,text,routeId:routeId.current});pending.current=null;await refresh(c);await loadHistory();}catch(e){setDraft(text);setTurns(old=>old.filter(t=>t.id!==id));requestError(e);void refresh(c).catch(()=>{});}finally{setSending(false);}
 }
 async function cancel(){const t=turns.find(t=>t.status==='running');if(t)try{await api(`/turns/${t.id}/cancel`,'POST',{});await refresh(t.conversationId);}catch(e){requestError(e);}}
 async function entire(action:'fixture'|'disconnect'|'connect'){try{const result=action==='connect'?await api<{repositories:{id:string}[]}>('/entire/connect','POST',{}):await api('/settings/entire','POST',{action}) as {repositories?:{id:string}[]};await loadSettings();if(action==='connect'&&current){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:result.repositories?.some(r=>r.id===current.repositoryId)?current.repositoryId:result.repositories?.[0]?.id??null});await refresh(current.id);}if(action==='disconnect'&&current&&!running){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:null});await refresh(current.id);}if(action==='fixture'&&current){await api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:'marvin-firmware'});await refresh(current.id);} }catch(e){requestError(e);}}
 async function unlink(){try{await api('/robot','DELETE');await loadSettings();setConfirmUnlink(false);}catch(e){requestError(e);}}
 if(!ready||!config)return <div className="loading-screen"><Face/><p>{error||'Opening Marvin…'}</p>{error&&<button className="button secondary" onClick={()=>location.reload()}>Try again</button>}</div>;
 if(!session)return <div className="login-page"><header className="login-header"><a className="wordmark" href="/">MARVIN<span className="wordmark-dot">.</span></a><a className="text-button" href={config.docsUrl} target="_blank" rel="noreferrer">Build documentation <ArrowUpRight size={15}/></a></header><main className="login-grid"><section className="login-copy"><p className="eyebrow">YOUR PERSONAL WORKSPACE</p><h1>A little robot.<br/>A bigger conversation.</h1><p className="login-description">A thoughtful companion for your code, your ideas, and whatever comes next. Start a conversation. Bring a robot along when you’re ready.</p><div className="login-form"><h2>Welcome to Marvin</h2><p className="muted">Your conversations, connected in one place.</p>{config.authMode==='oidc'?<a className="button primary full" href={`/api/auth/start?returnTo=${encodeURIComponent(location.pathname)}`}>Continue with {config.oidcLabel}<ArrowRight size={17}/></a>:<form onSubmit={e=>{e.preventDefault();void login();}}>{config.authMode==='local'&&<label className="field">Your local passphrase<input type="password" autoComplete="current-password" required value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></label>}<button className="button primary full" disabled={loginBusy}>{loginBusy?'Signing in…':config.development?'Enter local preview':'Sign in'}<ArrowRight size={17}/></button></form>}{config.development&&<p className="login-note">Local development sign-in. Entire identity integration is not configured.</p>}{(error||new URLSearchParams(location.search).has('error'))&&<p className="error-message" role="alert">{error||'Sign-in was cancelled or expired. Please try again.'}</p>}</div></section><section className="login-illustration" aria-label="Marvin illustration"><div className="drawing-meta"><span>MARVIN / 01</span><span>MOSTLY HARMLESS</span></div><RobotDrawing/><div className="illustration-caption"><span className="status-dot"/><p>One Marvin. Wherever the conversation takes you.</p></div><div className="drawing-note">SOFTWARE FIRST. ROBOT OPTIONAL.</div></section></main><footer className="login-footer"><span>Made for curious minds.</span><button className="text-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>} {theme==='dark'?'Light':'Dark'} appearance</button></footer></div>;
 return <div className={`app-layout ${sidebar?'sidebar-open':''}`}><a className="skip-link" href="#conversation">Skip to conversation</a>{sidebar&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
  <aside className="sidebar" aria-label="Conversation navigation"><div className="sidebar-brand"><a className="wordmark" href="/app">MARVIN<span className="wordmark-dot">.</span></a><button className="icon-button" aria-label="Collapse navigation" onClick={()=>setSidebar(false)}><PanelLeftClose size={18}/></button></div><button className="new-chat" aria-label="New conversation" onClick={()=>void newChat()}><Plus size={18}/>New conversation<span>↗</span></button><div className="history-heading">YOUR CONVERSATIONS</div><nav className="history-list" aria-label="Recent conversations">{conversations.map(c=><button className={current?.id===c.id?'active':''} key={c.id} onClick={()=>void choose(c)} aria-current={current?.id===c.id?'page':undefined}><MessageSquare size={15}/><span>{c.title}</span></button>)}</nav><div className="sidebar-bottom"><a href={config.docsUrl} target="_blank" rel="noreferrer"><BookOpen size={16}/>Build documentation<ArrowUpRight size={14}/></a><button onClick={()=>{setSettingsTab('Connections');setModal('settings');}}><SettingsIcon size={16}/>Settings</button><div className="account-row"><div className="avatar">{session.owner.name[0]}</div><div><strong>{session.owner.name}</strong><small>{config.development?'Local preview':'Personal workspace'}</small></div><button className="icon-button" aria-label="Sign out" onClick={()=>void api('/auth/logout','POST',{}).then(()=>{setSession(null);setCsrf('');setCurrent(null);setTurns([]);history.replaceState({},'','/login');}).catch(requestError)}><LogOut size={16}/></button></div></div></aside>
  <div className="workspace"><header className="workspace-header"><div className="header-left">{!sidebar&&<button className="icon-button" aria-label="Open navigation" onClick={()=>setSidebar(true)}><PanelLeft size={19}/></button>}<div className="repository-select"><GitBranch size={16}/><select aria-label="Active repository" value={current?.repositoryId??''} onChange={e=>{if(current)void api(`/conversations/${current.id}/repository`,'PATCH',{repositoryId:e.target.value||null}).then(()=>refresh(current.id)).catch(requestError);}} disabled={running}><option value="">No repository selected</option>{settings?.repositories.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><ChevronDown size={13}/></div>{settings?.entireState==='fixture'&&<span className="badge small">Sample</span>}</div><div className="header-right">{settings?.entireState==='connected'&&current?.repositoryId&&<button className="icon-button" aria-label="Explore repository" onClick={()=>setModal('repository')}><Code2 size={18}/></button>}{settings?.body&&<button className="body-status" onClick={()=>{setSettingsTab('Your Marvin');setModal('settings');}}><span className="status-dot muted-dot"/>{settings.body.simulated?'Simulated Marvin':'Marvin offline'}</button>}<button className="icon-button theme-button" aria-label={`Use ${theme==='dark'?'light':'dark'} appearance`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" aria-label="Open settings" onClick={()=>setModal('settings')}><SlidersHorizontal size={18}/></button></div></header>
   <main id="conversation" className="conversation-scroll" tabIndex={0}><div className={`conversation-inner ${turns.length?'has-messages':''}`}>
    {!turns.length?<><div className="welcome"><Face large/><p className="eyebrow">A SPACE TO THINK TOGETHER</p><h1>What’s on your mind?</h1><p>Explore your code. Work through an idea.<br/>Pick up right where you left off.</p></div><div className="suggestions">{[{icon:GitBranch,title:'Understand my work',text:'What changed in the firmware?'},{icon:MessageSquare,title:'Think something through',text:'Help me think through a simple onboarding experience.'},{icon:Wifi,title:'Meet my Marvin',text:'How do I set up my Marvin robot?'}].map(s=><button key={s.title} onClick={()=>{setDraft(s.text);input.current?.focus();}}><s.icon size={19}/><strong>{s.title}</strong><span>{s.text}</span><ArrowUpRight size={15}/></button>)}</div>{settings?.entireState==='disconnected'&&<div className="connect-card"><div className="connection-logo">e<span>↗</span></div><div><strong>Give Marvin a little context.</strong><p>Connect Entire to explore your repositories and the thinking behind your code.</p></div><button className="text-button" onClick={()=>{setSettingsTab('Connections');setModal('settings');}}>Connect Entire<ArrowRight size={15}/></button></div>}{!settings?.body&&<button className="optional-setup" onClick={()=>setSetup('new')}>Have a Marvin robot? <span>Set up your Marvin</span><ArrowUpRight size={14}/></button>}</>:<div className="messages">{turns.map(t=><section key={t.id} className="turn"><div className="user-message"><div className="message-label">YOU</div><p>{t.userText}</p></div><div className="assistant-message"><div className="message-label"><Face/>MARVIN {t.status==='running'&&<span className="stream-state">{toolStatus||'Thinking with you…'}</span>}</div><div className="markdown"><SafeMarkdown text={t.assistantText}/>{t.cards.map((c,i)=><Card key={i} card={c}/>)}{t.status==='running'&&!t.assistantText&&<div className="typing" aria-label="Marvin is thinking"><i/><i/><i/></div>}{t.status==='cancelled'&&<p className="turn-status">Response stopped. You can continue the conversation.</p>}{t.status==='failed'&&<p className="turn-status"><AlertCircle size={14}/> Response interrupted. Your messages are saved.</p>}</div></div></section>)}</div>}
    <div ref={bottom}/></div></main>
   <div className="composer-region">{error&&<div className="inline-error" role="alert"><AlertCircle size={16}/><span>{error}</span><button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}{connection==='offline'&&<div className="reconnecting" role="status"><RotateCcw size={13}/> Reconnecting… Your conversation is saved.</div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><textarea ref={input} aria-label="Message Marvin" placeholder="Ask Marvin anything…" value={draft} maxLength={12000} rows={2} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div className="composer-tools"><span><span className="status-dot"/> {settings?.provider==='fixture'?'Development preview':'Marvin'}<span className="composer-separator">/</span><span className="composer-context">{current?.repositoryId?'Repository context':'Ready to explore'}</span></span><div><button className="icon-button" type="button" aria-label="Talk to Marvin" disabled={!!running} onClick={()=>setModal('voice')}><Mic size={19}/></button>{running?<button className="send-button" type="button" aria-label="Stop response" onClick={()=>void cancel()}><Square size={15} fill="currentColor"/></button>:<button className="send-button" aria-label="Send message" disabled={!draft.trim()||sending}><ArrowUp size={19}/></button>}</div></div></form><p className="composer-note">{settings?.provider==='fixture'?'Responses and repository data are simulated in this preview.':'Marvin can make mistakes. Check important details.'} <span>Shift + Enter for a new line</span></p><div className="sr-only" role="status" aria-live="polite">{running?'Marvin is responding.':'Ready for your message.'}</div></div>
  </div>
  {modal==='settings'&&<Dialog title="Settings" onClose={()=>{setModal(null);setConfirmUnlink(false);}} wide><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{[{name:'Connections',icon:Link2},{name:'Your Marvin',icon:Wifi},{name:'Voice and models',icon:Volume2},{name:'Privacy and history',icon:Shield}].map(t=><button key={t.name} className={settingsTab===t.name?'active':''} onClick={()=>{setSettingsTab(t.name);setConfirmUnlink(false);}}><t.icon size={16}/>{t.name}</button>)}</nav><div className="settings-pane">
   {settingsTab==='Connections'&&<><p className="eyebrow">REPOSITORY CONTEXT</p><h3>A connection to your work.</h3><p className="muted">Entire brings together code, checkpoints, and the context behind your decisions.</p><div className="setting-card"><div className="setting-card-title"><div className="connection-logo">e<span>↗</span></div><div><strong>Entire</strong><small>{settings?.entireState==='connected'?'Connected · read-only':settings?.entireState==='fixture'?'Sample connection active':'Not connected'}</small></div>{settings?.entireState!=='disconnected'&&<Check size={18}/>}</div>{settings?.entireState==='connected'?<><p>Marvin checks your repository access before reading. Change repositories in the conversation header. Wi-Fi and your robot’s account link are unaffected.</p><button className="button secondary full" onClick={()=>void entire('connect')}>Check connection</button><button className="text-button" onClick={()=>void entire('disconnect')}>Disconnect Entire</button></>:<><p>{settings?.entireAvailable?'Your Entire CLI connection is configured on this server. Connect to verify access and choose a repository.':'Configure an Entire CLI login and authorized repositories on the Marvin server to connect. You can keep chatting while the connection is being set up.'}</p>{settings?.entireAvailable&&<button className="button primary full" onClick={()=>void entire('connect')}>Connect Entire</button>}<a className="text-button" href="https://docs.entire.io/cli-reference/login" target="_blank" rel="noreferrer">Entire login documentation <ExternalLink size={13}/></a>{settings?.entireState==='fixture'?<button className="button secondary full" onClick={()=>void entire('disconnect')}>Disconnect sample data</button>:config.development&&<button className="button secondary full" onClick={()=>void entire('fixture')}>Explore a sample repository <ArrowRight size={16}/></button>}</>}{settings?.entireError&&settings.entireState==='connected'&&<p className="notice">{settings.entireError}</p>}</div></>}
   {settingsTab==='Your Marvin'&&<><p className="eyebrow">YOUR PHYSICAL COMPANION</p><h3>{settings?.body?'One Marvin. Yours.':'Bring the conversation to life.'}</h3>{!settings?.body?<><div className="settings-robot"><Face large/></div><p className="muted">Link a Marvin robot whenever you’re ready. Your conversations and repository context will come with you.</p><button className="button primary full" onClick={()=>{setModal(null);setSetup('new');}}>Set up your Marvin <ArrowRight size={16}/></button><p className="fine-print">One robot per account. You can keep using Marvin here without one.</p></>:<><div className="setting-card"><div className="robot-summary"><Face/><div><strong>Marvin</strong><small>{settings.body.simulated?'Simulated robot · preview only':'Offline'}</small></div><span className="badge">Linked</span></div><dl className="device-details"><dt>Network</dt><dd>{settings.body.network}</dd><dt>Device</dt><dd><code>{settings.body.device_id}</code></dd></dl><button className="button secondary full" onClick={()=>{setModal(null);setSetup('change');}}><Wifi size={16}/>Change Wi-Fi<ChevronRight size={15}/></button><p className="fine-print">Moved somewhere new? Change the network while keeping the same Marvin linked.</p></div><div className="ownership-section">{confirmUnlink?<><h4>Unlink this Marvin?</h4><p>The robot loses access to your account. <strong>Your chats and Entire connection stay with you.</strong> Unlinking does not confirm that Wi-Fi settings are erased from an offline robot. Reset it before giving it to someone else.</p><div className="wizard-actions"><button className="button secondary" onClick={()=>setConfirmUnlink(false)}>Keep linked</button><button className="button danger" onClick={()=>void unlink()}>Unlink Marvin</button></div></>:<><h4>Account link</h4><p>Unlink Marvin if you’re replacing it or giving it to someone else.</p><button className="text-button danger-text" onClick={()=>setConfirmUnlink(true)}><Unplug size={15}/>Unlink Marvin</button></>}</div></>}</>}
   {settingsTab==='Voice and models'&&<><p className="eyebrow">ONE VOICE. ONE MARVIN.</p><h3>How Marvin responds.</h3><div className="setting-card"><strong>Text provider</strong><p>{settings?.provider==='fixture'?'Deterministic development preview.':`${settings?.provider==='anthropic'?'Anthropic':'OpenAI'} · configured on the server.`}</p><p className="fine-print">Your server administrator configures the model. Provider credentials stay on the server.</p></div><div className="setting-card"><strong>Realtime voice</strong><p>{config.voiceAvailable?'Voice is ready. Open Talk to Marvin to start your microphone, speak, and return to the same conversation in text.':'Voice is not configured on this server yet. Text conversations remain available.'}</p></div></>}
   {settingsTab==='Privacy and history'&&<PrivacyPanel onError={requestError}/>}
  </div></div></Dialog>}
  {modal==='repository'&&current&&<RepositoryPanel conversationId={current.id} name={settings?.repositories.find(r=>r.id===current.repositoryId)?.name??'Repository'} capabilities={settings?.repositories.find(r=>r.id===current.repositoryId)?.capabilities??[]} onClose={()=>setModal(null)}/>}
  {modal==='voice'&&current&&<VoicePanel conversationId={current.id} available={config.voiceAvailable} onClose={()=>{setModal(null);void refresh(current.id).catch(requestError);}} onRefresh={()=>{void refresh(current.id).catch(requestError);void loadHistory().catch(requestError);}}/>}
  {setup&&config.hardwareProvisioningAvailable?<Suspense fallback={<Dialog title="Set up your Marvin" onClose={()=>setSetup(null)}><p role="status">Opening secure setup…</p></Dialog>}><PhysicalSetup change={setup==='change'} deviceId={settings?.body?.device_id} onClose={()=>{setSetup(null);void loadSettings().catch(requestError);}} onComplete={()=>{void loadSettings().catch(requestError);}}/></Suspense>:setup&&<Setup change={setup==='change'} deviceId={settings?.body?.device_id} development={config.development} onClose={()=>setSetup(null)} onComplete={()=>{void loadSettings().catch(requestError);}}/>}
 </div>;
}
function historyReplace(id:string){history.replaceState({},'','/app/'+id);}
