import { createRoot } from 'react-dom/client';
import '@fontsource/barlow/latin-400.css';
import '@fontsource/barlow/latin-500.css';
import '@fontsource/barlow/latin-600.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import '../../../packages/design-tokens/tokens.css';
import './style.css';
import { App } from './App';
createRoot(document.getElementById('root')!).render(<App/>);
if(import.meta.env.DEV&&new URLSearchParams(location.search).has('audit'))void import('./dev-audit').then(m=>m.installAudit());
