import {useEffect,useRef,useState} from 'react';
import {Bluetooth,Check,Wifi,ArrowRight,RefreshCw,Eye,EyeOff} from 'lucide-react';
import {Dialog} from './Dialog';
import {Face} from './Face';
import {api} from './api';
import {DomainError,type Network} from '../../../packages/contracts/src/index';
import {provisioningSupport,type ProvisioningStage} from '../../../packages/provisioning/src/index';
import {BluetoothSetupSession,chooseBluetoothRobot} from '../../../packages/provisioning/src/bluetooth';
import {PhysicalRobot} from '../../../packages/provisioning/src/physical';
import {decodeSetupCode} from '../../../packages/provisioning/src/setup-code';

type SetupState='ready'|'selecting_device'|'connecting_device'|'reconciling'|'scanning_wifi'|'choosing_wifi'|'authorizing'|'connecting_wifi'|'confirming_account'|'complete';
const progressStates=new Set<SetupState>(['selecting_device','connecting_device','reconciling','authorizing','connecting_wifi','confirming_account']);

export function PhysicalSetup({change,deviceId,onClose,onComplete}:{change:boolean;deviceId?:string;onClose:()=>void;onComplete:()=>void}){
 const [state,setState]=useState<SetupState>('ready'),[code,setCode]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[networks,setNetworks]=useState<Network[]>([]),[selected,setSelected]=useState(''),[hidden,setHidden]=useState(false),[hiddenSsid,setHiddenSsid]=useState('');
 const robot=useRef<PhysicalRobot|null>(null),controller=useRef<AbortController|null>(null),alive=useRef(true),heading=useRef<HTMLHeadingElement>(null);const support=provisioningSupport(),busy=progressStates.has(state)||state==='scanning_wifi';
 const step=state==='ready'||state==='selecting_device'||state==='connecting_device'?0:state==='scanning_wifi'||state==='choosing_wifi'?1:state==='complete'?3:2;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();robot.current?.close();};},[]);useEffect(()=>{if(state!=='ready')heading.current?.focus();},[state]);
 function failed(failure:unknown,fallback='Setup did not finish. Close this window and try again.'){
  if(!alive.current)return;const domain=failure instanceof DomainError?failure:null;
  if(domain?.code==='BLUETOOTH_CANCELLED'){setError('');setState('ready');return;}
  if(domain)console.warn('Marvin setup stopped',{code:domain.code,state});
  setError(failure instanceof Error&&failure.message?failure.message:fallback);
 }
 function provisioningStage(stage:ProvisioningStage){if(!alive.current)return;setState(stage==='reconciling'?'reconciling':stage==='connecting_wifi'?'connecting_wifi':stage==='ready'?'complete':'confirming_account');}
 async function scan(){if(!robot.current)return;setState('scanning_wifi');setError('');setNetworks([]);setSelected('');try{const result=await robot.current.scan();if(alive.current){setNetworks(result.networks);setState('choosing_wifi');}}catch(failure){failed(failure,'Marvin could not scan for Wi-Fi. Close this window and try again.');if(alive.current)setState('choosing_wifi');}}
 async function recoverOrScan(){if(!robot.current)return;controller.current=new AbortController();try{if(await robot.current.reconcile(provisioningStage,controller.current.signal)){await scan();return;}await robot.current.resume(undefined,provisioningStage,controller.current.signal);if(alive.current){setState('complete');setCode('');onComplete();}}catch(failure){if(failure instanceof DomainError&&failure.code==='NO_PENDING_SETUP'){await scan();return;}failed(failure);if(alive.current)setState('ready');}}
 async function find(){setError('');let card;try{card=decodeSetupCode(code);if(change&&card.deviceId!==deviceId)throw new DomainError('DEVICE_MISMATCH','Use the setup card for the Marvin linked to this account.');}catch(failure){failed(failure);return;}robot.current?.close();setState('selecting_device');
  try{const chosen=await chooseBluetoothRobot();if(!alive.current)return;setState('connecting_device');const secure=await BluetoothSetupSession.open(chosen,card.username,card.password,20000,true);if(!alive.current){secure.close();return;}robot.current=new PhysicalRobot(card.deviceId,secure,{ticket:request=>api('/robot/enrollment','POST',request),cancel:async id=>{await api('/robot/enrollment/'+encodeURIComponent(id),'DELETE');},binding:async()=>{const settings=await api<{body:null|{device_id:string;network:string;simulated:number}}>('/settings');return settings.body;},acknowledge:async deviceId=>{await api('/robot/reconciliation/ack','POST',{deviceId});}},change);await recoverOrScan();
  }catch(failure){failed(failure);if(alive.current&&!(failure instanceof DomainError&&failure.code==='BLUETOOTH_CANCELLED'))setState('ready');}
 }
 async function connect(){const chosen=networks.find(item=>item.id===selected);if(!chosen||!robot.current)return;setError('');setState('authorizing');controller.current=new AbortController();try{await robot.current.connect(chosen,password,provisioningStage,controller.current.signal);if(alive.current){setPassword('');setCode('');setState('complete');onComplete();}}catch(failure){failed(failure);if(alive.current)setState('choosing_wifi');}}
 function selectHidden(){if(!robot.current)return;setError('');try{const chosen=robot.current.hiddenNetwork(hiddenSsid);setNetworks(current=>[...current.filter(item=>item.id!==selected),chosen]);setSelected(chosen.id);setPassword('');setHidden(false);}catch(failure){failed(failure);}}
 const network=networks.find(item=>item.id===selected),validPassword=network?.security==='open'||(new TextEncoder().encode(password).length>=8&&new TextEncoder().encode(password).length<=63);
 const close=()=>{controller.current?.abort();robot.current?.close();setPassword('');setCode('');onClose();};
 const progressCopy=state==='selecting_device'?['Choose your Marvin.','Select Marvin in the Bluetooth window. “Paired” only means this browser remembers it.']:state==='connecting_device'?['Connecting securely…','Keep Marvin nearby while the secure connection is established.']:state==='reconciling'?['Preparing Marvin for setup…','Marvin is safely clearing the account link you removed earlier.']:state==='authorizing'?['Authorizing setup…','Marvin is verifying this setup with your account.']:state==='connecting_wifi'?['Connecting to Wi-Fi…','Marvin is joining the network you selected.']:['Confirming your account link…','Marvin is checking its connection with the Marvin service.'];
 return <Dialog title={change?'Change Wi-Fi':'Set up your Marvin'} onClose={close}><div className="setup-content">
  <ol className="stepper" aria-label="Setup progress">{['Find Marvin','Choose Wi-Fi','Connect','Ready'].map((label,index)=><li key={label} className={index<=step?'current':''} aria-current={index===step?'step':undefined}><span>{index<step?<Check size={12}/>:index+1}</span>{label}</li>)}</ol>
  {state==='ready'&&<><div className="setup-art"><Face large/></div><h3>{change?'Connect to your Marvin.':'Bring Marvin a little closer.'}</h3><p className="muted">Keep Marvin powered on and nearby. Bluetooth is used only while setting up its connection.</p><label className="field">Marvin setup code<input type="password" value={code} onChange={event=>setCode(event.target.value)} autoComplete="off" spellCheck={false} maxLength={520}/><small>Current Marvin firmware uses the setup card to protect the encrypted Bluetooth connection.</small></label>{!support.supported&&<p className="notice">{support.reason}</p>}<button className="button primary full" disabled={!code||!support.supported} onClick={()=>void find()}><Bluetooth size={17}/>Connect Marvin</button></>}
  {progressStates.has(state)&&<><div className="setup-art"><Face large thinking/></div><h3 ref={heading} tabIndex={-1}>{progressCopy[0]}</h3><p className="muted setup-status" role="status"><span className="setup-spinner" aria-hidden="true"/>{progressCopy[1]}</p></>}
  {(state==='scanning_wifi'||state==='choosing_wifi')&&<><div className="connected-notice"><Check size={15}/>Marvin connected</div><h3 ref={heading} tabIndex={-1}>Choose a network Marvin can see.</h3><p className="muted">This list comes from Marvin’s own 2.4 GHz Wi-Fi scan.</p><div className="network-heading"><span>AVAILABLE NETWORKS</span><button className="text-button" disabled={busy} onClick={()=>void scan()}><RefreshCw className={state==='scanning_wifi'?'spin':''} size={14}/>{state==='scanning_wifi'?'Scanning…':'Scan again'}</button></div>{state==='scanning_wifi'?<div className="scan-loading" role="status"><span className="setup-spinner" aria-hidden="true"/><strong>Marvin is looking for Wi-Fi networks…</strong><small>This can take several seconds.</small></div>:<><fieldset className="physical-networks"><legend className="sr-only">Wi-Fi network</legend>{networks.map(item=><label className={`network ${selected===item.id?'selected':''}`} key={item.id}><input type="radio" name="physical-network" value={item.id} checked={selected===item.id} disabled={!item.compatible} onChange={()=>{setSelected(item.id);setPassword('');setError('');}}/><Wifi size={19}/><span><strong>{item.ssid||'Unnamed network'}</strong><small>{!item.compatible?'Not supported by this Marvin':item.rssi===-120?'Hidden WPA2 network':item.security==='open'?'Open network':item.rssi>-65?'Good signal':'Weak signal'}</small></span></label>)}</fieldset>{!networks.length&&<p className="notice">Marvin found no networks. Move it closer to your router and scan again.</p>}{hidden?<div className="setting-card"><label className="field">Hidden Wi-Fi name<input value={hiddenSsid} onChange={event=>setHiddenSsid(event.target.value)} autoComplete="off" maxLength={32}/><small>Marvin will try this WPA2-Personal network directly.</small></label><div className="wizard-actions"><button className="button ghost" onClick={()=>{setHidden(false);setHiddenSsid('');}}>Cancel</button><button className="button secondary" disabled={!hiddenSsid} onClick={selectHidden}>Use hidden network</button></div></div>:<button className="text-button hidden-network" onClick={()=>setHidden(true)}>Use a hidden network</button>}{network?.compatible&&network.security!=='open'&&<label className="field">Wi-Fi password<div className="password-input"><input aria-label="Wi-Fi password" type={show?'text':'password'} value={password} onChange={event=>setPassword(event.target.value)} autoComplete="off" maxLength={63}/><button className="icon-button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><small>Sent directly to Marvin over encrypted Bluetooth.</small></label>}<div className="wizard-actions end"><button className="button primary" disabled={!network?.compatible||!validPassword} onClick={()=>void connect()}>Connect Marvin <ArrowRight size={16}/></button></div></>}</>}
  {state==='complete'&&<><div className="success-mark"><Check size={30}/></div><h3 ref={heading} tabIndex={-1}>{change?'Marvin has a new connection.':'You and Marvin, connected.'}</h3><p className="muted">Marvin’s Wi-Fi connection and account link are confirmed.</p><button className="button primary full" onClick={close}>Back to Marvin <ArrowRight size={16}/></button></>}
  {error&&<p className="error-message" role="alert">{error}</p>}
 </div></Dialog>;
}
