import {useEffect,useRef,useState} from 'react';
import {Bluetooth,Check,Wifi,ArrowRight,RefreshCw,Eye,EyeOff} from 'lucide-react';
import {Dialog} from './Dialog';
import {Face} from './Face';
import {api} from './api';
import {DomainError,type Network} from '../../../packages/contracts/src/index';
import {provisioningSupport,type ProvisioningStage} from '../../../packages/provisioning/src/index';
import {BluetoothSetupSession,chooseBluetoothRobot} from '../../../packages/provisioning/src/bluetooth';
import {PhysicalRobot,canResumePhysicalSetup} from '../../../packages/provisioning/src/physical';
import {decodeSetupCode} from '../../../packages/provisioning/src/setup-code';
export function PhysicalSetup({change,deviceId,onClose,onComplete}:{change:boolean;deviceId?:string;onClose:()=>void;onComplete:()=>void}){
 const [step,setStep]=useState(0),[code,setCode]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[networks,setNetworks]=useState<Network[]>([]),[selected,setSelected]=useState(''),[hidden,setHidden]=useState(false),[hiddenSsid,setHiddenSsid]=useState(''),[stage,setStage]=useState<ProvisioningStage>('connecting_wifi'),[resume,setResume]=useState(false);
 const robot=useRef<PhysicalRobot|null>(null),controller=useRef<AbortController|null>(null),alive=useRef(true),heading=useRef<HTMLHeadingElement>(null);const support=provisioningSupport();
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();robot.current?.close();};},[]);useEffect(()=>{if(step)heading.current?.focus();},[step]);
 function failed(e:unknown){if(!alive.current)return;setError(e instanceof Error?e.message:'Setup did not finish. Reconnect and try again.');setResume(canResumePhysicalSetup(e));}
 async function scan(){if(!robot.current)return;setBusy(true);setError('');try{const result=await robot.current.scan();if(alive.current){setNetworks(result.networks);setSelected('');setStep(1);}}catch(e){failed(e);}finally{if(alive.current)setBusy(false);}}
 async function find(resuming=false){setError('');let card;try{card=decodeSetupCode(code);if(change&&card.deviceId!==deviceId)throw new DomainError('DEVICE_MISMATCH','Use the setup card for the Marvin linked to this account.');}catch(e){failed(e);return;}setBusy(true);robot.current?.close();
  try{const chosen=await chooseBluetoothRobot();if(!alive.current)return;const secure=await BluetoothSetupSession.open(chosen,card.username,card.password,20000,true);if(!alive.current){secure.close();return;}robot.current=new PhysicalRobot(card.deviceId,secure,{ticket:request=>api('/robot/enrollment','POST',request),cancel:async id=>{await api('/robot/enrollment/'+encodeURIComponent(id),'DELETE');},binding:async()=>{const settings=await api<{body:null|{device_id:string;network:string;simulated:number}}>('/settings');return settings.body;}},change);
   if(resuming){controller.current=new AbortController();setStep(2);await robot.current.resume(undefined,setStage,controller.current.signal);if(alive.current){setStep(3);setCode('');onComplete();}}else await scan();
  }catch(e){failed(e);if(alive.current)setStep(0);}finally{if(alive.current)setBusy(false);}
 }
 async function connect(){const network=networks.find(n=>n.id===selected);if(!network||!robot.current)return;setBusy(true);setError('');setResume(false);setStep(2);controller.current=new AbortController();const credential=password;setPassword('');
  try{await robot.current.connect(network,credential,s=>{if(alive.current)setStage(s);},controller.current.signal);if(alive.current){setStep(3);setCode('');onComplete();}}
  catch(e){failed(e);if(alive.current)setStep(1);}finally{if(alive.current)setBusy(false);}
 }
 function selectHidden(){if(!robot.current)return;setError('');try{const network=robot.current.hiddenNetwork(hiddenSsid);setNetworks(current=>[...current.filter(n=>n.id!==selected),network]);setSelected(network.id);setPassword('');setHidden(false);}catch(e){failed(e);}}
 const network=networks.find(n=>n.id===selected),validPassword=network?.security==='open'||(new TextEncoder().encode(password).length>=8&&new TextEncoder().encode(password).length<=63);
 const close=()=>{controller.current?.abort();robot.current?.close();setPassword('');setCode('');onClose();};
 return <Dialog title={change?'Change Wi-Fi':'Set up your Marvin'} onClose={close}><div className="setup-content">
  <ol className="stepper" aria-label="Setup progress">{['Find Marvin','Choose Wi-Fi','Connect','Ready'].map((label,i)=><li key={label} className={i<=step?'current':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={12}/>:i+1}</span>{label}</li>)}</ol>
  {step===0&&<><div className="setup-art"><Face large/></div><h3 ref={heading} tabIndex={-1}>{change?'A new network. The same Marvin.':'Bring Marvin a little closer.'}</h3><p className="muted">Restart Marvin and keep it nearby. Setup is available for five minutes after power-on.</p><label className="field">Marvin setup code<input type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" spellCheck={false} maxLength={520}/><small>Use the complete code from your robot’s setup card. It is used only for the secure Bluetooth connection.</small></label>{!support.supported&&<p className="notice">{support.reason}</p>}<button className="button primary full" disabled={busy||!code||!support.supported} onClick={()=>void find()}><Bluetooth size={17}/>{busy?'Connecting securely…':'Find Marvin'}</button><button className="text-button" disabled={busy||!code||!support.supported} onClick={()=>void find(true)}>Resume an earlier setup</button></>}
  {step===1&&<><h3 ref={heading} tabIndex={-1}>Choose a network Marvin can see.</h3><p className="muted">This list comes from Marvin’s own 2.4 GHz Wi-Fi scan.</p><div className="network-heading"><span>AVAILABLE NETWORKS</span><button className="text-button" disabled={busy||resume} onClick={()=>void scan()}><RefreshCw size={14}/>Scan again</button></div><fieldset className="physical-networks"><legend className="sr-only">Wi-Fi network</legend>{networks.map(n=><label className={`network ${selected===n.id?'selected':''}`} key={n.id}><input type="radio" name="physical-network" value={n.id} checked={selected===n.id} disabled={busy||!n.compatible||resume} onChange={()=>{setSelected(n.id);setPassword('');setError('');}}/><Wifi size={19}/><span><strong>{n.ssid||'Unnamed network'}</strong><small>{!n.compatible?'Not supported by this Marvin':n.rssi===-120?'Hidden WPA2 network':n.security==='open'?'Open network':n.rssi>-65?'Good signal':'Weak signal'}</small></span></label>)}</fieldset>{!networks.length&&<p className="notice">Marvin found no networks. Move it closer to your router and scan again.</p>}{hidden?<div className="setting-card"><label className="field">Hidden Wi-Fi name<input value={hiddenSsid} onChange={e=>setHiddenSsid(e.target.value)} autoComplete="off" maxLength={32}/><small>Hidden networks cannot be verified by the scan. Marvin will try WPA2-Personal directly.</small></label><div className="wizard-actions"><button className="button ghost" onClick={()=>{setHidden(false);setHiddenSsid('');}}>Cancel</button><button className="button secondary" disabled={!hiddenSsid} onClick={selectHidden}>Use hidden network</button></div></div>:<button className="text-button" disabled={busy||resume} onClick={()=>setHidden(true)}>Use a hidden network</button>}{network?.compatible&&network.security!=='open'&&!resume&&<label className="field">Wi-Fi password<div className="password-input"><input aria-label="Wi-Fi password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off" maxLength={63}/><button className="icon-button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><small>Sent directly to Marvin over encrypted Bluetooth.</small></label>}<div className="wizard-actions"><button className="button ghost" disabled={busy} onClick={()=>{robot.current?.close();setStep(0);setPassword('');}}>Reconnect</button>{resume?<button className="button primary" disabled={busy} onClick={()=>void find(true)}>Resume setup</button>:<button className="button primary" disabled={busy||!network?.compatible||!validPassword} onClick={()=>void connect()}>Connect Marvin <ArrowRight size={16}/></button>}</div></>}
  {step===2&&<><div className="setup-art"><Face large thinking/></div><h3 ref={heading} tabIndex={-1}>{stage==='connecting_wifi'?'Connecting to Wi-Fi.':'Confirming your account link.'}</h3><p className="muted" role="status">Keep Marvin powered on and nearby. Closing this window won’t cancel work already running on the robot; you can resume setup afterward.</p></>}
  {step===3&&<><div className="success-mark"><Check size={30}/></div><h3 ref={heading} tabIndex={-1}>{change?'Marvin has a new connection.':'You and Marvin, connected.'}</h3><p className="muted">Marvin’s Wi-Fi connection and account link are confirmed. Your conversations and Entire connection stay with you.</p><button className="button primary full" onClick={close}>Back to Marvin <ArrowRight size={16}/></button></>}
  {error&&<p className="error-message" role="alert">{error}</p>}
 </div></Dialog>;
}
