import {useEffect,useState} from 'react';
import {Download,Shield} from 'lucide-react';
import {api} from './api';
export function PrivacyPanel({onError}:{onError:(error:unknown)=>void}){
 const [days,setDays]=useState<string>(''),[confirm,setConfirm]=useState(false),[phrase,setPhrase]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{void api<{retention_days:number|null}>('/account/privacy').then(p=>setDays(p.retention_days===null?'forever':String(p.retention_days))).catch(onError);},[onError]);
 async function retention(value:string){setBusy(true);setSaved(false);try{await api('/account/privacy','PATCH',{retentionDays:value==='forever'?null:Number(value)});setDays(value);setSaved(true);}catch(e){onError(e);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await api('/account','DELETE',{confirmation:phrase});location.assign('/login');}catch(e){onError(e);setBusy(false);}}
 return <><p className="eyebrow">YOUR SPACE, YOUR CONTEXT</p><h3>Your conversations, your choice.</h3><div className="setting-card"><Shield size={22}/><h4>What Marvin keeps</h4><p>Your server saves messages and voice transcripts for continuity. Raw audio is not stored by Marvin. During a voice session, audio is sent to the configured provider.</p><a className="button secondary" href="/api/account/export/download" download><Download size={16}/>Download conversations</a><p className="fine-print">Includes your messages and replies in a portable data file. Credentials and Wi-Fi settings are excluded.</p></div><div className="setting-card"><label className="field">Keep conversation history<select value={days} disabled={busy||!days} onChange={e=>void retention(e.target.value)}><option value="" disabled>Loading…</option><option value="forever">Until I delete my account</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">One year</option></select></label><p className="fine-print">Older messages and their saved summaries are removed during regular maintenance. Server backups and provider records follow their own retention policies.</p>{saved&&<p role="status">Retention preference saved.</p>}</div><div className="ownership-section"><h4>Delete your Marvin account</h4>{confirm?<><p>This permanently deletes your saved conversations and disconnects your Desktop Pet from this account. It does not erase an offline Desktop Pet or delete your Entire or GitHub account.</p><label className="field">Type DELETE MY ACCOUNT to confirm<input value={phrase} onChange={e=>setPhrase(e.target.value)} autoComplete="off"/></label><div className="wizard-actions"><button className="button secondary" disabled={busy} onClick={()=>{setConfirm(false);setPhrase('');}}>Keep my account</button><button className="button danger" disabled={busy||phrase!=='DELETE MY ACCOUNT'} onClick={()=>void remove()}>{busy?'Deleting…':'Delete account'}</button></div></>:<><p>Download your conversations first if you want to keep a copy.</p><button className="text-button danger-text" onClick={()=>setConfirm(true)}>Delete my account</button></>}</div></>;
}
