import { useState } from 'react';
import type { RepoCard } from '../../../packages/contracts/src/index';
import { api } from './api';
import { Dialog } from './Dialog';
import { RepositoryCard } from './RepositoryCard';
export function RepositoryPanel({conversationId,name,capabilities,onClose}:{conversationId:string;name:string;capabilities:string[];onClose:()=>void}){
 const [query,setQuery]=useState(''),[mode,setMode]=useState('code'),[card,setCard]=useState<RepoCard|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[path,setPath]=useState(''),[start,setStart]=useState(1),[record,setRecord]=useState('');
 async function read(tool:string,args:Record<string,unknown>={}){setBusy(true);setError('');setCard(null);try{setCard(await api<RepoCard>(`/conversations/${conversationId}/repository/read`,'POST',{tool,args}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog title="Explore repository" onClose={onClose}><div className="repository-panel"><p className="eyebrow">{name}</p><p className="muted">Read the evidence behind Marvin’s answers. Your repository is read-only.</p><form onSubmit={e=>{e.preventDefault();void read(mode==='graph'?'repository_graph':'repository_search',mode==='graph'?{query}:{query,mode,page:1});}}><label className="field">Search repository<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={300} required placeholder="A function, phrase, or past decision"/></label><div className="wizard-actions"><label className="field">Search in<select value={mode} onChange={e=>setMode(e.target.value)}><option value="code">Code · exact text</option><option value="history">History · meaning</option>{capabilities.includes('graph')&&<option value="graph">Code relationships</option>}</select></label><button className="button primary" disabled={busy||!query.trim()}>Search</button></div></form><div className="repository-actions"><button className="button secondary" disabled={busy} onClick={()=>void read('repository_summary')}>Repository overview</button>{capabilities.includes('history')&&<button className="button secondary" disabled={busy} onClick={()=>void read('repository_history')}>Recent checkpoints</button>}</div>{capabilities.includes('source')&&<details className="source-reader"><summary>Read a file or checkpoint</summary><form onSubmit={e=>{e.preventDefault();void read('repository_source',{path,start,end:start+79});}}><label className="field">Committed file path<input value={path} onChange={e=>setPath(e.target.value)} placeholder="src/main.ts" required/></label><label className="field">Starting line<input type="number" min={1} max={99920} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><button className="button secondary" disabled={busy}>Read 80 lines</button></form><label className="field">Checkpoint or session ID<input value={record} onChange={e=>setRecord(e.target.value)} maxLength={128}/></label><div className="repository-actions"><button className="button secondary" disabled={busy||!record} onClick={()=>void read('repository_checkpoint',{id:record})}>Read checkpoint</button><button className="button secondary" disabled={busy||!record} onClick={()=>void read('repository_session',{id:record})}>Read session</button></div></details>}{busy&&<p role="status">Reading from your repository…</p>}{error&&<p className="error-message" role="alert">{error}</p>}{card&&<><RepositoryCard card={card}/>{card.nextPage&&<button className="button secondary" disabled={busy} onClick={()=>void read('repository_search',{query,mode:'history',page:card.nextPage})}>Next page</button>}</>}</div></Dialog>;
}
