import { useEffect,useRef,useState } from 'react';
import { Bluetooth,Check,ChevronLeft,Eye,EyeOff,LockKeyhole,RefreshCw,Wifi,ArrowRight,TriangleAlert } from 'lucide-react';
import { Dialog } from './Dialog';
import { api } from './api';
import { Face } from './Face';
import { SimulatedRobot,discoverPhysicalRobot,provisioningSupport,type ProvisioningStage } from '../../../packages/provisioning/src/index';
import type { Network } from '../../../packages/contracts/src/index';
export function Setup({onClose,onComplete,change=false,deviceId,development}:{onClose:()=>void;onComplete:()=>void;change?:boolean;deviceId?:string;development:boolean}){
 const [step,setStep]=useState(0),[simulation,setSimulation]=useState(false),[networks,setNetworks]=useState<Network[]>([]),[selected,setSelected]=useState<Network|null>(null),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[stage,setStage]=useState<ProvisioningStage>('connecting_wifi'),[hidden,setHidden]=useState(false),[ssid,setSsid]=useState('');
 const robot=useRef(new SimulatedRobot()),controller=useRef<AbortController|null>(null),enrollment=useRef(crypto.randomUUID());
 const support=provisioningSupport();
 useEffect(()=>()=>{controller.current?.abort();},[]);
 async function scan(){setBusy(true);setError('');try{const result=await robot.current.scan();setNetworks(result.networks);setStep(1);setSelected(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function findReal(){setBusy(true);setError('');try{await discoverPhysicalRobot();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function connect(){
  const network=hidden?{id:'hidden',ssid:ssid.trim(),rssi:-60,channel:1,security:'wpa2-personal',compatible:true} as Network:selected;
  if(!network||!network.ssid)return;setBusy(true);setError('');setStep(2);controller.current=new AbortController();
  try{
   await robot.current.connect(network,password,setStage,controller.current.signal);setPassword('');
   if(change)await api('/simulation/network','POST',{deviceId:deviceId??robot.current.deviceId,network:network.ssid});
   else await api('/simulation/robot','POST',{deviceId:robot.current.deviceId,enrollmentId:enrollment.current,network:network.ssid});
   setStep(3);onComplete();
  }catch(e){if((e as Error).name!=='AbortError'){setError((e as Error).message);setStep(1);}}finally{setBusy(false);}
 }
 return <Dialog title={change?'Change Wi-Fi':'Set up your Marvin'} onClose={()=>{controller.current?.abort();setPassword('');onClose();}}>
  <div className="setup-content">
   <ol className="stepper" aria-label="Setup progress">{['Find Marvin','Choose Wi-Fi','Connect','Ready'].map((s,i)=><li key={s} className={i<=step?'current':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={12}/>:i+1}</span>{s}</li>)}</ol>
   {simulation&&<div className="notice compact"><span className="status-dot"/> Simulated robot · no hardware settings will change</div>}
   {step===0&&<><div className="setup-art"><Face large/></div><h3>{change?'A new network. The same Marvin.':'Bring Marvin a little closer.'}</h3><p className="muted">{change?'Your robot stays linked to your account. Keep it nearby while you change its Wi-Fi.':'Power on your robot and enable setup mode. Bluetooth is only needed for setup and network changes.'}</p><div className="instructions"><Bluetooth size={20}/><div><strong>Connect over Bluetooth</strong><p>Use a supported browser and select your Marvin in the device chooser. The ESP32-S3-WROOM setup gesture is awaiting board validation.</p></div></div>{!support.supported&&<div className="notice"><TriangleAlert size={18}/><span>{support.reason}</span></div>}<button className="button primary full" disabled={busy||!support.supported} onClick={()=>void findReal()}><Bluetooth size={17}/>{busy?'Finding Marvin…':'Find Marvin'}</button>{development&&<div className="simulation-option"><p>Explore the setup experience without hardware.</p><button className="button secondary full" onClick={()=>{setSimulation(true);void scan();}}>Try a simulated Marvin <ArrowRight size={16}/></button></div>}</>}
   {step===1&&<><h3>Choose a network Marvin can see.</h3><p className="muted">{simulation?'These sample networks are reported by the simulated robot.':'These networks were scanned by Marvin, not your computer.'} Marvin supports 2.4 GHz Wi-Fi.</p><div className="network-heading"><span>AVAILABLE NETWORKS</span><button className="text-button" disabled={busy} onClick={()=>void scan()}><RefreshCw size={13}/> Scan again</button></div><div className="network-list" role="radiogroup" aria-label="Wi-Fi network">{networks.map(n=><button key={n.id} role="radio" aria-checked={!hidden&&selected?.id===n.id} tabIndex={selected?selected.id===n.id?0:-1:networks[0]?.id===n.id?0:-1} onKeyDown={e=>{if(["ArrowDown","ArrowRight","ArrowUp","ArrowLeft"].includes(e.key)){e.preventDefault();const offset=e.key==="ArrowDown"||e.key==="ArrowRight"?1:-1;const next=(networks.findIndex(item=>item.id===n.id)+offset+networks.length)%networks.length;setSelected(networks[next]);setHidden(false);(e.currentTarget.parentElement?.children[next] as HTMLElement)?.focus();}}} className={`network ${!hidden&&selected?.id===n.id?'selected':''}`} onClick={()=>{setSelected(n);setHidden(false);setError('');}}><Wifi size={20}/><span><strong>{n.ssid}</strong><small>2.4 GHz · {n.rssi>-60?'Strong signal':n.rssi>-70?'Good signal':'Weak signal'}</small></span><LockKeyhole size={14}/><span className="radio-mark">{!hidden&&selected?.id===n.id&&<span/>}</span></button>)}</div><button className="text-button hidden-network" onClick={()=>{setHidden(!hidden);setSelected(null);}}>My network is hidden</button>{hidden&&<label className="field">Network name<input value={ssid} onChange={e=>setSsid(e.target.value)} maxLength={32} autoComplete="off"/></label>}{(selected||hidden)&&<label className="field">Wi-Fi password<div className="password-input"><input aria-label="Wi-Fi password" autoFocus type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off" maxLength={63}/><button className="icon-button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><small>{simulation?'Use any 8–63 characters. “wrong-password” tests a failed connection.':'Your password is sent directly to Marvin.'}</small></label>}<div className="wizard-actions"><button className="button ghost" onClick={()=>{setStep(0);setPassword('');}}><ChevronLeft size={16}/>Back</button><button className="button primary" onClick={()=>void connect()} disabled={busy||(!selected&&!hidden)||password.length<8||(hidden&&!ssid.trim())}>Connect Marvin <ArrowRight size={16}/></button></div></>}
   {step===2&&<><div className="setup-art"><Face large thinking/></div><h3>Making the connection.</h3><p className="muted">Keep this window open and Marvin nearby.</p><div className="connection-stages"><p><span className={stage!=='connecting_wifi'?'done':'pulse'}>{stage!=='connecting_wifi'?<Check size={14}/>:<Wifi size={14}/>}</span>Connecting to Wi-Fi</p><p><span className={stage==='ready'?'done':stage==='checking_server'?'pulse':''}>{stage==='ready'?<Check size={14}/>:2}</span>Checking Marvin’s server</p><p><span className={stage==='ready'?'done':''}>{stage==='ready'?<Check size={14}/>:3}</span>{change?'Keeping your account linked':'Linking to your account'}</p></div></>}
   {step===3&&<><div className="success-mark"><Check size={30}/></div><h3>{change?'Marvin has a new connection.':'You and Marvin, connected.'}</h3><p className="muted">{simulation?'The simulated setup is complete. Your conversation and Entire connection stay exactly where they were.':'Marvin is linked and ready. You can close Bluetooth and continue your conversation.'}</p><button className="button primary full" onClick={onClose}>Back to Marvin <ArrowRight size={16}/></button></>}
   {error&&<p className="error-message" role="alert">{error}</p>}
  </div>
 </Dialog>;
}
