import {createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID} from 'node:crypto';
import {execFile,spawn,type ChildProcess} from 'node:child_process';
import {mkdir,mkdtemp,readFile,rename,rm,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {z} from 'zod';
import {DomainError,RepoCard,type Evidence,type Repository} from '../../contracts/src/index.js';
import type {Store} from '../../persistence/src/store.js';
import {repositoryArguments,validateRepositoryArguments} from './policy.js';
import {SourcePath} from './entire-cli.js';
import type {RepositoryIntegration} from './repository-integration.js';

type CredentialBundle={tokens:string;contexts:string};
type Envelope={v:1;iv:string;tag:string;data:string};
const SecretRef=z.string().regex(/^entire_[a-f0-9]{32}$/);
const safeText=(value:string,max=3000)=>value.replace(/-----BEGIN [^-]*PRIVATE KEY-----[\s\S]*?-----END [^-]*PRIVATE KEY-----/g,'[private key redacted]').replace(/\b(?:eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{8,}|gh[pousr]_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9_-]{16,})\b/g,'[credential redacted]').slice(0,max);

export class EntireSecretStore{
 private key:Buffer;
 constructor(readonly directory:string,keyBase64:string){this.key=Buffer.from(keyBase64,'base64');if(this.key.length!==32)throw new Error('Entire secret key must be 32 bytes.');}
 private path(ref:string){return join(this.directory,SecretRef.parse(ref)+'.enc');}
 ref(ownerId:string){return 'entire_'+createHash('sha256').update(ownerId).digest('hex').slice(0,32);}
 async put(ownerId:string,value:CredentialBundle){await mkdir(this.directory,{recursive:true,mode:0o700});const ref=this.ref(ownerId),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key,iv),data=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]),envelope:Envelope={v:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:data.toString('base64')},target=this.path(ref),temp=target+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(envelope),{mode:0o600});await rename(temp,target);return ref;}
 async get(ref:string):Promise<CredentialBundle>{let envelope:Envelope;try{envelope=z.object({v:z.literal(1),iv:z.string(),tag:z.string(),data:z.string()}).parse(JSON.parse(await readFile(this.path(ref),'utf8')));}catch{throw new DomainError('ENTIRE_REAUTH_REQUIRED','Reconnect Entire to continue.',409);}try{const decipher=createDecipheriv('aes-256-gcm',this.key,Buffer.from(envelope.iv,'base64'));decipher.setAuthTag(Buffer.from(envelope.tag,'base64'));return z.object({tokens:z.string().max(131072),contexts:z.string().max(131072)}).parse(JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.data,'base64')),decipher.final()]).toString('utf8')));}catch{throw new DomainError('ENTIRE_REAUTH_REQUIRED','Reconnect Entire to continue.',409);}}
 async delete(ref:string|undefined|null){if(ref)await rm(this.path(ref),{force:true});}
}

type LoginAttempt={id:string;ownerId:string;status:'starting'|'waiting'|'connected'|'failed'|'cancelled';verificationUri?:string;userCode?:string;expiresAt:number;error?:string;process:ChildProcess;directory:string};
export type EntireLoginStatus=Omit<LoginAttempt,'process'|'directory'|'ownerId'>;
type HostedRepo={id:string;name:string;qualified:string;description:string;capabilities:string[]};
const Page=z.object({items:z.array(z.object({repo:z.string().min(1).max(300),status:z.string().max(80),placements:z.array(z.object({status:z.string().max(80)}).passthrough()).optional()}).passthrough()).max(500),nextPageToken:z.string().max(4096).optional()});
const json=(raw:string)=>{try{return JSON.parse(raw) as unknown;}catch{throw new DomainError('ENTIRE_BAD_RESPONSE','Entire returned unreadable data.',502);}};
const repoId=(qualified:string)=>'entire_'+createHash('sha256').update(qualified).digest('hex').slice(0,24);
const qualified=(raw:string)=>raw.replace(/^\//,'');
const display=(raw:string)=>raw.replace(/^\/(?:gh|et)\//,'').replace(/^(?:gh|et)\//,'');
class KeyedSerial{
 private tails=new Map<string,Promise<void>>();
 async run<T>(key:string,fn:()=>Promise<T>){const previous=this.tails.get(key)??Promise.resolve();let release!:()=>void;const next=new Promise<void>(resolve=>release=resolve);this.tails.set(key,next);await previous;try{return await fn();}finally{release();if(this.tails.get(key)===next)this.tails.delete(key);}}
}

export class EntireHostedCli implements RepositoryIntegration{
 readonly deployment='hosted' as const;
 private attempts=new Map<string,LoginAttempt>();
 private serial=new KeyedSerial();
 private cached=new Map<string,HostedRepo[]>();
 constructor(readonly executable:string,readonly secrets:EntireSecretStore,readonly store:Store){}
 private baseEnv(directory:string,tokenPath=join(directory,'tokens.json')):NodeJS.ProcessEnv{return {PATH:process.env.PATH,HOME:join(directory,'home'),TMPDIR:join(directory,'tmp'),LANG:'en_US.UTF-8',ENTIRE_CONFIG_DIR:join(directory,'config'),XDG_CACHE_HOME:join(directory,'cache'),ENTIRE_TOKEN_STORE:'file',ENTIRE_TOKEN_STORE_PATH:tokenPath,ENTIRE_TELEMETRY_OPTOUT:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_PAGER:'cat',PAGER:'cat',NO_COLOR:'1'};}
 private async prepare(directory:string,bundle?:CredentialBundle){for(const path of ['home','tmp','config','cache'])await mkdir(join(directory,path),{recursive:true,mode:0o700});if(bundle){await writeFile(join(directory,'tokens.json'),bundle.tokens,{mode:0o600});await writeFile(join(directory,'config','contexts.json'),bundle.contexts,{mode:0o600});}}
 private async capture(directory:string):Promise<CredentialBundle>{return {tokens:await readFile(join(directory,'tokens.json'),'utf8'),contexts:await readFile(join(directory,'config','contexts.json'),'utf8')};}
 private publicAttempt(a:LoginAttempt):EntireLoginStatus{return {id:a.id,status:a.status,verificationUri:a.verificationUri,userCode:a.userCode,expiresAt:a.expiresAt,error:a.error};}
 async startLogin(ownerId:string):Promise<EntireLoginStatus>{for(const attempt of this.attempts.values())if(attempt.ownerId===ownerId&&['starting','waiting'].includes(attempt.status)){attempt.process.kill('SIGTERM');attempt.status='cancelled';}
  const directory=await mkdtemp(join(tmpdir(),'marvin-entire-login-'));await this.prepare(directory);const child=spawn(this.executable,['login','--device'],{env:this.baseEnv(directory),stdio:['ignore','pipe','pipe']});const attempt:LoginAttempt={id:randomUUID(),ownerId,status:'starting',expiresAt:Date.now()+10*60*1000,process:child,directory};this.attempts.set(attempt.id,attempt);
  let stdout='',stderr='';const parse=()=>{const code=/^Device code:\s*([A-Z0-9-]{4,32})\s*$/m.exec(stdout)?.[1],url=/^\s*(https:\/\/\S+)\s*$/m.exec(stdout)?.[1];if(code&&url){const parsed=new URL(url);if(parsed.protocol!=='https:'||!(parsed.hostname==='entire.io'||parsed.hostname.endsWith('.entire.io'))){child.kill('SIGTERM');attempt.status='failed';attempt.error='Entire returned an unexpected login address.';return;}attempt.userCode=code;attempt.verificationUri=parsed.toString();attempt.status='waiting';}};
  child.stdout.on('data',chunk=>{stdout=(stdout+chunk.toString()).slice(-16384);parse();});child.stderr.on('data',chunk=>{stderr=(stderr+chunk.toString()).slice(-16384);});child.on('error',()=>{attempt.status='failed';attempt.error='The Entire CLI could not start.';void rm(directory,{recursive:true,force:true});});child.on('close',code=>{void(async()=>{if(attempt.status==='cancelled')return;if(code!==0){attempt.status='failed';attempt.error=/expired|denied|cancel/i.test(stderr+stdout)?'Entire authorization expired or was cancelled.':'Entire sign-in could not be completed.';await rm(directory,{recursive:true,force:true});return;}try{const ref=await this.secrets.put(ownerId,await this.capture(directory)),version=await this.cliVersion();await this.store.setEntireConnection(ownerId,{authKind:'hosted_cli',status:'connected',secretRef:ref,cliVersion:version});attempt.status='connected';}catch{attempt.status='failed';attempt.error='Entire sign-in completed, but Marvin could not save the connection.';}finally{await rm(directory,{recursive:true,force:true});}})();});
  const deadline=Date.now()+10000;while(attempt.status==='starting'&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,25));if(attempt.status==='starting'){child.kill('SIGTERM');attempt.status='failed';attempt.error='Entire did not return login instructions.';}return this.publicAttempt(attempt);
 }
 loginStatus(ownerId:string,id:string){const a=this.attempts.get(id);if(!a||a.ownerId!==ownerId)throw new DomainError('ENTIRE_LOGIN_NOT_FOUND','That Entire sign-in attempt is unavailable.',404);return this.publicAttempt(a);}
 cancelLogin(ownerId:string,id:string){const a=this.attempts.get(id);if(!a||a.ownerId!==ownerId)return false;if(['starting','waiting'].includes(a.status)){a.status='cancelled';a.process.kill('SIGTERM');void rm(a.directory,{recursive:true,force:true});}return true;}
 private async cliVersion(){return new Promise<string>(resolve=>execFile(this.executable,['version'],{timeout:5000,maxBuffer:16384,encoding:'utf8'},(_e,out)=>resolve(/^Entire CLI\s+([^\s]+)/m.exec(out)?.[1]??'unknown')));}
 private command(ownerId:string,args:string[],signal?:AbortSignal){return this.serial.run(ownerId,async()=>{const connection=await this.store.entireConnection(ownerId);if(!connection||connection.authKind!=='hosted_cli'||connection.status!=='connected'||!connection.secretRef)throw new DomainError('ENTIRE_NOT_CONFIGURED','Connect Entire first.',409);const directory=await mkdtemp(join(tmpdir(),'marvin-entire-run-'));try{await this.prepare(directory,await this.secrets.get(connection.secretRef));const output=await new Promise<string>((resolve,reject)=>execFile(this.executable,args,{env:this.baseEnv(directory),timeout:20000,maxBuffer:524288,encoding:'utf8',signal},(error,stdout,stderr)=>{if(!error){resolve(stdout);return;}const diagnostic=String(stderr);if(/not logged in|login required|401|token.*expir/i.test(diagnostic))reject(new DomainError('ENTIRE_REAUTH_REQUIRED','Reconnect Entire to continue.',409));else if(/403|forbidden|not authorized|404|not found/i.test(diagnostic))reject(new DomainError('REPOSITORY_FORBIDDEN','This repository is unavailable.',403));else if(/429|rate.limit/i.test(diagnostic))reject(new DomainError('ENTIRE_RATE_LIMITED','Entire is limiting requests. Try again shortly.',429));else reject(new DomainError('ENTIRE_UNAVAILABLE','Entire could not complete this read.',502));}));await this.secrets.put(ownerId,await this.capture(directory));await this.store.verifyEntireConnection(ownerId);return output;}catch(error){if(error instanceof DomainError&&error.code==='ENTIRE_REAUTH_REQUIRED'){await this.store.setEntireConnection(ownerId,{authKind:'hosted_cli',status:'reauth_required',secretRef:connection.secretRef,cliVersion:connection.cliVersion});await this.store.setEntireState(ownerId,'disconnected');}throw error;}finally{await rm(directory,{recursive:true,force:true});}});}
 private repository(row:z.infer<typeof Page>['items'][number]):HostedRepo{const q=qualified(row.repo),native=q.startsWith('et/');return {id:repoId(q),name:display(q),qualified:q,description:`Entire cloud repository · ${row.status}`,capabilities:['summary','search','code_search',...(!native?['checkpoint']:[])]};}
 private async page(ownerId:string,cursor?:string){const args=['repo','mirror','list','--mirrored','--forge','all','--json','--page-size','100'];if(cursor!==undefined)args.push('--page-token',z.string().max(4096).parse(cursor));return Page.parse(json(await this.command(ownerId,args)));}
 async configured(ownerId:string):Promise<Repository[]>{const cached=this.cached.get(ownerId);if(cached)return cached;const repos:HostedRepo[]=[];let cursor:string|undefined;for(let page=0;page<10;page++){const value=await this.page(ownerId,cursor);repos.push(...value.items.map(row=>this.repository(row)));if(!value.nextPageToken)break;cursor=value.nextPageToken;}repos.sort((a,b)=>a.name.localeCompare(b.name));this.cached.set(ownerId,repos);return repos;}
 async connect(ownerId:string){this.invalidate(ownerId);const repos=await this.configured(ownerId);if(!repos.length)throw new DomainError('ENTIRE_NOT_CONFIGURED','No mirrored Entire repositories are available.',409);await this.check(ownerId,repos[0]!.id);return repos;}
 async check(ownerId:string,id:string){this.invalidate(ownerId);const repo=(await this.configured(ownerId)).find(repo=>repo.id===id) as HostedRepo|undefined;if(!repo)throw new DomainError('REPOSITORY_FORBIDDEN','This repository is unavailable.',403);return repo;}
 async discover(ownerId:string,cursor?:string){const value=await this.page(ownerId,cursor);return {items:value.items.map(row=>this.repository(row)),nextCursor:value.nextPageToken??null};}
 private card(repo:HostedRepo,title:string,summary:string,evidence:Evidence[]=[],extra:Partial<RepoCard>={}):RepoCard{return RepoCard.parse({kind:'repository',repositoryId:repo.id,source:'entire',title,summary:safeText(summary),revision:'Entire cloud index; commit revision unavailable',files:[],fetchedAt:Date.now(),evidence,...extra});}
 async read(ownerId:string,id:string,tool:string,args:Record<string,unknown>,signal?:AbortSignal){if(!(tool in repositoryArguments))throw new DomainError('TOOL_FORBIDDEN','Unknown repository operation.',403);validateRepositoryArguments(tool as keyof typeof repositoryArguments,args);const repo=await this.check(ownerId,id) as HostedRepo,expected=display(repo.qualified);
  if(tool==='repository_summary')return this.card(repo,repo.name,'Entire access is verified. Search the cloud index for code and development history; indexed results may not identify an exact commit.',[],{capabilities:repo.capabilities});
  if(tool==='repository_search'){const query=String(args.query),page=Number(args.page),mode=String(args.mode),command=['search',query,'--repo',repo.qualified,'--limit','10'];if(mode==='code')command.push('--code','--json');else command.push('--page',String(page),'--compact');const value=json(await this.command(ownerId,command,signal));
   if(mode==='code'){const parsed=z.object({results:z.array(z.object({repo:z.string(),path:z.string(),line:z.number().int().min(1),context_line:z.string()}).passthrough()).max(1000),failed_jurisdictions:z.array(z.string()).optional(),skipped_repos:z.array(z.unknown()).optional()}).passthrough().parse(value);if(parsed.results.some(result=>display(result.repo)!==expected))throw new DomainError('ENTIRE_SCOPE_MISMATCH','Entire returned results from another repository.',502);const evidence=parsed.results.filter(r=>SourcePath.safeParse(r.path).success).slice(0,10).map((r,index)=>({id:`code-${index+1}`,label:r.path,path:r.path,lineStart:r.line,lineEnd:r.line,excerpt:safeText(r.context_line,1600),origin:'entire' as const}));return this.card(repo,'Code search',evidence.length?'Indexed exact-text matches. Verify current source before relying on them.':'No indexed code matches were returned.',evidence,{partial:!!(parsed.failed_jurisdictions?.length||parsed.skipped_repos?.length)});}
   const parsed=z.object({results:z.array(z.object({id:z.string(),type:z.string(),repo:z.string(),title:z.string(),snippet:z.string().optional(),date:z.string().optional()}).passthrough()).max(100),total_pages:z.number().optional(),page:z.number().optional(),partial:z.boolean().optional(),truncated:z.boolean().optional(),coverage_incomplete:z.boolean().optional()}).passthrough().parse(value);if(parsed.results.some(result=>display(result.repo)!==expected))throw new DomainError('ENTIRE_SCOPE_MISMATCH','Entire returned history from another repository.',502);return this.card(repo,'Repository history search','Indexed development-history excerpts. Open a checkpoint before drawing conclusions.',parsed.results.slice(0,10).map(r=>({id:r.id.slice(0,128),label:safeText(r.title,200),excerpt:safeText(r.snippet??r.title,1600),origin:'entire' as const,kind:r.type.slice(0,40),date:r.date?.slice(0,80)})),{nextPage:parsed.total_pages&&page<parsed.total_pages?page+1:null,partial:!!(parsed.partial||parsed.truncated||parsed.coverage_incomplete)});}
  if(tool==='repository_checkpoint'){if(!repo.capabilities.includes('checkpoint'))throw new DomainError('ENTIRE_CAPABILITY_UNAVAILABLE','Cloud checkpoint detail is unavailable for this repository type.',409);const target=String(args.id),value=z.object({checkpoint_id:z.string(),branch:z.string().optional(),files_touched:z.array(z.string()).optional(),sessions:z.array(z.unknown()).optional(),token_usage:z.record(z.string(),z.number()).optional()}).passthrough().parse(json(await this.command(ownerId,['checkpoint','explain',target,'--repo',expected,'--json','--no-pager'],signal)));if(value.checkpoint_id!==target)throw new DomainError('ENTIRE_SCOPE_MISMATCH','Entire returned a different checkpoint.',502);const evidence=(value.files_touched??[]).slice(0,10).map((path,index)=>({id:`file-${index+1}`,label:path,path,origin:'entire' as const,kind:'file'}));return this.card(repo,'Checkpoint '+target,`Stored checkpoint metadata${value.branch?` on ${value.branch}`:''}. Full transcripts are not retrieved.`,evidence,{partial:(value.files_touched?.length??0)>10});}
  throw new DomainError('ENTIRE_CAPABILITY_UNAVAILABLE','This operation requires an authorized source checkout or local connector.',409);
 }
 invalidate(ownerId:string){this.cached.delete(ownerId);}
 async disconnect(ownerId:string){const connection=await this.store.entireConnection(ownerId);for(const attempt of this.attempts.values())if(attempt.ownerId===ownerId)this.cancelLogin(ownerId,attempt.id);await this.secrets.delete(connection?.secretRef);await this.store.removeEntireConnection(ownerId);this.invalidate(ownerId);}
 close(){for(const attempt of this.attempts.values())if(['starting','waiting'].includes(attempt.status)){attempt.status='cancelled';attempt.process.kill('SIGTERM');void rm(attempt.directory,{recursive:true,force:true});}this.attempts.clear();}
}
