/** Sanitized verification of the local HTTPS deployment. */
import {readFileSync} from 'node:fs';
import {request as httpsRequest} from 'node:https';
import {z} from 'zod';
const origin=process.env.MARVIN_SMOKE_ORIGIN??'https://192.168.1.5:8443',ca=readFileSync('work/board/board-backend-root.crt'),login=z.object({password:z.string()}).parse(JSON.parse(readFileSync('work/board/backend-login.json','utf8')));let cookie='',csrf='';
async function request(path:string,method='GET',body?:unknown){const bytes=body===undefined?undefined:Buffer.from(JSON.stringify(body));return new Promise<{status:number;headers:Record<string,string|string[]|undefined>;text:string}>((resolve,reject)=>{const call=httpsRequest(origin+path,{method,ca,rejectUnauthorized:true,headers:{origin,...(cookie?{cookie}:{}),...(csrf&&method!=='GET'?{'x-csrf-token':csrf}:{}),...(bytes?{'content-type':'application/json','content-length':bytes.length}:{})}},response=>{const chunks:Buffer[]=[];response.on('data',chunk=>chunks.push(chunk));response.on('end',()=>{if(response.headers['set-cookie'])cookie=response.headers['set-cookie'][0]!.split(';')[0]!;resolve({status:response.statusCode??0,headers:response.headers,text:Buffer.concat(chunks).toString()});});});call.on('error',reject);call.end(bytes);});}
const page=await request('/'),script=/src="([^"]+\.js)"/.exec(page.text)?.[1];if(page.status!==200||!script)throw new Error('Deployment page unavailable.');const bundle=await request(script),video=await request('/assets/video/marvin_moving_20sec_pingpong.mp4');
const auth=await request('/api/auth/login','POST',{password:login.password});login.password='';if(auth.status!==200)throw new Error('Deployment login failed.');csrf=JSON.parse(auth.text).csrf;let settings=await request('/api/settings'),value=JSON.parse(settings.text);if(value.entireStatus==='ready'){const connected=await request('/api/entire/connect','POST',{});if(connected.status!==200)throw new Error('Entire connection failed.');settings=await request('/api/settings');value=JSON.parse(settings.text);}
const result={page:true,video:video.status===200&&Number(video.headers['content-length']??video.text.length)>100000,bundleUsesVideo:bundle.text.includes('marvin_moving_20sec_pingpong.mp4'),captionsRemoved:!bundle.text.includes('MOSTLY HARMLESS'),entireStatus:value.entireStatus,entireAvailable:value.entireAvailable,repositories:(value.repositories??[]).map((repository:{name:string})=>repository.name)};
console.log(JSON.stringify(result));if(!result.video||!result.bundleUsesVideo||!result.captionsRemoved||result.entireStatus!=='connected'||!result.entireAvailable||!result.repositories.length)process.exitCode=1;
