/** Physical owner enrollment on the isolated LAN test deployment. Never prints credentials or SSIDs. */
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {readFileSync,writeFileSync} from 'node:fs';
import {request as httpsRequest} from 'node:https';
import {resolve} from 'node:path';
import {parseArgs} from 'node:util';
import {z} from 'zod';
import {DomainError} from '../packages/contracts/src/index.js';
import {Security2} from '../packages/provisioning/src/security2.js';
import {PhysicalRobot,canResumePhysicalSetup} from '../packages/provisioning/src/physical.js';
const {values}=parseArgs({options:{change:{type:'boolean'},resume:{type:'boolean'},preflight:{type:'boolean'},presence:{type:'boolean'},verify:{type:'boolean'},hidden:{type:'boolean'},'wrong-password':{type:'boolean'}}});
const origin='https://192.168.1.5:8443',ca=readFileSync('work/board/board-backend-root.crt'),login=z.object({password:z.string()}).parse(JSON.parse(readFileSync('work/board/backend-login.json','utf8')));let cookie='',csrf='';
async function api(path:string,method='GET',body?:unknown):Promise<any>{
 const data=body===undefined?null:Buffer.from(JSON.stringify(body));return new Promise((resolve,reject)=>{const request=httpsRequest(origin+path,{method,ca,rejectUnauthorized:true,timeout:20000,headers:{origin,...(cookie?{cookie}:{}),...(csrf?{'x-csrf-token':csrf}:{}),...(data?{'content-type':'application/json','content-length':data.length}:{})}},response=>{let bytes=0;const parts:Buffer[]=[];response.on('data',part=>{bytes+=part.length;if(bytes>1048576){response.destroy();reject(new Error('Backend response too large'));}else parts.push(part);});response.on('end',()=>{if(response.statusCode!==200&&response.statusCode!==201){reject(new Error('Backend HTTP '+response.statusCode));return;}if(response.headers['set-cookie'])cookie=response.headers['set-cookie'][0].split(';')[0];try{resolve(JSON.parse(Buffer.concat(parts).toString()));}catch{reject(new Error('Invalid backend response'));}});});request.on('timeout',()=>request.destroy(new Error('Backend timed out')));request.on('error',()=>reject(new Error('Backend TLS or transport failed')));request.end(data);});
}
csrf=(await api('/api/auth/login','POST',{password:login.password})).csrf;login.password='';const before=(await api('/api/settings')).body;if(values.preflight){console.log(JSON.stringify({httpsLogin:true,hasLinkedRobot:!!before}));process.exit(0);}
const card=z.object({deviceId:z.string(),username:z.string(),password:z.string()}).parse(JSON.parse(readFileSync('work/board/factory-owner-288485b2ab10/setup-secret.json','utf8')));
if(values.verify){if(before?.device_id!==card.deviceId)throw new Error('This account does not own the test board.');const deadline=Date.now()+60000;let presence:any=null;do{presence=(await api('/api/robot/presence')).presence;if(presence?.deviceId===card.deviceId)break;await new Promise(resolve=>setTimeout(resolve,500));}while(Date.now()<deadline);const samples:any[]=[];for(let i=0;i<5;i++){await new Promise(resolve=>setTimeout(resolve,5000));const p=(await api('/api/robot/presence')).presence;samples.push({online:p?.deviceId===card.deviceId,epochMatches:p?.epoch===before.epoch,sameBoot:p?.bootId===presence?.bootId});}const result={at:new Date().toISOString(),passed:!!presence&&samples.every(s=>s.online&&s.epochMatches&&s.sameBoot),bootId:presence?.bootId,samples,scope:'Five physical gateway presence checks at five-second intervals, exceeding the 15-second heartbeat expiry; no BLE reset, speech or action claim.'};writeFileSync('work/board/owner-verify-'+Date.now()+'.json',JSON.stringify(result,null,2),{mode:0o600});console.log(JSON.stringify(result));process.exit(result.passed?0:1);}
if(values.change&&before?.device_id!==card.deviceId)throw new Error('The test account does not own this device.');if(!values.change&&!values.resume&&before)throw new Error('The test account already has a robot; use --resume or --change.');
const child=spawn(resolve('work/idf-tools/python_env/idf5.4_py3.13_env/bin/python'),['firmware/tools/ble-bridge.py'],{stdio:['pipe','pipe','inherit']}),lines=createInterface({input:child.stdout})[Symbol.asyncIterator]();
async function receive(){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([lines.next().then(({value,done})=>{if(done)throw new Error('BLE closed');const data=JSON.parse(value);if(data.error)throw new Error('BLE transport failed');return data;}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('BLE timeout')),45000);})]);}finally{clearTimeout(timer);}}
async function exchange(channel:string,data:Uint8Array){child.stdin.write(JSON.stringify({op:'exchange',channel,hex:Buffer.from(data).toString('hex')})+'\n');return new Uint8Array(Buffer.from((await receive()).hex,'hex'));}
const secure=new Security2();let robot:PhysicalRobot|undefined;const started=Date.now();
try{
 await receive();const version=JSON.parse(new TextDecoder().decode(await exchange('ff51',new TextEncoder().encode('---'))));if(version.marvin!==1||version.security!==2||version.patch!==1||version.enrollment!==1)throw new Error('Install the owner enrollment firmware profile first.');
 await secure.open(card.username,card.password,data=>exchange('ff52',data));card.password='';
 robot=new PhysicalRobot(card.deviceId,{command:async value=>JSON.parse(new TextDecoder().decode(await secure.exchange(new TextEncoder().encode(JSON.stringify(value)),data=>exchange('ff53',data)))),close(){secure.close();child.stdin.end(JSON.stringify({op:'close'})+'\n');child.kill();}},{ticket:value=>api('/api/robot/enrollment','POST',value),cancel:async id=>{await api('/api/robot/enrollment/'+encodeURIComponent(id),'DELETE');},binding:async()=>(await api('/api/settings')).body},!!values.change);
 const signal=AbortSignal.timeout(150000),progress=(stage:string)=>console.log(JSON.stringify({stage}));
 if(values.resume)await robot.resume(undefined,progress,signal);else{const wifi=z.object({ssid:z.string(),password:z.string()}).strict().parse(JSON.parse(readFileSync('work/board/wifi-test.json','utf8'))),scan=await robot.scan(),network=values.hidden?robot.hiddenNetwork(wifi.ssid):scan.networks.find(n=>n.ssid===wifi.ssid&&n.compatible);if(!network)throw new Error('The test network is not visible to Marvin.');if(values['wrong-password'])wifi.password='marvin-deliberately-wrong-password';await robot.connect(network,wifi.password,progress,signal);wifi.password='';}
 const after=(await api('/api/settings')).body,operation=values.resume?'resume':values.hidden?'hidden-network':values['wrong-password']?'wrong-password':values.change?'network':'claim',result={at:new Date().toISOString(),passed:after?.device_id===card.deviceId&&!after.simulated,operation,ownerPreserved:values.change?before.device_id===after.device_id:null,elapsedMs:Date.now()-started,scope:values.resume?'Physical Security2 recovery and saved network/account confirmation; no new password or ticket required for an already completed setup.':'Physical Security2 BLE, robot scan, signed account ticket, on-device verification, Wi-Fi and TLS device redemption on the isolated LAN test backend. No speech or native device socket claim.'};
 if(values.presence){let presence:any=null;const deadline=Date.now()+45000;do{presence=(await api('/api/robot/presence')).presence;if(presence?.deviceId===card.deviceId)break;await new Promise(resolve=>setTimeout(resolve,500));}while(Date.now()<deadline);const native={at:new Date().toISOString(),passed:presence?.deviceId===card.deviceId&&presence?.status==='online',epochMatches:presence?.epoch===after.epoch,capabilities:presence?.capabilities??[],scope:'Physical native WSS gateway presence after owner enrollment; no speech or action claim.'};writeFileSync('work/board/owner-native-presence-'+Date.now()+'.json',JSON.stringify(native,null,2),{mode:0o600});console.log(JSON.stringify(native));if(!native.passed||!native.epochMatches)process.exitCode=1;}
 writeFileSync('work/board/owner-'+result.operation+'-'+Date.now()+'.json',JSON.stringify(result,null,2),{mode:0o600});console.log(JSON.stringify(result));if(!result.passed)process.exitCode=1;
}catch(error){const result={at:new Date().toISOString(),passed:false,operation:values.hidden?'hidden-network':values['wrong-password']?'wrong-password':values.change?'network':'claim',resumable:canResumePhysicalSetup(error),errorCode:error instanceof DomainError?error.code:'TRANSPORT_ERROR',elapsedMs:Date.now()-started,scope:'Physical setup attempt stopped before completion was confirmed; credentials and SSIDs omitted.'};writeFileSync('work/board/owner-'+result.operation+'-interrupted-'+Date.now()+'.json',JSON.stringify(result,null,2),{mode:0o600});console.log(JSON.stringify(result));if(!result.resumable)throw error;process.exitCode=2;
}finally{robot?.close();secure.close();child.kill();}
