import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
const directory='work/firmware-ticket-vectors';await mkdir(directory,{recursive:true});const key=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),other=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),now=1789263000;
const base={iss:'https://marvin.example',aud:'marvin_'+'a'.repeat(32),sub:randomUUID(),jti:randomUUID(),iat:now,exp:now+120,op:'claim',nonce:'1'.repeat(64),epoch:7};
function ticket(body:object=base,header:object={alg:'ES256',typ:'JWT',kid:'fixture'},privateKey=key.privateKey){const data=Buffer.from(JSON.stringify(header)).toString('base64url')+'.'+Buffer.from(JSON.stringify(body)).toString('base64url');return data+'.'+sign('sha256',Buffer.from(data),{key:privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');}
const expectation={issuer:base.iss,device:base.aud,nonce:base.nonce,operation:'claim',owner:null,epoch:0,now,ageMs:1000};
const cases:{name:string;ticket:string;accept:boolean;expect:typeof expectation|Record<string,unknown>}[]=[];
const add=(name:string,body:object,accept=false,changes:object={},header?:object,privateKey=key.privateKey)=>cases.push({name,ticket:ticket(body,header,privateKey),accept,expect:{...expectation,...changes}});
add('valid-claim',base,true);
add('valid-network',{...base,op:'network'},true,{operation:'network',owner:base.sub,epoch:7});
add('valid-reconcile',{...base,jti:randomUUID(),op:'reconcile'},true,{operation:'reconcile',owner:base.sub,epoch:7});
add('wrong-backend',{...base,iss:'https://attacker.example'});
add('wrong-device',{...base,aud:'marvin_'+'b'.repeat(32)});
add('wrong-nonce',{...base,nonce:'2'.repeat(64)});
add('wrong-operation',{...base,op:'network'});
add('expired',{...base,exp:now});
add('future-issued',{...base,iat:now+10,exp:now+120});
add('excessive-lifetime',{...base,exp:now+121});
add('expired-monotonic-window',base,false,{ageMs:120000});
add('invalid-epoch',{...base,epoch:0});
add('fractional-epoch',{...base,epoch:7.5});
add('wrong-owner',{...base,op:'network'},false,{operation:'network',owner:randomUUID(),epoch:7});
add('wrong-ownership-epoch',{...base,op:'network'},false,{operation:'network',owner:base.sub,epoch:8});
add('network-without-known-owner',{...base,op:'network'},false,{operation:'network',epoch:7});
add('wrong-signing-key',base,false,{},undefined,other.privateKey);
add('algorithm-confusion',base,false,{},{alg:'none',typ:'JWT'});
add('wrong-token-type',base,false,{},{alg:'ES256',typ:'other'});
add('oversized-owner',{...base,sub:'a'.repeat(129)});
add('invalid-owner-characters',{...base,sub:'owner/other'});
add('embedded-nul-owner',{...base,sub:'owner\u0000hidden'});
add('nested-payload',{...base,extra:{nested:true}});
add('invalid-clock',base,false,{now:4102444801});
const valid=ticket();cases.push({name:'corrupt-signature',ticket:valid.slice(0,-8)+'AAAAAAAA',accept:false,expect:expectation},{name:'extra-segment',ticket:valid+'.extra',accept:false,expect:expectation},{name:'empty-token',ticket:'',accept:false,expect:expectation});
const head=Buffer.from('{"alg":"ES256","alg":"none","typ":"JWT"}').toString('base64url'),body=Buffer.from(JSON.stringify(base)).toString('base64url'),data=head+'.'+body;
cases.push({name:'duplicate-header-field',ticket:data+'.'+sign('sha256',Buffer.from(data),{key:key.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url'),accept:false,expect:expectation});
await writeFile(directory+'/public.pem',key.publicKey.export({format:'pem',type:'spki'}));await writeFile(directory+'/cases.json',JSON.stringify(cases));console.log('Generated '+cases.length+' synthetic signature/scope/expiry cases; no real device credentials.');
