import {it,expect} from 'vitest';
import {createServer} from 'node:http';
import {AnthropicTextProvider} from '../../packages/runtime/src/anthropic.js';
import {DomainError} from '../../packages/contracts/src/index.js';
import type {ModelContext} from '../../packages/runtime/src/provider.js';
const event=(data:any)=>'event: '+data.type+'\ndata: '+JSON.stringify(data)+'\n\n';
const context:ModelContext={interaction:{ownerId:'o',conversationId:'c',interactionId:'i',routeId:'web',surface:'web_text',repositoryId:null,entireState:'disconnected',body:null},summary:'The chosen color is cobalt.',messages:[{userText:'Remember cobalt',assistantText:'Remembered.',status:'completed'}],input:'What color?'};
function response(tool:boolean){const block=tool?{type:'tool_use',id:'tool1',name:'physical_head',input:{}}:{type:'text',text:''};return event({type:'message_start',message:{id:'msg1',type:'message',role:'assistant',model:'fixture',content:[],stop_reason:null,stop_sequence:null,usage:{input_tokens:10,output_tokens:1}}})+event({type:'content_block_start',index:0,content_block:block})+event({type:'content_block_delta',index:0,delta:tool?{type:'input_json_delta',partial_json:'{}'}:{type:'text_delta',text:'Cobalt.'}})+event({type:'content_block_stop',index:0})+event({type:'message_delta',delta:{stop_reason:tool?'tool_use':'end_turn',stop_sequence:null},usage:{output_tokens:4}})+event({type:'message_stop'});}
it('20 fresh SDK instances reconstruct canonical context without provider session IDs',async()=>{const requests:any[]=[];const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;requests.push(JSON.parse(body));res.writeHead(200,{'content-type':'text/event-stream'});res.end(response(false));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const base='http://127.0.0.1:'+(server.address() as any).port;for(let i=0;i<20;i++){const provider=new AnthropicTextProvider('test-key','fixture',base),output=[];for await(const e of provider.run(context,async()=>{throw new Error('Unexpected tool');},new AbortController().signal))output.push(e);expect(output).toEqual([{type:'delta',text:'Cobalt.'}]);}expect(requests).toHaveLength(20);expect(requests.every(r=>JSON.stringify(r.messages).includes('Remember cobalt')&&JSON.stringify(r.messages).includes('chosen color is cobalt')&&!('previous_response_id' in r))).toBe(true);expect(requests.every(r=>r.tools.length===0)).toBe(true);}finally{await new Promise<void>(r=>server.close(()=>r()));}});
it('forged physical tool calls become truthful error results, not successful actions',async()=>{const requests:any[]=[];let invoked=0;const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;requests.push(JSON.parse(body));res.writeHead(200,{'content-type':'text/event-stream'});res.end(response(requests.length===1));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const provider=new AnthropicTextProvider('test-key','fixture','http://127.0.0.1:'+(server.address() as any).port);for await(const _ of provider.run(context,async()=>{invoked++;throw new DomainError('TOOL_FORBIDDEN','Web interactions cannot move Marvin.',403);},new AbortController().signal)){}expect(invoked).toBe(1);expect(requests).toHaveLength(2);const result=requests[1].messages.at(-1).content[0];expect(result.is_error).toBe(true);expect(result.content).toContain('TOOL_FORBIDDEN');}finally{await new Promise<void>(r=>server.close(()=>r()));}});
