import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import WebSocket from 'ws';
import {createApp} from '../../apps/server/src/app.js';
import {config} from '../../apps/server/src/config.js';
import {sqliteDatabase} from '../../packages/persistence/src/database.js';
import {FixtureTextProvider,type ModelContext} from '../../packages/runtime/src/provider.js';
import type {VoiceProvider,VoiceSignal} from '../../packages/runtime/src/voice.js';
const until=async(fn:()=>boolean|Promise<boolean>)=>{for(let i=0;i<400;i++){if(await fn())return;await new Promise(r=>setTimeout(r,5));}throw new Error('Timed out');};
it.each([24000,16000])('100 body turns at input rate %i route only to their device and close the provider',async(inputRate)=>{
 let notify:(s:VoiceSignal)=>void=()=>{},opens=0,closes=0,uploaded=0,outputBytes=960;const contexts:ModelContext[]=[];
 const voice:VoiceProvider={async connect(signal){opens++;notify=signal;return {append:pcm=>{uploaded+=pcm.length;},clear(){},close(){closes++;},forTurn(){return {name:'body-fixture',async *run(ctx){contexts.push(ctx);yield {type:'audio',pcm:Buffer.alloc(outputBytes).toString('base64')};yield {type:'delta',text:'Hello from body.'};}};}};}};
 const service=await createApp(config({NODE_ENV:'test'}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0),voice});const sockets:WebSocket[]=[];
 const address=(await service.app.listen({host:'127.0.0.1',port:0})).replace('http:','ws:')+'/api/device/socket';
 async function connect(){const owner=(await service.store.ensureOwner('test',randomUUID(),'Owner')).id,device=randomUUID(),enrollment=randomUUID();await service.store.reserve(owner,device,enrollment);await service.store.redeem(owner,device,enrollment,'Home');const token=await service.devices.persistence.issue(owner,device),ws=new WebSocket(address,{headers:{authorization:'Bearer '+token}});sockets.push(ws);const events:any[]=[],audio:Buffer[]=[];ws.on('message',(data,binary)=>{if(binary)audio.push(Buffer.from(data as Buffer));else events.push(JSON.parse(data.toString()));});await new Promise<void>(r=>ws.once('open',r));ws.send(JSON.stringify({type:'hello',protocol:{major:1,minor:inputRate===16000?2:1},...(inputRate===16000?{audioInputRate:16000}:{}),deviceId:device,bootId:randomUUID(),firmware:'test',capabilities:['voice']}));await until(()=>events.some(e=>e.type==='welcome'));return {ws,owner,device,events,audio};}
 try{const a=await connect(),b=await connect();expect(opens).toBe(0);a.ws.send(JSON.stringify({type:'voice_start',reason:'button'}));await until(()=>a.events.some(e=>e.type==='voice_ready'));a.ws.send(Buffer.alloc(960));await until(()=>uploaded===(inputRate===16000?1440:960));expect(a.events.find(e=>e.type==='voice_ready')).toMatchObject({inputSampleRate:inputRate,sampleRate:24000});
 for(let i=0;i<100;i++){notify({type:'transcript',itemId:randomUUID(),text:'Say hello '+i});await until(()=>a.events.filter(e=>e.type==='voice_turn_end').length===i+1);}
 expect(a.audio).toHaveLength(100);expect(b.audio).toHaveLength(0);expect(b.events.some(e=>e.type.startsWith('voice'))).toBe(false);expect(contexts.every(c=>c.interaction.surface==='body_voice'&&c.interaction.routeId===a.device)).toBe(true);expect(a.audio.every(frame=>frame.subarray(0,4).toString()==='MVA1'&&frame.length===980)).toBe(true);
 const last=contexts.at(-1)!;expect(last.messages.some(m=>m.userText==='Say hello 98')).toBe(true);
 outputBytes=48000;const burstStarted=performance.now();notify({type:'transcript',itemId:randomUUID(),text:'Burst test'});await until(()=>a.events.filter(e=>e.type==='voice_turn_end').length===101);
 expect(a.audio).toHaveLength(113);expect(performance.now()-burstStarted).toBeGreaterThanOrEqual(740);
 outputBytes=480000;notify({type:'transcript',itemId:randomUUID(),text:'Interrupt a long burst'});await until(()=>a.audio.length>=116);const flushCount=a.events.filter(e=>e.type==='audio_flush').length;a.ws.send(JSON.stringify({type:'voice_interrupt'}));await until(()=>a.events.filter(e=>e.type==='audio_flush').length>flushCount);const before=a.audio.length;await new Promise(resolve=>setTimeout(resolve,150));expect(a.audio.length).toBe(before);
 a.ws.send(JSON.stringify({type:'voice_stop'}));await until(()=>closes===1);expect(service.devices.presence(a.owner)).not.toBeNull();expect(opens).toBe(1);
 expect(service.devices.diagnostics(a.owner)).toMatchObject({audioReceivedBytes:960,audioSentBytes:a.audio.reduce((n,f)=>n+f.length-20,0),voiceStarts:1,voiceActive:false});
 expect(service.devices.diagnostics(b.owner)).toMatchObject({audioReceivedBytes:0,audioSentBytes:0,voiceStarts:0,voiceActive:false});
 expect(service.devices.diagnostics(randomUUID())).toBeNull();
 }finally{for(const ws of sockets)ws.close();await service.app.close();}
},30000);
it('a provider connection failure preserves device presence and uploads no idle audio',async()=>{
 const voice:VoiceProvider={async connect(){throw new Error('Unavailable');}};const service=await createApp(config({NODE_ENV:'test'}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0),voice});const owner=(await service.store.ensureOwner('test','o','Owner')).id,device=randomUUID(),e=randomUUID();await service.store.reserve(owner,device,e);await service.store.redeem(owner,device,e,'Home');const token=await service.devices.persistence.issue(owner,device);const addr=(await service.app.listen({host:'127.0.0.1',port:0})).replace('http:','ws:');const ws=new WebSocket(addr+'/api/device/socket',{headers:{authorization:'Bearer '+token}}),events:any[]=[];ws.on('message',data=>events.push(JSON.parse(data.toString())));
 try{await new Promise<void>(r=>ws.once('open',r));ws.send(JSON.stringify({type:'hello',protocol:{major:1,minor:1},deviceId:device,bootId:randomUUID(),firmware:'test',capabilities:['voice']}));await until(()=>events.some(e=>e.type==='welcome'));ws.send(JSON.stringify({type:'voice_start',reason:'wake'}));await until(()=>events.some(e=>e.type==='voice_error'));expect(service.devices.presence(owner)).not.toBeNull();expect(service.devices.voice?.active(device)).toBe(false);}finally{ws.close();await service.app.close();}
});
it.each([['context','stop'],['admission','stop'],['context','interrupt'],['admission','interrupt']] as const)('cancelling during %s by %s fences pending body work',async(boundary,action)=>{
 const signals:((e:VoiceSignal)=>void)[]=[];let closes=0,runs=0;
 const provider:VoiceProvider={async connect(signal){signals.push(signal);return {append(){},clear(){},close(){closes++;},forTurn(){return {name:'race-fixture',async *run(){runs++;yield {type:'delta',text:'Late output'};yield {type:'audio',pcm:Buffer.alloc(960).toString('base64')};}};}};}};
 const service=await createApp(config({NODE_ENV:'test'}),{database:sqliteDatabase(),voice:provider}),owner=(await service.store.ensureOwner('test',randomUUID(),'Owner')).id,device=randomUUID(),enrollment=randomUUID();await service.store.reserve(owner,device,enrollment);await service.store.redeem(owner,device,enrollment,'Home');const token=await service.devices.persistence.issue(owner,device),conversation=await service.store.createConversation(owner);const address=(await service.app.listen({host:'127.0.0.1',port:0})).replace('http:','ws:')+'/api/device/socket';
 const ws=new WebSocket(address,{headers:{authorization:'Bearer '+token}}),events:any[]=[],audio:Buffer[]=[];ws.on('message',(raw,binary)=>binary?audio.push(Buffer.from(raw as Buffer)):events.push(JSON.parse(raw.toString())));await new Promise<void>(resolve=>ws.once('open',resolve));
 let entered=false,release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;}),context=service.runtime.context.bind(service.runtime),begin=service.store.begin.bind(service.store);
 if(boundary==='context')service.runtime.context=async(...args)=>{entered=true;await gate;return context(...args);};else service.store.begin=async(...args)=>{entered=true;await gate;return begin(...args);};
 try{ws.send(JSON.stringify({type:'hello',protocol:{major:1,minor:1},deviceId:device,bootId:randomUUID(),firmware:'fixture',capabilities:['voice']}));await until(()=>events.some(e=>e.type==='welcome'));ws.send(JSON.stringify({type:'voice_start',reason:'button'}));await until(()=>signals.length===1&&events.some(e=>e.type==='voice_ready'));signals[0]({type:'transcript',itemId:'old',text:'A late request'});await until(()=>entered);if(action==='stop'){ws.send(JSON.stringify({type:'voice_stop'}));await until(()=>events.some(e=>e.type==='voice_closed'));ws.send(JSON.stringify({type:'voice_start',reason:'button'}));await until(()=>signals.length===2&&events.filter(e=>e.type==='voice_ready').length===2);}else{const flushes=events.filter(e=>e.type==='audio_flush').length;ws.send(JSON.stringify({type:'voice_interrupt'}));await until(()=>events.filter(e=>e.type==='audio_flush').length>flushes);}release();await new Promise(resolve=>setTimeout(resolve,40));await service.runtime.drain();if(action==='stop')signals[0]({type:'fault',code:'OLD_PROVIDER_FAILURE'});await new Promise(resolve=>setTimeout(resolve,10));expect(closes).toBe(action==='stop'?1:0);expect(service.devices.voice!.active(device)).toBe(true);expect(audio).toHaveLength(0);const turns=await service.store.turns(owner,conversation.id);if(boundary==='context'){expect(runs).toBe(0);expect(turns).toHaveLength(0);}else{expect(turns).toHaveLength(1);expect(turns[0].status).toBe('cancelled');}
 }finally{release();service.runtime.context=context;service.store.begin=begin;ws.terminate();await service.app.close();}
});
