import {it,expect} from 'vitest';
import {WebSocketServer,WebSocket} from 'ws';
import {DeepgramVoiceProvider} from '../../packages/runtime/src/deepgram-voice.js';
import type {VoiceSignal} from '../../packages/runtime/src/voice.js';
import type {ModelContext,ModelEvent,TextProvider} from '../../packages/runtime/src/provider.js';
const ctx:ModelContext={interaction:{ownerId:'o',conversationId:'c',interactionId:'i',routeId:'web',surface:'web_voice',repositoryId:null,entireState:'disconnected',body:null},summary:'Cobalt is the chosen color.',messages:[],input:'What color?'};
const until=async(fn:()=>boolean)=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw new Error('Timeout');};
async function fixture(withTool=true){const server=new WebSocketServer({port:0,host:'127.0.0.1'});await new Promise<void>(r=>server.once('listening',r));const listeners:WebSocket[]=[],speakers:WebSocket[]=[],texts:string[]=[],uploads:Buffer[]=[],contexts:ModelContext[]=[];let suppress=false;
 server.on('connection',(ws,req)=>{expect(req.headers.authorization).toBe('Token fixture');const url=new URL(req.url!,'http://fixture');expect(url.searchParams.get('sample_rate')).toBe('24000');
  if(url.pathname.endsWith('listen')){listeners.push(ws);ws.on('message',(data,binary)=>{if(binary)uploads.push(Buffer.from(data as Buffer));});}
  else{speakers.push(ws);let sequence=0;ws.on('message',data=>{const e=JSON.parse(data.toString());if(e.type==='Speak')texts.push(e.text);if(e.type==='Flush'&&!suppress){ws.send(Buffer.alloc(960,3));ws.send(JSON.stringify({type:'Flushed',sequence_id:sequence++}));}});}
 });
 const model:TextProvider={name:'canonical-fixture',async *run(context,execute){contexts.push(context);if(withTool)await execute('fixture_tool',{});yield {type:'delta',text:'Cobalt.'};}};
 const provider=new DeepgramVoiceProvider('fixture','nova-3','aura-2-asteria-en',model,'ws://127.0.0.1:'+(server.address() as any).port);
 const transcript=(ws:WebSocket,start=0)=>ws.send(JSON.stringify({type:'Results',start,duration:1,is_final:true,speech_final:true,channel:{alternatives:[{transcript:'What color?'}]}}));
 return {server,listeners,speakers,texts,uploads,contexts,provider,transcript,suppress:()=>{suppress=true;},close:async()=>{for(const ws of server.clients)ws.terminate();await new Promise<void>(r=>server.close(()=>r()));}};
}
it('reconstructs 20 canonical turns with bounded PCM, tools and single-use utterances',async()=>{const f=await fixture(),signals:VoiceSignal[]=[];const connection=await f.provider.connect(e=>signals.push(e));let tools=0;
 try{for(let i=0;i<20;i++){f.transcript(f.listeners[0],i);await until(()=>signals.filter(e=>e.type==='transcript').length===i+1);const e=signals.filter(e=>e.type==='transcript')[i] as Extract<VoiceSignal,{type:'transcript'}>;const provider=connection.forTurn(e.itemId),events:ModelEvent[]=[];for await(const event of provider.run(ctx,async()=>{tools++;},new AbortController().signal))events.push(event);expect(events.filter(e=>e.type==='audio')).toHaveLength(2);expect(()=>connection.forTurn(e.itemId)).toThrow();}
 connection.append(Buffer.alloc(960,7));await until(()=>f.uploads.length===1);expect(f.uploads[0]).toEqual(Buffer.alloc(960,7));expect(tools).toBe(20);expect(f.contexts.every(c=>c===ctx)).toBe(true);expect(f.texts).toEqual(Array(20).fill('Cobalt.'));
 }finally{connection.close();await f.close();}
});
it('clear replaces recognition transport and fences stale transcripts',async()=>{const f=await fixture(),signals:VoiceSignal[]=[];const c=await f.provider.connect(e=>signals.push(e));try{c.clear();c.append(Buffer.alloc(960,9));await until(()=>f.listeners.length===2&&f.uploads.length===1);expect(f.uploads[0]).toEqual(Buffer.alloc(960,9));f.transcript(f.listeners[1]);f.transcript(f.listeners[1]);await until(()=>signals.some(e=>e.type==='transcript'));expect(signals.filter(e=>e.type==='transcript')).toHaveLength(1);}finally{c.close();await f.close();}});
it('interruption retires synthesis without waiting for a provider flush',async()=>{const f=await fixture(),signals:VoiceSignal[]=[];f.suppress();const c=await f.provider.connect(e=>signals.push(e));try{f.transcript(f.listeners[0]);await until(()=>signals.some(e=>e.type==='transcript'));const e=signals.find(e=>e.type==='transcript') as Extract<VoiceSignal,{type:'transcript'}>,abort=new AbortController();const run=(async()=>{for await(const _ of c.forTurn(e.itemId).run(ctx,async()=>{},abort.signal)){} })();const rejected=expect(run).rejects.toThrow();await until(()=>f.texts.length>0);abort.abort();await rejected;expect(signals.some(e=>e.type==='fault')).toBe(false);}finally{c.close();await f.close();}});
it('malformed recognition closes the session once and rejects further audio',async()=>{const f=await fixture(),signals:VoiceSignal[]=[];const c=await f.provider.connect(e=>signals.push(e));try{f.listeners[0].send(Buffer.alloc(2));await until(()=>signals.some(e=>e.type==='fault'));expect(signals.filter(e=>e.type==='fault')).toHaveLength(1);expect(()=>c.append(Buffer.alloc(960))).toThrow();expect(f.speakers).toHaveLength(0);}finally{c.close();await f.close();}});
it('invalid input frames do not create synthesis or upload bytes',async()=>{const f=await fixture();const c=await f.provider.connect(()=>{});try{for(const length of [0,1,24002])expect(()=>c.append(Buffer.alloc(length))).toThrow();expect(f.uploads).toHaveLength(0);expect(f.speakers).toHaveLength(0);}finally{c.close();await f.close();}});
it('rapid repeated clear keeps the newest recognition generation alive',async()=>{const f=await fixture(),signals:VoiceSignal[]=[];const c=await f.provider.connect(e=>signals.push(e));try{for(let i=0;i<20;i++)c.clear();c.append(Buffer.alloc(960,11));await until(()=>f.uploads.length===1||signals.some(e=>e.type==='fault'));expect(signals.filter(e=>e.type==='fault')).toHaveLength(0);expect(f.uploads).toEqual([Buffer.alloc(960,11)]);f.transcript(f.listeners.at(-1)!);await until(()=>signals.some(e=>e.type==='transcript'));}finally{c.close();await f.close();}});
it('advertises the configured second voice adapter to the portal',async()=>{const {createApp}=await import('../../apps/server/src/app.js'),{config}=await import('../../apps/server/src/config.js'),{sqliteDatabase}=await import('../../packages/persistence/src/database.js');const service=await createApp(config({NODE_ENV:'test',MODEL_PROVIDER:'openai',OPENAI_API_KEY:'fixture-not-a-key',OPENAI_MODEL:'fixture',VOICE_PROVIDER:'deepgram',DEEPGRAM_API_KEY:'fixture-not-a-key',DEEPGRAM_STT_MODEL:'nova-3',DEEPGRAM_TTS_MODEL:'aura-2-asteria-en'}),{database:sqliteDatabase()});try{expect((await service.app.inject('/api/config')).json().voiceAvailable).toBe(true);}finally{await service.app.close();}});
it('20 authenticated voice sessions retire and recover canonical history through the actual adapter',async()=>{
 const {createApp}=await import('../../apps/server/src/app.js'),{config}=await import('../../apps/server/src/config.js'),{sqliteDatabase}=await import('../../packages/persistence/src/database.js');const f=await fixture(false),service=await createApp(config({NODE_ENV:'test'}),{database:sqliteDatabase(),voice:f.provider});const sockets:WebSocket[]=[];
 try{const owner=await service.store.ensureOwner('test','voice-owner','Owner'),session=await service.store.createSession(owner.id),conversation=await service.store.createConversation(owner.id);const address=(await service.app.listen({host:'127.0.0.1',port:0})).replace('http:','ws:')+'/api/voice';
 for(let i=0;i<20;i++){
  const ws=new WebSocket(address,{headers:{origin:'http://127.0.0.1:5173',cookie:'marvin_session='+session.token}}),events:any[]=[];sockets.push(ws);ws.on('message',raw=>events.push(JSON.parse(raw.toString())));await new Promise<void>((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});
  ws.send(JSON.stringify({v:1,type:'start',csrf:session.csrf,conversationId:conversation.id}));await until(()=>events.some(e=>e.type==='ready'));ws.send(Buffer.alloc(960));await until(()=>f.uploads.length===i+1);f.transcript(f.listeners.at(-1)!);
  await until(()=>events.some(e=>e.type==='event'&&e.event.type==='completed'));expect(events.filter(e=>e.type==='audio')).toHaveLength(2);expect(events.some(e=>e.type==='error')).toBe(false);
  const closed=new Promise<void>(resolve=>ws.once('close',()=>resolve()));ws.send(JSON.stringify({v:1,type:'stop'}));await closed;await until(()=>f.listeners.at(-1)!.readyState===WebSocket.CLOSED);
 }
 expect(f.contexts).toHaveLength(20);expect(f.contexts.every(c=>c.interaction.ownerId===owner.id&&c.interaction.conversationId===conversation.id&&c.interaction.surface==='web_voice')).toBe(true);expect(f.contexts.slice(1).every(c=>c.messages.some(m=>m.userText==='What color?'&&m.assistantText==='Cobalt.'))).toBe(true);
 }finally{for(const ws of sockets)ws.terminate();await service.app.close();await f.close();}
});
