import { describe,it,expect,beforeEach,afterEach } from 'vitest';
import { randomUUID } from 'node:crypto';
import { sqliteDatabase,postgresDatabase,type Database } from '../../packages/persistence/src/database.js';
import { migrate } from '../../packages/persistence/src/migrations.js';
import { Store } from '../../packages/persistence/src/store.js';
import type { InteractionContext } from '../../packages/contracts/src/index.js';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const modes=['sqlite',...(process.env.TEST_DATABASE_URL?['postgres']:[])];
for(const mode of modes)describe(`persistence conformance: ${mode}`,()=>{
 let db:Database,store:Store,ownerId:string,conversationId:string;
 beforeEach(async()=>{db=mode==='postgres'?postgresDatabase(process.env.TEST_DATABASE_URL!):sqliteDatabase();await migrate(db);store=new Store(db);ownerId=(await store.ensureOwner('test',randomUUID(),'Test owner')).id;conversationId=(await store.createConversation(ownerId)).id;});
 afterEach(async()=>{await db.close();});
 const context=():InteractionContext=>({ownerId,conversationId,interactionId:randomUUID(),routeId:randomUUID(),surface:'web_text',repositoryId:null,entireState:'disconnected',body:null});
 it('100 concurrent devices can reserve only one owner slot',async()=>{const results=await Promise.allSettled(Array.from({length:100},()=>store.reserve(ownerId,randomUUID(),randomUUID())));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);});
 it('100 owners cannot claim the same device',async()=>{const device=randomUUID();const owners=await Promise.all(Array.from({length:100},()=>store.ensureOwner('test',randomUUID(),'Owner')));const results=await Promise.allSettled(owners.map(o=>store.reserve(o.id,device,randomUUID())));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);});
 it('claim redemption is idempotent, Wi-Fi changes retain identity, unlink bumps epoch',async()=>{const d=randomUUID(),e=randomUUID();await store.reserve(ownerId,d,e);await store.redeem(ownerId,d,e,'Home');await store.redeem(ownerId,d,e,'Home');await store.changeNetwork(ownerId,d,'Friend');const body=await store.body(ownerId);expect(body?.device_id).toBe(d);expect(body?.network).toBe('Friend');await store.unlink(ownerId);expect(await store.body(ownerId)).toBeNull();expect((await store.getConversation(ownerId,conversationId)).id).toBe(conversationId);const next=await store.reserve(ownerId,d,randomUUID());expect(next.epoch).toBe(2);});
 it('expired reservations release both account and device',async()=>{const d=randomUUID();await store.reserve(ownerId,d,randomUUID());await db.query('UPDATE body_slots SET expires_at=? WHERE owner_id=?',[1,ownerId]);await expect(store.reserve(ownerId,d,randomUUID())).resolves.toBeDefined();});
 it('100 concurrent generations create exactly one durable turn; duplicate retry does not regenerate',async()=>{const c=context();const results=await Promise.allSettled(Array.from({length:100},()=>store.begin({...c,interactionId:randomUUID()},'Hello','worker')));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const t=(await store.turns(ownerId,conversationId))[0];expect(await store.begin({...c,interactionId:t.id},'Hello','worker')).toMatchObject({created:false});});
 it('same request ID with different content is rejected',async()=>{const c=context();await store.begin(c,'first','worker');await expect(store.begin(c,'changed','worker')).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});});
 it('tenant isolation covers history, threads and output replay',async()=>{const other=await store.ensureOwner('test',randomUUID(),'Other');await expect(store.getConversation(other.id,conversationId)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(store.turns(other.id,conversationId)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(store.replay(other.id,conversationId,'route')).rejects.toMatchObject({code:'NOT_FOUND'});});
 it('cancelled and expired workers cannot append, while partial text remains',async()=>{const c=context();await store.begin(c,'hello','worker');const e={v:1 as const,interactionId:c.interactionId,conversationId,routeId:c.routeId,type:'delta' as const,text:'partial'};await store.append(e,'worker');await store.cancel(ownerId,c.interactionId);await expect(store.append(e,'worker')).rejects.toMatchObject({code:'FENCED'});expect((await store.turns(ownerId,conversationId))[0]).toMatchObject({assistantText:'partial',status:'cancelled',lastSeq:1});const c2=context();await store.begin(c2,'next','worker');await db.query('UPDATE turns SET lease_until=1 WHERE id=?',[c2.interactionId]);await store.recoverExpired();await expect(store.append({...e,interactionId:c2.interactionId},'worker')).rejects.toMatchObject({code:'FENCED'});});
 it('output replay is scoped to the initiating route',async()=>{const c=context();await store.begin(c,'hello','worker');await store.append({v:1,interactionId:c.interactionId,conversationId,routeId:c.routeId,type:'delta',text:'private'},'worker');expect(await store.replay(ownerId,conversationId,'different-route')).toHaveLength(0);expect(await store.replay(ownerId,conversationId,c.routeId)).toHaveLength(1);});
 it('repository changes are blocked during generation',async()=>{const c=context();await store.begin(c,'hello','worker');await expect(store.setRepository(ownerId,conversationId,'marvin-portal')).rejects.toMatchObject({code:'BUSY'});});
 it('sessions expire and logout revokes independently',async()=>{const s=await store.createSession(ownerId),expired=await store.createSession(ownerId,-1);expect(await store.session(expired.token)).toBeNull();expect((await store.session(s.token))?.ownerId).toBe(ownerId);await store.logout(s.token);expect(await store.session(s.token)).toBeNull();});
});
it('SQLite schema upgrade and process restart preserve canonical history',async()=>{const dir=mkdtempSync(join(tmpdir(),'marvin-upgrade-'));let db=sqliteDatabase(join(dir,'db'));try{await migrate(db,1);let store=new Store(db);const o=await store.ensureOwner('test','upgrade','Owner'),c=await store.createConversation(o.id);await migrate(db,2);await db.close();db=sqliteDatabase(join(dir,'db'));await migrate(db);store=new Store(db);expect((await store.getConversation(o.id,c.id)).id).toBe(c.id);}finally{await db.close();rmSync(dir,{recursive:true,force:true});}});
if(process.env.TEST_DATABASE_URL)it('PostgreSQL fresh schema, upgrade and reopened connection preserve a seeded turn',async()=>{
 const admin=postgresDatabase(process.env.TEST_DATABASE_URL!),schema='upgrade_'+randomUUID().replaceAll('-','');
 await admin.query(`CREATE SCHEMA ${schema}`);
 const url=new URL(process.env.TEST_DATABASE_URL!);url.searchParams.set('options',`-c search_path=${schema}`);
 let db=postgresDatabase(url.toString());
 try{await migrate(db,1);let store=new Store(db);const owner=await store.ensureOwner('test','upgrade','Owner'),c=await store.createConversation(owner.id);await store.begin({ownerId:owner.id,conversationId:c.id,interactionId:'seed',routeId:'r',surface:'web_text',repositoryId:null,entireState:'disconnected',body:null},'Persist this seeded turn','worker');await migrate(db,2);await db.close();db=postgresDatabase(url.toString());await migrate(db);store=new Store(db);expect((await store.turns(owner.id,c.id))[0].userText).toBe('Persist this seeded turn');}finally{await db.close();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.close();}
});
