import {it,expect} from 'vitest';
import {PhysicalRobot,type EnrollmentApi,type SecureSetupLink} from '../../packages/provisioning/src/physical.js';
function rig(change=false){
 const commands:Record<string,unknown>[]=[],http:unknown[]=[],deviceId='marvin_'+'a'.repeat(32);let applied=false,verified=false,closed=false,foreign=false,pending=false;
 const link:SecureSetupLink={async command(r){commands.push(r);if(r.op==='clock')return {clockSet:true};if(r.op==='scan')return {phase:'scanning'};if(r.op==='status')return {phase:pending?'awaiting_backend':applied?'network_verified':'scan_complete',linked:applied,networkConnected:true,hasSavedNetwork:applied,scanGeneration:4,count:1,error:'',...(pending?{pendingNetwork:'Robot-visible AP'}:{})};if(r.op==='network')return {source:'robot',ssid:'Robot-visible AP',rssi:-62,channel:6,scanGeneration:4,supported:true,security:'wpa2-personal'};if(r.op==='challenge')return {challenge:{deviceId:foreign?'marvin_'+'b'.repeat(32):deviceId,nonce:'1'.repeat(64),operation:r.operation,issuedAt:r.issuedAt},proof:'synthetic-proof'};if(r.op==='ticket_begin')return {accepted:true};if(r.op==='ticket_chunk')return {received:Number(r.offset)+String(r.hex).length/2};if(r.op==='ticket_finish'){verified=true;return {verified:true};}if(r.op==='apply'){expect(verified).toBe(true);applied=true;return {phase:'connecting'};}if(r.op==='resume'){pending=false;applied=true;return {phase:'connecting'};}throw new Error('Unknown command');},close(){closed=true;}};
 const server:EnrollmentApi={async ticket(r){http.push(r);return {ticket:'signed-ticket'.repeat(50),enrollmentId:'enrollment',expiresAt:Date.now()+120000};},async cancel(id){http.push({cancel:id});},async binding(){return applied?{device_id:deviceId,network:'Robot-visible AP',simulated:0}:null;}};
 return {robot:new PhysicalRobot(deviceId,link,server,change,1),commands,http,server,link,foreign:()=>{foreign=true;},pending:()=>{pending=true;},closed:()=>closed};
}
it('robot scan indices and ticket chunks precede encrypted password delivery; HTTP gets no Wi-Fi credentials',async()=>{
 const r=rig(),scan=await r.robot.scan();expect(scan.source).toBe('robot');expect(scan.networks[0].ssid).toBe('Robot-visible AP');const stages:string[]=[];await r.robot.connect(scan.networks[0],'synthetic-password',stage=>stages.push(stage),new AbortController().signal);
 expect(stages).toEqual(['connecting_wifi','ready']);expect(r.commands.filter(c=>c.op==='ticket_chunk').every(c=>String(c.hex).length<=240)).toBe(true);expect(r.commands.find(c=>c.op==='apply')).toMatchObject({index:0,scanGeneration:4,password:'synthetic-password'});expect(JSON.stringify(r.http)).not.toMatch(/synthetic-password|Robot-visible AP/);expect((r.http[0] as any).challenge.operation).toBe('claim');
});
it('a network change requires the same identity and a network ticket',async()=>{const r=rig(true),scan=await r.robot.scan();await r.robot.connect(scan.networks[0],'synthetic-password',()=>{},new AbortController().signal);expect((r.http[0] as any).challenge.operation).toBe('network');});
it('forged networks and a different device fail before passwords or HTTP authorization',async()=>{
 const r=rig(),scan=await r.robot.scan();await expect(r.robot.connect({...scan.networks[0],ssid:'Laptop-only AP'},'synthetic-password',()=>{},new AbortController().signal)).rejects.toMatchObject({code:'NETWORK_NOT_SCANNED'});r.foreign();await expect(r.robot.connect(scan.networks[0],'synthetic-password',()=>{},new AbortController().signal)).rejects.toMatchObject({code:'DEVICE_IDENTITY_MISMATCH'});expect(r.http).toHaveLength(0);expect(r.commands.some(c=>'password'in c)).toBe(false);
});
it('cancellation while the backend issues a ticket closes BLE and cancels only the unused reservation',async()=>{
 const r=rig(),scan=await r.robot.scan();let resolve:(v:any)=>void=()=>{};r.server.ticket=()=>new Promise(r=>{resolve=r;});const abort=new AbortController(),work=r.robot.connect(scan.networks[0],'synthetic-password',()=>{},abort.signal);for(let i=0;i<5;i++)await Promise.resolve();abort.abort();resolve({ticket:'ticket',enrollmentId:'unused',expiresAt:Date.now()+120000});await expect(work).rejects.toThrow();expect(r.closed()).toBe(true);expect(r.commands.some(c=>'password'in c)).toBe(false);expect(r.http).toContainEqual({cancel:'unused'});
});
it('resume uses the robot pending network and confirms the server binding without resending credentials',async()=>{const r=rig();r.pending();const stages:string[]=[];await r.robot.resume(undefined,s=>stages.push(s),new AbortController().signal);expect(stages).toContain('ready');expect(r.commands.some(c=>'password'in c)).toBe(false);expect(r.http).toHaveLength(0);});
it('resume after reboot confirms the saved network and binding without a new ticket or apply',async()=>{
 const r=rig(),scan=await r.robot.scan();await r.robot.connect(scan.networks[0],'synthetic-password',()=>{},new AbortController().signal);const command=r.link.command.bind(r.link);r.commands.length=0;r.http.length=0;
 r.link.command=async request=>{const value=await command(request) as any;return request.op==='status'?{...value,phase:'idle',savedNetwork:'Robot-visible AP'}:value;};
 await r.robot.resume(undefined,()=>{},AbortSignal.timeout(1000));expect(r.commands.map(c=>c.op)).toEqual(['clock','status','status']);expect(r.http).toHaveLength(0);
 r.server.binding=async()=>({device_id:'another-device',network:'Robot-visible AP',simulated:0});await expect(r.robot.resume(undefined,()=>{},AbortSignal.timeout(1000))).rejects.toMatchObject({code:'BINDING_UNCONFIRMED'});
});

it('setup cards reject malformed or extra data without echoing private input',async()=>{const {decodeSetupCode}=await import('../../packages/provisioning/src/setup-code.js');const card={deviceId:'marvin_'+'a'.repeat(32),username:'marvin-test',password:'private-synthetic-code'};expect(decodeSetupCode('marvin1.'+Buffer.from(JSON.stringify(card)).toString('base64url'))).toEqual(card);try{decodeSetupCode('private-synthetic-code');throw new Error('unexpected');}catch(e){expect((e as Error).message).not.toContain('private-synthetic-code');}expect(()=>decodeSetupCode('marvin1.'+Buffer.from(JSON.stringify({...card,privateKey:'never allowed'})).toString('base64url'))).toThrow();});

it('confirmed rollback releases the unused server reservation for an immediate password retry',async()=>{const r=rig(),scan=await r.robot.scan(),command=r.link.command.bind(r.link);r.link.command=async request=>{const reply=await command(request) as any;return request.op==='status'&&reply.phase==='network_verified'?{...reply,phase:'failed',linked:false,error:'WIFI_CONNECTION_FAILED'}:reply;};await expect(r.robot.connect(scan.networks[0],'synthetic-password',()=>{},new AbortController().signal)).rejects.toMatchObject({code:'WIFI_CONNECTION_FAILED'});expect(r.http).toContainEqual({cancel:'enrollment'});});
