import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {sqliteDatabase,postgresDatabase} from '../../packages/persistence/src/database.js';
import {migrate} from '../../packages/persistence/src/migrations.js';
import {Store} from '../../packages/persistence/src/store.js';
import {deleteAccount,exportPage} from '../../packages/persistence/src/privacy.js';
for(const mode of ['sqlite',...(process.env.TEST_DATABASE_URL?['postgres']:[])])it(`privacy export excludes secrets and deletion preserves another account: ${mode}`,async()=>{
 const db=mode==='sqlite'?sqliteDatabase():postgresDatabase(process.env.TEST_DATABASE_URL!);await migrate(db);const store=new Store(db);
 try{const owner=(await store.ensureOwner('test',randomUUID(),'Owner')).id,other=(await store.ensureOwner('test',randomUUID(),'Other')).id,c=await store.createConversation(owner),otherC=await store.createConversation(other),session=await store.createSession(owner),device=randomUUID(),e=randomUUID();await store.reserve(owner,device,e);await store.redeem(owner,device,e,'Private Wi-Fi');
 for(let i=0;i<21;i++){const id=randomUUID();await store.begin({ownerId:owner,conversationId:c.id,interactionId:id,routeId:'web',surface:'web_text',repositoryId:null,entireState:'disconnected',body:null},'Private turn '+i,'worker');await store.append({v:1,interactionId:id,conversationId:c.id,routeId:'web',type:'completed'},'worker');}
 const first=await exportPage(store,owner,undefined);expect(first.turns).toHaveLength(20);const second=await exportPage(store,owner,first.nextCursor!);expect(second.turns).toHaveLength(1);expect(JSON.stringify(first)).not.toContain(session.token);expect(JSON.stringify(first)).not.toContain('Private Wi-Fi');await expect(exportPage(store,other,first.nextCursor!)).rejects.toThrow();
 await deleteAccount(store,owner);expect(await store.session(session.token)).toBeNull();expect(await db.query('SELECT id FROM owners WHERE id=?',[owner])).toHaveLength(0);expect(await db.query('SELECT id FROM turns WHERE owner_id=?',[owner])).toHaveLength(0);expect((await store.getConversation(other,otherC.id)).id).toBe(otherC.id);expect((await db.query<any>('SELECT epoch FROM device_epochs WHERE device_id=?',[device]))[0].epoch).toBe(2);
 }finally{await db.close();}
});
it('retention purges old tool/event records and summaries while preserving recent messages',async()=>{const db=sqliteDatabase();await migrate(db);const store=new Store(db);try{const owner=(await store.ensureOwner('test','retention','Owner')).id,c=await store.createConversation(owner),id=randomUUID();await store.begin({ownerId:owner,conversationId:c.id,interactionId:id,routeId:'web',surface:'web_text',repositoryId:null,entireState:'disconnected',body:null},'expired secret','worker');await store.append({v:1,interactionId:id,conversationId:c.id,routeId:'web',type:'completed'},'worker');await store.saveTool(randomUUID(),id,'fixture',{}, {text:'expired secret'},'completed');await db.query('UPDATE turns SET created_at=1 WHERE id=?',[id]);await db.query("UPDATE conversations SET summary='expired secret',summary_through=1 WHERE id=?",[c.id]);const {purgeExpiredHistory}=await import('../../packages/persistence/src/privacy.js');expect(await purgeExpiredHistory(store,owner,1000)).toBe(1);expect(await store.turns(owner,c.id)).toHaveLength(0);expect((await store.getConversation(owner,c.id)).summary).toBe('');expect(await db.query('SELECT * FROM events')).toHaveLength(0);expect(await db.query('SELECT * FROM tool_invocations')).toHaveLength(0);}finally{await db.close();}});
