import { beforeEach,afterEach,it,expect } from 'vitest';
import { createApp } from '../../apps/server/src/app.js';
import { config } from '../../apps/server/src/config.js';
import { sqliteDatabase } from '../../packages/persistence/src/database.js';
import { FixtureTextProvider } from '../../packages/runtime/src/provider.js';
import { GithubIdentity,hashPassword,verifyPassword,safeReturnTo } from '../../apps/server/src/auth.js';
import WebSocket from 'ws';
import { generateKeyPairSync,randomUUID } from 'node:crypto';
import { mkdtempSync,writeFileSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { deviceFingerprint } from '../../packages/enrollment/src/service.js';
let service:Awaited<ReturnType<typeof createApp>>,cookie:string,csrf:string,ownerId:string;
const origin='http://127.0.0.1:5173';
beforeEach(async()=>{service=await createApp(config({NODE_ENV:'test'}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0)});const login=await service.app.inject({method:'POST',url:'/api/auth/login',headers:{origin},payload:{}});expect(login.statusCode).toBe(200);cookie=login.cookies[0].name+'='+login.cookies[0].value;csrf=login.json().csrf;ownerId=login.json().owner.id;});
afterEach(async()=>{await service.app.close();});
const headers=()=>({cookie,origin,'x-csrf-token':csrf});
it('private endpoints require authentication, origin and anti-CSRF token',async()=>{expect((await service.app.inject('/api/conversations')).statusCode).toBe(401);expect((await service.app.inject({method:'POST',url:'/api/conversations',headers:{cookie,origin},payload:{}})).statusCode).toBe(403);expect((await service.app.inject({method:'POST',url:'/api/conversations',headers:{...headers(),origin:'https://attacker.invalid'},payload:{}})).statusCode).toBe(403);});
it('route-level tenant isolation blocks another account thread',async()=>{const other=await service.store.ensureOwner('test','other','Other'),c=await service.store.createConversation(other.id);expect((await service.app.inject({url:'/api/conversations/'+c.id,headers:headers()})).statusCode).toBe(404);});
it('Pet conversation link can be selected independently and rejects foreign conversations',async()=>{const first=await service.store.createConversation(ownerId),second=await service.store.createConversation(ownerId),other=await service.store.ensureOwner('test',randomUUID(),'Other'),foreign=await service.store.createConversation(other.id);expect((await service.app.inject({url:'/api/robot/conversation',headers:headers()})).json()).toEqual({conversationId:null});expect((await service.app.inject({method:'PUT',url:'/api/robot/conversation',headers:headers(),payload:{conversationId:first.id}})).json()).toEqual({conversationId:first.id});await service.store.activate(ownerId,second.id);expect((await service.app.inject({url:'/api/robot/conversation',headers:headers()})).json()).toEqual({conversationId:first.id});expect((await service.app.inject({method:'PUT',url:'/api/robot/conversation',headers:headers(),payload:{conversationId:foreign.id}})).statusCode).toBe(404);expect((await service.app.inject({method:'PUT',url:'/api/robot/conversation',headers:headers(),payload:{conversationId:null}})).json()).toEqual({conversationId:null});});
it('API cannot forge body_voice or send raw physical/write commands',async()=>{const c=await service.store.createConversation(ownerId);for(const payload of [{conversationId:c.id,interactionId:randomUUID(),routeId:'r',text:'move',surface:'body_voice'},{type:'physical_head'}])expect((await service.app.inject({method:'POST',url:'/api/turns',headers:headers(),payload})).statusCode).toBe(400);expect((await service.app.inject({method:'POST',url:'/api/physical/drive',headers:headers(),payload:{}})).statusCode).toBe(404);});
it('turn retry is idempotent and persists partial/complete messages',async()=>{const c=await service.store.createConversation(ownerId);const payload={conversationId:c.id,interactionId:randomUUID(),routeId:'r',text:'hello'};const first=await service.app.inject({method:'POST',url:'/api/turns',headers:headers(),payload});expect(first.statusCode).toBe(202);await service.runtime.drain();const again=await service.app.inject({method:'POST',url:'/api/turns',headers:headers(),payload});expect(again.statusCode).toBe(200);expect(await service.store.turns(ownerId,c.id)).toHaveLength(1);});
it('oversized messages and password-bearing simulation requests fail validation',async()=>{expect((await service.app.inject({method:'POST',url:'/api/turns',headers:headers(),payload:{text:'x'.repeat(40000)}})).statusCode).toBe(413);expect((await service.app.inject({method:'POST',url:'/api/simulation/robot',headers:headers(),payload:{deviceId:'test',enrollmentId:'enroll',network:'Test',password:'do-not-send'}})).statusCode).toBe(400);});
it('logout revokes the server session and does not remove history',async()=>{await service.store.createConversation(ownerId);expect((await service.app.inject({method:'POST',url:'/api/auth/logout',headers:headers(),payload:{}})).statusCode).toBe(200);expect((await service.app.inject({url:'/api/conversations',headers:{cookie}})).statusCode).toBe(401);expect(await service.store.listConversations(ownerId)).toHaveLength(1);});
it('an active session can unlink a Desktop Pet without a recent sign-in',async()=>{const device=randomUUID(),enrollment=randomUUID();await service.store.reserve(ownerId,device,enrollment);await service.store.redeem(ownerId,device,enrollment,'Home');await service.store.db.query('UPDATE sessions SET authenticated_at=? WHERE owner_id=?',[Date.now()-16*60*1000,ownerId]);const result=await service.app.inject({method:'DELETE',url:'/api/robot',headers:headers()});expect(result.statusCode).toBe(200);expect(result.json()).toMatchObject({ok:true,deviceId:device});expect(await service.store.body(ownerId)).toBeNull();});
it('local password hashing and deployment fail-closed checks',async()=>{const hash=await hashPassword('long enough phrase');expect(await verifyPassword('long enough phrase',hash)).toBe(true);expect(await verifyPassword('incorrect',hash)).toBe(false);expect(()=>config({NODE_ENV:'production'})).toThrow();expect(()=>config({HOST:'0.0.0.0',AUTH_MODE:'development'})).toThrow();expect(()=>config({MODEL_PROVIDER:'openai'})).toThrow();expect(safeReturnTo('//attacker.invalid')).toBe('/app');expect(safeReturnTo('/app/abc')).toBe('/app/abc');});
it('GitHub OAuth requires an allowlist and accepts only an exact allowed login',async()=>{
 const cfg=config({NODE_ENV:'test',AUTH_MODE:'github',GITHUB_CLIENT_ID:'client',GITHUB_CLIENT_SECRET:'secret',GITHUB_ALLOWED_USERS:'spedemon, ashtom'});
 const responses=[new Response(JSON.stringify({access_token:'token'}),{status:200}),new Response(JSON.stringify({id:42,login:'Spedemon',name:'Stefano'}),{status:200})];
 const github=new GithubIdentity(cfg,service.store,(async()=>responses.shift()!) as typeof fetch),flow=await github.begin('/app/conversation');
 const authorize=new URL(flow.url);expect(authorize.searchParams.get('redirect_uri')).toBe(cfg.APP_ORIGIN+'/auth/callback');expect(authorize.searchParams.has('scope')).toBe(false);const callback=new URL(cfg.APP_ORIGIN+'/auth/callback');callback.searchParams.set('code','code');callback.searchParams.set('state',authorize.searchParams.get('state')!);
 const result=await github.callback(flow.token,callback);expect(result.owner.name).toBe('Stefano');expect(result.returnTo).toBe('/app/conversation');
 const githubApp=await createApp(cfg,{database:sqliteDatabase(),provider:new FixtureTextProvider(0)});try{const start=await githubApp.app.inject('/api/auth/start?returnTo=%2Fapp');expect(start.statusCode).toBe(302);expect(start.cookies[0].path).toBe('/');expect(new URL(start.headers.location!).searchParams.get('redirect_uri')).toBe(cfg.APP_ORIGIN+'/auth/callback');}finally{await githubApp.app.close();}
 const deniedResponses=[new Response(JSON.stringify({access_token:'token'}),{status:200}),new Response(JSON.stringify({id:43,login:'not-allowed',name:null}),{status:200})],denied=new GithubIdentity(cfg,service.store,(async()=>deniedResponses.shift()!) as typeof fetch),deniedFlow=await denied.begin('/app'),deniedAuthorize=new URL(deniedFlow.url),deniedCallback=new URL(cfg.APP_ORIGIN+'/api/auth/callback');deniedCallback.searchParams.set('code','code');deniedCallback.searchParams.set('state',deniedAuthorize.searchParams.get('state')!);
 await expect(denied.callback(deniedFlow.token,deniedCallback)).rejects.toMatchObject({code:'IDENTITY_FORBIDDEN'});
 expect(()=>config({NODE_ENV:'test',AUTH_MODE:'github',GITHUB_CLIENT_ID:'client',GITHUB_CLIENT_SECRET:'secret'})).toThrow(/allowed username/);
});
it('local-dev cardless setup is authenticated, ephemeral and unavailable in secure modes',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'marvin-dev-card-')),file=join(dir,'card.json'),publicFile=join(dir,'device-public.pem'),keysFile=join(dir,'keys.json'),device=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),deployment=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),publicPem=device.publicKey.export({format:'pem',type:'spki'}).toString(),card={deviceId:deviceFingerprint(publicPem),username:'marvin-test',password:'private-development-secret'};writeFileSync(file,JSON.stringify([card]),{mode:0o600});writeFileSync(publicFile,publicPem,{mode:0o600});writeFileSync(keysFile,JSON.stringify({privateKey:deployment.privateKey.export({format:'pem',type:'pkcs8'}),receiptKey:'a'.repeat(64)}),{mode:0o600});
 const localPassword='a local test passphrase',local=await createApp(config({NODE_ENV:'test',APP_ORIGIN:'https://marvin.local',AUTH_MODE:'local',LOCAL_PASSWORD_HASH:await hashPassword(localPassword),LOCAL_DEV_SETUP_CARDS_FILE:file,LOCAL_DEV_DEVICE_PUBLIC_KEY_FILE:publicFile,HARDWARE_PROVISIONING_ENABLED:'true',ENROLLMENT_KEYS_FILE:keysFile,DEVICE_PUBLIC_ORIGIN:'https://marvin.local'}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0)});
 try{const localOrigin='https://marvin.local';expect(await local.store.db.query('SELECT device_id FROM device_identities')).toEqual([{device_id:card.deviceId}]);expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{origin:localOrigin}})).statusCode).toBe(401);const login=await local.app.inject({method:'POST',url:'/api/auth/login',headers:{origin:localOrigin},payload:{password:localPassword}}),localCookie=login.cookies[0].name+'='+login.cookies[0].value;expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,origin:'https://attacker.invalid'}})).statusCode).toBe(403);expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,'sec-fetch-site':'cross-site','sec-fetch-mode':'cors'}})).statusCode).toBe(403);expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,'sec-fetch-site':'same-origin','sec-fetch-mode':'navigate'}})).statusCode).toBe(403);expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,'sec-fetch-site':'same-origin','sec-fetch-mode':'cors'}})).json()).toEqual({card});expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,origin:localOrigin}})).json()).toEqual({card});expect((await local.app.inject('/api/config')).json().localDevSetupAvailable).toBe(true);}finally{await local.app.close();rmSync(dir,{recursive:true,force:true});}
 expect(()=>config({NODE_ENV:'test',DEPLOYMENT_MODE:'local-secure',LOCAL_DEV_SETUP_CARDS_FILE:'/private/card.json',APP_ORIGIN:'https://marvin.local'})).toThrow(/local-dev/);
 expect(()=>config({NODE_ENV:'test',LOCAL_DEV_DEVICE_PUBLIC_KEY_FILE:'/private/device-public.pem'})).toThrow(/matching setup card/);
 expect(()=>config({NODE_ENV:'test',DEPLOYMENT_MODE:'local-secure',APP_ORIGIN:'https://192.168.1.8'})).toThrow(/hostname/);
});
it('local-dev Pet registry registers every identity and reveals only the selected card',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'marvin-dev-pets-')),keysFile=join(dir,'keys.json'),registryFile=join(dir,'pets.json'),deployment=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),pets=[0,1].map(index=>{const device=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),publicKey=device.publicKey.export({format:'pem',type:'spki'}).toString(),card={deviceId:deviceFingerprint(publicKey),username:`marvin-test-${index}`,password:`private-development-secret-${index}`},cardFile=join(dir,`card-${index}.json`),devicePublicKeyFile=join(dir,`device-${index}.pem`);writeFileSync(cardFile,JSON.stringify(card),{mode:0o600});writeFileSync(devicePublicKeyFile,publicKey,{mode:0o600});return {label:`Pet ${index+1}`,card,cardFile,devicePublicKeyFile};});
 writeFileSync(keysFile,JSON.stringify({privateKey:deployment.privateKey.export({format:'pem',type:'pkcs8'}),receiptKey:'a'.repeat(64)}),{mode:0o600});writeFileSync(registryFile,JSON.stringify(pets.map(({label,cardFile,devicePublicKeyFile})=>({label,cardFile,devicePublicKeyFile}))),{mode:0o600});
 const localPassword='a local test passphrase',local=await createApp(config({NODE_ENV:'test',APP_ORIGIN:'https://marvin.local',AUTH_MODE:'local',LOCAL_PASSWORD_HASH:await hashPassword(localPassword),LOCAL_DEV_PETS_FILE:registryFile,HARDWARE_PROVISIONING_ENABLED:'true',ENROLLMENT_KEYS_FILE:keysFile,DEVICE_PUBLIC_ORIGIN:'https://marvin.local'}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0)});
 try{const localOrigin='https://marvin.local',expected=pets.map(({label,card})=>({label,deviceId:card.deviceId})),login=await local.app.inject({method:'POST',url:'/api/auth/login',headers:{origin:localOrigin},payload:{password:localPassword}}),localCookie=login.cookies[0].name+'='+login.cookies[0].value;expect(await local.store.db.query('SELECT device_id FROM device_identities ORDER BY device_id')).toEqual([...pets].map(pet=>({device_id:pet.card.deviceId})).sort((a,b)=>a.device_id.localeCompare(b.device_id)));expect((await local.app.inject({url:'/api/local-dev/setup-pets',headers:{cookie:localCookie,origin:localOrigin}})).json()).toEqual({pets:expected});expect((await local.app.inject({url:`/api/local-dev/setup-card/${pets[1]!.card.deviceId}`,headers:{cookie:localCookie,origin:localOrigin}})).json()).toEqual({card:pets[1]!.card});expect((await local.app.inject({url:'/api/local-dev/setup-card',headers:{cookie:localCookie,origin:localOrigin}})).statusCode).toBe(404);expect((await local.app.inject({url:'/api/local-dev/setup-card/marvin_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',headers:{cookie:localCookie,origin:localOrigin}})).statusCode).toBe(404);}finally{await local.app.close();rmSync(dir,{recursive:true,force:true});}
 expect(()=>config({NODE_ENV:'test',LOCAL_DEV_PETS_FILE:'/private/pets.json',LOCAL_DEV_SETUP_CARDS_FILE:'/private/card.json'})).toThrow(/replaces/);
});
it('websocket output is origin-routed, replayable, and stops immediately after logout',async()=>{
 const c=await service.store.createConversation(ownerId);
 const address=await service.app.listen({host:'127.0.0.1',port:0});
 const open=()=>new Promise<WebSocket>((resolve,reject)=>{const ws=new WebSocket(address.replace('http:','ws:')+'/api/events',{headers:{cookie,origin}});ws.once('open',()=>resolve(ws));ws.once('error',reject);});
 const sockets=await Promise.all(['r','other-route'].map(()=>open()));
 const observed:any[][]=[[],[]];
 await Promise.all(sockets.map((ws,index)=>new Promise<void>(resolve=>{ws.on('message',raw=>{const e=JSON.parse(raw.toString());observed[index].push(e);if(e.type==='subscribed')resolve();});ws.send(JSON.stringify({v:1,type:'subscribe',conversationId:c.id,routeId:index?'other-route':'r',after:0}));})));
 await service.app.inject({method:'PUT',url:'/api/robot/conversation',headers:headers(),payload:{conversationId:c.id}});
 await new Promise(r=>setTimeout(r,20));expect(observed.every(events=>events.some(e=>e.type==='conversation_link'))).toBe(true);
 const id=randomUUID();await service.runtime.start(await service.runtime.context(ownerId,c.id,id,'r'),'hello');await service.runtime.drain();
 await new Promise(r=>setTimeout(r,40));
 expect(observed[0].some(e=>e.type==='completed')).toBe(true);expect(observed[1].some(e=>e.type==='delta')).toBe(true);
 sockets[0].terminate();const replay=await open();const replayed:any[]=[];
 await new Promise<void>(resolve=>{replay.on('message',raw=>{const e=JSON.parse(raw.toString());replayed.push(e);if(e.type==='subscribed')resolve();});replay.send(JSON.stringify({v:1,type:'subscribe',conversationId:c.id,routeId:'r',after:0}));});
 expect(replayed.filter(e=>e.type==='delta').map(e=>e.text).join('')).toBe((await service.store.turns(ownerId,c.id))[0].assistantText);
 await service.app.inject({method:'POST',url:'/api/auth/logout',headers:headers(),payload:{}});
 const before=replayed.length;const closed=new Promise<number>(resolve=>replay.once('close',resolve));service.runtime.events.emit('event',{v:1,type:'delta',conversationId:c.id,interactionId:id,routeId:'r',seq:999,text:'must not arrive'},ownerId);
 expect(await closed).toBe(4401);expect(replayed).toHaveLength(before);sockets[1].terminate();
});
it('local passphrase login handles failure, intended route, expiration and cancelled identity flow',async()=>{
 const local=await createApp(config({NODE_ENV:'test',AUTH_MODE:'local',LOCAL_PASSWORD_HASH:await hashPassword('a local test passphrase')}),{database:sqliteDatabase(),provider:new FixtureTextProvider(0)});
 try{expect((await local.app.inject({method:'POST',url:'/api/auth/login',headers:{origin},payload:{password:'incorrect'}})).statusCode).toBe(401);
 const result=await local.app.inject({method:'POST',url:'/api/auth/login',headers:{origin},payload:{password:'a local test passphrase',returnTo:'/app/saved-conversation'}});expect(result.statusCode).toBe(200);expect(result.json().returnTo).toBe('/app/saved-conversation');const cookie=result.cookies[0].name+'='+result.cookies[0].value;
 expect((await local.app.inject({url:'/api/auth/session',headers:{cookie}})).json().owner.id).toBe(result.json().owner.id);
 await local.store.db.query('UPDATE sessions SET expires_at=?',[1]);expect((await local.app.inject({url:'/api/conversations',headers:{cookie}})).statusCode).toBe(401);
 const cancelled=await local.app.inject('/api/auth/callback?error=access_denied');expect(cancelled.statusCode).toBe(302);expect(cancelled.headers.location).toBe(origin+'/login?error=signin_failed');
 }finally{await local.app.close();}
});
